### ISSUE TITLE
[Dauphin] Voir si l'on peut récupérer les documents déposés chez eux

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1004]
Voir si via l'api (Cachée) on peut récupérer des documents déposés sur leurs plateformes

Si oui faire les tickets qui vont bien

Pour se faire, jouer sur le dashboard et essayer de trouver les routes menant aux documents

https://agent-dauphin.cget.gouv.fr/agents/#/cget/dashboard

**Comment by VSerain** [comment]
Ténir au courrant les bizdev des découvert

**Comment by alice-telescoop** [comment]
J'aurais bien tenté mais il me manque les accès

**Comment by VSerain** [comment]
> J'aurais bien tenté mais il me manque les accès

Je te partage sur dashlane

**Comment by alice-telescoop** [comment]
À partir d'une demande, on peut faire les appels GET
`https://agent-dauphin.cget.gouv.fr/referentiel-financement/api/tenants/cget/demandes-financement/ByIAZDbxO
?expand=pieces.documents` qui les documents au chemin `result.pieces` au format 
```{
    reference: string,
    libelle: { value: string },
    description: {value: string },
    modeTransmission: string,
    conforme: boolean,
    fonction: string,
    obligatoire: boolean,
    obligatoireSurRecevabilite: boolean,
    documents: {
        id: string,
        href: string, // this is what we want to download later
        title: string,
        rel: string,
        expand: [...]
    }[]
}
```


À partir d'un asso (d'un tiers pour leur nomenclature) on les récupère via un GET à `https://agent-dauphin.cget.gouv.fr/referentiel-tiers/cget/tiers/41fPMDsxf8
?expand=pieces.documents` au chemin `result.pieces` au format 
```{
    reference: string,
    libelle: { value: string, lang: string },
    documents: [...] // same than previous cas
}
```

Attention, potentiellement plusieurs documents (fichiers) pour une même pièce. Je pense qu'il doit y avoir par exemple pour des cartes d'identité un fichier pour le recto et un pour le verso.

Autre pb, l'identifiant utilisé dans l'url est un identifiant interne dauphin, auquel on peut accéder via une requête POST  à `https://agent-dauphin.cget.gouv.fr/referentiel-tiers/cget/tiers/search/fullText` avec le body 
```
{
  "from": 0,
  "size": 10,
  "type": "tiers",
  "query": "808393763", // what we would search in the web interface
  "facets": {
    "famille": [
      "Association"
    ],
    "status": [
      "SUPPORTED"
    ]
  }
}
```

Alors l'url à appeler est dans `result.hits[0]._source.id` en supposant que l'association recherchée est bien le premier résultat de la recherche

**Comment by alice-telescoop** [comment]
Dans mes tests j'ai eu des pb d'authentification mais je pense que c'est parce que je fais ça en investigation depuis le navigateur

**Comment by alice-telescoop** [comment]
@VSerain @mxmeunier faut-il chercher plus ? Je ne sais pas s'il y a des choses à cibler

**Comment by mxmeunier** [comment]
> @VSerain @mxmeunier faut-il chercher plus ? Je ne sais pas s'il y a des choses à cibler

Ca me va tu as l'air d'avoir fait le tour. Pour clôturer ce ticket je propose que tu rédiges un ticket `Récupérer les documents Dauphin` en reportant les informations de ton investigation. :)

**Comment by alice-telescoop** [comment]
Oui c'est dans `reference` et dans `libelle`

**Comment by VSerain** [comment]
Ok, est-ce que tu peut récupérer un échantillon pour qu'on est un exemple des documents possible, et apres on fait un ticket pour que le dauphin service devienne un document Provider !

**Comment by alice-telescoop** [comment]
C'est pas clair pour moi pour deux raisons : 
- je vais vraisemblablement rater des trucs parce que je ne peux que regarder pour quelques essais ce qu'il y a 
- il y a des documents "demande" et des documents "asso". Je fais ça pour les deux ? A priori ce ne sont pas les mêmes. Quand il y a des documents en commun (ex statuts de l'asso) il sont enregistrés en double chez eux

**Comment by VSerain** [comment]
1. Oui le but c'est de voir a peut pres ce qu'on peut récupérer ! On présisera bien que c'est ni exostif ni garentie
2. Pour le moment on ne remonte que des documents liée à l'asso ! Donc, je dirais qu'on commence par ça ! En revanche peut être qu'il serait intéressent de remontée aussi des documents liée à une subvention, on peut posser la question au bizdev dans leurs channel si ils repondent positivement on fait un ticket reflection chez nous pour voirs comment on attaque le soucis

**Comment by alice-telescoop** [comment]
J'ai complété avec les types de documents récupérables

**Comment by alice-telescoop** [comment]
Vu avec Louis : ce sont des documents qu'on a déjà mais intéressant quand même. Mis à l'ordre du jour du point solution du 26 avril pour savoir comment on en tire profit. Donc on ne crée pas les tickets de suite
