### ISSUE TITLE
[Gispro] Réfléchir à un moyen de lier les données GISPRO et dauphin de manière propre !

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1007]
Il faut se poser 10min pour voir architecturalement comment on fait pour lier les deux providers

Peut-être que Dauphin appelle Gispro ou l'inverse
Ou bien on fait une jointure entre gispro et la table de cache dauphin
ou bien subvention service sait qu'il doit lier les demandes entre elles par un système de clé 
ou bien ....

PS: GISPRO comprend un n°EJ et un n° de dossier Dauphin

Point vendredi 17 mars 2023

**Comment by mxmeunier** [comment]
@VSerain pourquoi doit-on faire cohabiter Dauphin avec Gispro ? Ce dernier ne contient-il pas déjà les données de Dauphin ?

**Comment by VSerain** [comment]
> @VSerain pourquoi doit-on faire cohabiter Dauphin avec Gispro ? Ce dernier ne contient-il pas déjà les données de Dauphin ?

Car ce sont 2 provider de données différent, et que même si gispro intègre une partie de data dauphin, elles n' y sont pas tout et ne seront pas mise à jour avec la même régularité !

**Comment by VSerain** [comment]
On souhaite intégrer les données Gispro directement dans les données Dauphin (dans la même table).
Ça signifie changer notre façon de traiter les données dauphin.
Pour rappel celle-ci sont mise à jour appel à Dauphin (api).

Donc, on doit changer le nom de la table en 'dauphin-gispro'.
Le format de base serait (Id de jointure à re-def par @VSerain) : 
```
{
    dauphin : DauphinDTO
    gispro: {} // Format à définir suivant le fichier    
}
```
Modifier les adapters pour passer de dauphin -> sub à dauphin && gispro -> sub.
Le plus important étant de rajouter le n'EJ

Ne plus faire de call à l'api dauphin à chaque fois où l'on nous demande des sub (Faire en prio #683 #685)
