### ISSUE TITLE
[AssociationName] Pour la recherche ne faire une recherche que sur les données historyUnitéeLegal

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1015]
Ne rechercher que `provider.name === "Base Sirene - DataGouv"`

Créer un index sur le provider de la table association-name

**Comment by mxmeunier** [comment]
@VSerain dans association-name les imports historyUnitéeLegal viennent de "Base Sirene - DataGouv" ou "Base Sirene" ?

**Comment by VSerain** [comment]
Du coup, j'ai juste mieux ordonné pour que le nom de provider fiable remonte en premier
