### ISSUE TITLE
Voir pour trouver le BOP dans les versements fonjep

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1019]
Créer une collection bop-financeur-fonjep contant les données du tableau ci-dessous.

Créer une jointure entre bop-financeur-fonjep et versement-fonjep pour récupérer le bop et l'ajouter au versement  d'après le code financeur

**Comment by mxmeunier** [comment]
Voir avec Yasmine comment récupérer le BOP

**Comment by mxmeunier** [comment]
![Image](https://user-images.githubusercontent.com/7630775/231220426-5ae291d7-1ada-46ee-99d1-f1192ef39803.png)

**Comment by alice-telescoop** [comment]
on a une réponse donc ? -> Ready ?

**Comment by mxmeunier** [comment]
Yep par contre le ticket se transforme un peu.

2 possibilité : 
- le front connait le métier et a une liste FinanceurCode - BOP pour afficher le bop
- on fait une migration mongo pour ajouter bop sur chaque FonjepVersement et on modifie le parser pour qu'il l'ajoute également

On en parle au point ticket

**Comment by alice-telescoop** [comment]
cf #1393
