### ISSUE TITLE
Erreurs login non remontées

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1023]
Le erreurs sur la page /auth/login ne sont plus remontées (la page /auth/login est rechargée et on aperçoit l'erreur 1/2s)

**Comment by alice-telescoop** [comment]
C'est parce que les erreurs de login remontent un 401, qui depuis #983 redirige vers la page d'accueil. @VSerain il faut qu'on reprenne la conception de ça (et est-ce que c'est en préprod/prod avec ce comportement ?)

**Comment by mxmeunier** [comment]
Je confirme que l'erreur est en preprod

**Comment by mxmeunier** [comment]
Je confirme que l'erreur est en prod. :(

**Comment by alice-telescoop** [comment]
ok. Je suis en train de tester un fix, qui du coup passera en hotfix ^^

**Comment by VSerain** [comment]
> C'est parce que les erreurs de login remontent un 401, qui depuis #983 redirige vers la page d'accueil. @VSerain il faut qu'on reprenne la conception de ça (et est-ce que c'est en préprod/prod avec ce comportement ?)

On est pas allez jusqu'au bout ? On peut refaire des tickets si besoin

**Comment by alice-telescoop** [comment]
Ben ç'a créé un bug. Mais ça va pour la conception j'ai trouvé un fix qui ne change pas le principe
