### ISSUE TITLE
Notifier les utilisateurs inactifs depuis 5 mois

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1032]
Il faut envoyer un mail contenant le message :

>Bonjour,
>
>vous êtes inscrits à Data.Subvention.
>Cependant nous observons que votre compte est inactif depuis un an.
>Nous allons supprimer votre compte sous 15 jours.
>Si vous souhaitez le conserver, il vous suffit de vous connecter à Data.Subvention https://datasubvention.beta.gouv.fr/

stuck by https://github.com/betagouv/api-subventions-asso/issues/684

**Comment by mxmeunier** [comment]
@VSerain @natoine @Gttnmarion

**Comment by VSerain** [comment]
> @VSerain @natoine @Gttnmarion on a réfléchi à un message ?

On demande au bizdev ?

**Comment by natoine** [comment]
Bonjour,

vous êtes inscrits à Data.Subvention.
Cependant nous observons que votre compte est inactif depuis un an.
Nous allons supprimer votre compte sous 15 jours.
Si vous souhaitez le conserver, il vous suffit de vous connecter à Data.Subvention : https://datasubvention.beta.gouv.fr/

**Comment by Gttnmarion** [comment]
Un template avait déjà été produit : Inactivité de compte - 1e mail avant suppression de compte
Sur Sendiblue : id #89

**Comment by alice-telescoop** [comment]
oups j'avais même pas vu ! @Gttnmarion ça rejoins ce qu'on s'est dit à midi. Mais du coup il faudrait configurer l'envoi de ça depuis brevo

**Comment by Gttnmarion** [comment]
> oups j'avais même pas vu ! @Gttnmarion ça rejoint ce qu'on s'est dit à midi. Mais du coup il faudrait configurer l'envoi de ça depuis brevo

CF du coup mon ticket :) : [#2032](https://github.com/betagouv/api-subventions-asso/issues/2032)
