### ISSUE TITLE
[CHORUS] implémenter date de paiement dateOperation

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1039]
stuck by #1055

**Comment by mxmeunier** [comment]
@VSerain date de paiement = dateOperation ?

**Comment by mxmeunier** [comment]
@VSerain cf #1037 le ticket mentionne que le SubventionDTO mais du coup c'est aussi VersementDTO ?

Quel champs pour quel DTO ?

**Comment by VSerain** [comment]
Oui date de paiement = dateOperation dans le cadre de CHorus !
Et tous est dans subventionDto sauf la date de paiement qui elle est cotée versement !

Enfin pour le moment

**Comment by alice-telescoop** [comment]
à réinvestiguer
