### ISSUE TITLE
Ranger les fichiers css

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1081]
- regrouper (si bien pertinent) les fichiers `global.css` et `custom.css`
- minifier `svelte.css` (configurer webpack pour)
- ne pas versionner les fichiers style du build (`svelte.css`)

**Comment by mxmeunier** [comment]
Piste : supprimer `custom.css` normalement utilisé que dans l'EJS

**Comment by alice-telescoop** [comment]
done in #1545
