### ISSUE TITLE
S'assurer que la selection au clavier des lignes du tableau passe d'une subvention aux versements

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1084]
stuck by : attendre d'avoir fusionné le tableau pour voir si c'est toujours d'actualité

Pour la navigation au clavier :
ne pas faire tout le tableau des demandes avant d'arriver sur le tableau des versements

**Comment by mxmeunier** [comment]
Sera fait dans #2684
