### ISSUE TITLE
[Extract CSV] La colonne Centre financier contient "false" quand il n'y a pas de versement

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1092]
Voir pourquoi on retourne pas "-" ou vide

**Comment by mxmeunier** [comment]
Non reproductible sur develop. Par contre on affiche le 0,00€ quand il n'y a pas de versement

**Comment by mxmeunier** [comment]
W751003066
W863000563

**Comment by mxmeunier** [comment]
Toujours non reproductible avec ces deux RNA. J'ai bien des "-" au téléchargement (sur develop)
