### ISSUE TITLE
Optimiser les taille des builds

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1098]
Le build FRONT embarque le build API et inversement. Pour limiter la taille des builds il est nécessaire de limiter ce qui est embarqué dans chaque appli.

La mise à jour de Lerna en version 6 et l'utilisation du système de packages permet de définir de quel build dépendent API et FRONT.

Investiguer aussi sur [`.slugignore`](https://doc.scalingo.com/platform/app/slugignore) pour supprimer les fichiers non nécessaire au runtime de l'app

**Comment by alice-telescoop** [comment]
@VSerain Tu l'as fait du coup non ?

**Comment by mxmeunier** [comment]
@VSerain à supprimer du coup ?

**Comment by VSerain** [comment]
Oui mes capitaines
