### ISSUE TITLE
Concevoir le DTO du socle commun Datasub

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1103]
Une fois le DTO créé, créer un ticket pour chaque provider pour investiguer / mettre en place l'adapter vers ce nouveau format.

-----------------------

L'idée en terme d'archi, c'est que les services des providers implémentent `toGrant()`, `toApplication()` et `toPayment()` pour que le service agrégateur prenne les résultats de `toGrant()` tels quels, et les résultats de `toApplication()` et `toPayment()` pour les relier ensemble.

tickets créés :

- [ ] #1191
- [ ] #1192
- [ ] #1193
- [ ] #1194

**Comment by alice-telescoop** [comment]
cf #479 ?

**Comment by mxmeunier** [comment]
tickets créés : #1191 #1192 #1193 #1194

**Comment by alice-telescoop** [comment]
| champ               	| osiris                     	| dauphin -gispro            	| ds         	| caisse des dépôts           	| fonjep   	| chorus                 	|
|---------------------	|----------------------------	|----------------------------	|------------	|-----------------------------	|----------	|------------------------	|
| exercice            	| extract year               	| exerciceBudgetaire         	| date_debut 	| date_convention             	| ✔        	|                        	|
| service_instructeur 	| ✔                          	| **financeursPrivilegies[0] ⚠** 	| ✔          	| nom_attribuant              	| ✔        	|                        	|
| dispositif          	| ✔                          	| "Politique de la ville"    	|            	| **« Caisse des dépôts ? »** 	| ✔        	|                        	|
| montant.accorde     	| ✔                          	| ✔                          	|            	| ✔                           	| ✔        	|                        	|
| montant.demande     	| ✔                          	| ✔                          	|            	| on accepte undefined ici    	| ✔        	|                        	|
| objet               	| actions.intitulé (aggrégé) 	| intitule projet            	| 〰         	| ✔                           	| **TODO** 	|                        	|
| statut              	| ✔                          	| virtualStatusLabel         	| **TODO**   	|  « Accordé »                	| ✔        	|                        	|
| siret               	| ✔                          	| ✔                          	| ✔          	| idbeneficiaire              	| ✔        	| ✔                      	|
| montant versé       	|                            	|                            	|            	| ✔                           	| ✔        	| ✔                      	|
| bop                 	|                            	|                            	|            	| **?**                       	| ✔        	| ✔                      	|
| periode_debut       	|                            	|                            	|            	| ✔                           	| ✔        	| date premier versement 	|
