### ISSUE TITLE
Créer une route pour le DTO du socle commun

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1105]
stuck by 
- [x] ~~#1103~~ 
- [x] #1325 

Créer une route retournant des subvention/versements au nouveau format

**Comment by VSerain** [comment]
Je pense qu'il faut créer un nouveau service qui permet de demandes au diférent provider si il on des données au nouveau format !
En suite dans les controlleurs association et etablissement on créer un /{NOM du Socle Commun} qui call se service !

Au debut, il ne retournerait qu'une partie des données et puis plus de provider implémente le nouveau format alors on aura plus de données !

**Comment by alice-telescoop** [comment]
Dans l'idée oui, avec quand même la logique dans le service de "est-ce que j'envoie le format complet ou est-ce que j'ai besoin de me trouver mes versements" donc ya de la conception. Je sais pas s'il faut le faire en mont du ticket ou si c'est le ticket justement. 
Je dirais de le scinder en "faire la route" et "faire le service" et "faire le service" est pas un petit ticket

**Comment by VSerain** [comment]
Ok avec toi ! Je propose ta solution, faire une ticket pour le service et ce ticket deviens stuck par le ticket service !
