### ISSUE TITLE
Lister les routes qui se basent sur la collection `log`

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1120]
Faire la liste des routes liées aux statistiques qui se basent sur la table de `log`.

Créer un ticket pour chaque route afin d'utiliser la collection `associationVisit` à la place

**Comment by mxmeunier** [comment]
`stats/request`

**Comment by mxmeunier** [comment]
@VSerain j'ai un petit doute quant à l'exhaustivité de ma liste, je n'ai trouvé que 3 routes utilisant le `statsRepository` lui même lié à la collection `log`. C'était tellement rapide et regroupé que je me demande si je loupe pas un endroit. J'ai regardé dans le  `UserController` ainsi qu'effectué une recherche sur `db.collection("log")` et ça ne donne rien de plus !

**Comment by mxmeunier** [comment]
tickets #1186 #1187 #1188

**Comment by VSerain** [comment]
Je regarde

**Comment by mxmeunier** [comment]
> Je pense qu'on à des doublon: #984 && #1109

Je pense aussi. Je ferme #984

**Comment by VSerain** [comment]
Ok pour ça aussi : https://github.com/betagouv/api-subventions-asso/issues/1120#issuecomment-1495897777 ?
