### ISSUE TITLE
Modifier le nom de domaine de l'outil

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1170]
Faire pointer le nom de domaine actuel vers la landing page (https://datasubvention.beta.gouv.fr)
Choisir un nouveau nom de domaine pour l'app (https://app.datasubvention.beta.gouv.fr ??)

Il faut aussi ajouter un plugin wordpress pour rediriger les anciennes url vers les nouvelles

voir :

-  https://fr.wordpress.org/plugins/redirection/
- https://redirection.me/

**Comment by mxmeunier** [comment]
Quels sont les nouveaux noms de domaine pour le Front et la Landing page ?

**Comment by mxmeunier** [comment]
waiting validation : validation du domaine pour l'outil

**Comment by VSerain** [comment]
Pour le front: https://app.datasubvention.beta.gouv.fr/
Pour l'api : https://api.datasubvention.beta.gouv.fr/
Pour le blog : https://datasubvention.beta.gouv.fr/

**Comment by VSerain** [comment]
A faire à un moment ou il n'y a presonne

**Comment by mxmeunier** [comment]
S'assurer du lancement d'une news / notification sur le blog du changement de nom de domaine

**Comment by alice-telescoop** [comment]
Du coup c'est fait si j'ai bien compris (même si chez moi ça n'est pas encore effectif mais DNS you know)
