### ISSUE TITLE
Utiliser `associationVisit` pour la route `stats/request`

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1186]
Ne plus appeler `statsRepository` mais `statsAssociationsVisitRepository` et modifier la méthode appelée en conséquence.

stuck by #1300

**Comment by mxmeunier** [comment]
@VSerain j'ai besoin de faire un dump prod pour avoir les données de la collection `stats-association-visit` mais avec mon souci de mdp à saisir à chaque fois sur les connexions scalingo + le fait que ça touche la prod je veux pas pousser tout seul de peur de faire une bêtise (je suis pas trop habitué ce genre de commande)

Je te ping quand j'ai du temps cette semaine pour que tu m'assiste!

**Comment by VSerain** [comment]
> @VSerain j'ai besoin de faire un dump prod pour avoir les données de la collection `stats-association-visit` mais avec mon souci de mdp à saisir à chaque fois sur les connexions scalingo + le fait que ça touche la prod je veux pas pousser tout seul de peur de faire une bêtise (je suis pas trop habitué ce genre de commande)
> 
> Je te ping quand j'ai du temps cette semaine pour que tu m'assiste!

Yes, je peut te filler un dump si besoin
