### ISSUE TITLE
Mettre en place un outil de suivi des erreurs

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1239]
Maintenant, quand on rencontre une erreur, soit elle crash l'application et on peut avoir l'info sur scalingo, soit elle est rattrapée et on n'en entend pas parler (alors même qu'on pourrait vouloir le savoir et/ou qu'elle envoie potentiellement une 500) (c'est ce que va faire le ticket #1221).
Je propose d'utiliser Sentry, Rollbar ou Bugsnag pour être alerté de ces erreurs.
Chez TelesCoop on utilise Rollbar qui a une version gratuite aux fonctionnalités conséquentes

EDIT : faire les démarches pour obtenir un compte Sentry

**Comment by mxmeunier** [comment]
https://mattermost.incubateur.net/betagouv/pl/pc5cfyrfgiy4zjqtr8w9htzdzc

**Comment by alice-telescoop** [comment]
https://sentry.incubateur.net/betagouv/api/getting-started/node/ installer sur les différents packages

**Comment by alice-telescoop** [comment]
aller + loin avec les releases : https://docs.sentry.io/api/releases/create-a-new-deploy-for-an-organization/
