### ISSUE TITLE
Mettre à jour les stats statiques de la LP

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1268]
En duo avec @gttnmarion

**Comment by Gttnmarion** [comment]
@mxmeunier ou quelqu'un d'autre, pour pouvoir mettre à jour les stats de la LP il me faut :

- le nombre de users inscrits
- Le nombre d'utilisateurs fidèles (ayant fait plus de 100 requêtes depuis leur inscription)
- Le nombre de visites par semaine (* pages consultées c’est à dire, vues de pages uniques par utilisateurs)
- Le nombre d'utilisateurs à date du 1e avril et 3 mai
- Le nombre total de recherches effectuées à date du 1e avril et 3 mai

Comment est-ce qu'on peut automatiser ça sur Wordpress pour que ce soit plus simple pour tout le monde à terme ? :)

Dispo pour faire un point si besoin! merciii

**Comment by mxmeunier** [comment]
> @mxmeunier ou quelqu'un d'autre, pour pouvoir mettre à jour les stats de la LP il me faut :
> 
> * le nombre de users inscrits a date du jour
> * Le nombre d'utilisateurs fidèles (ayant fait plus de 100 requêtes depuis leur inscription) à date du jour
> * Le nombre de visites par semaine (* pages consultées c’est à dire, vues de pages uniques par utilisateurs) à date du jour
> * Le nombre d'utilisateurs à date du 1e avril et 3 mai
> * Le nombre total de recherches effectuées à date du 1e avril et 3 mai
> 
> Comment est-ce qu'on peut automatiser ça sur Wordpress pour que ce soit plus simple pour tout le monde à terme ? :)
> 
> Dispo pour faire un point si besoin! merciii

Hello @Gttnmarion ! Toujours d'actualité ou déjà mis à jour ? J'étais pas trop là cette semaine

**Comment by Gttnmarion** [comment]
Oui toujours d'actualité uniquement pour la partie concernant le nombre d'utilisateurs à date (1e avril et 5 mai) et pour le nb total de recherche (1e avril et 5 mai). C'est pour mettre a jour le tableau :)

![image](https://user-images.githubusercontent.com/114912799/236468246-94bc0df6-58ae-4028-b26c-c4a2e8fc93ca.png)

**Comment by alice-telescoop** [comment]
### Utilisateurs
- 1er avril : 1124
- 1er mai : 1207
- 9 mai (si tu veux quand même en faire qqchose) : 1224

**Comment by alice-telescoop** [comment]
# Requêtes/visites

- total mars : 33 458
- total avril : 15 910
- total mai (1er mai -> aujourd'hui) : 1 738 requêtes

**Comment by Gttnmarion** [comment]
Merci ! Si tu as également les dates de janvier 2022 à Février 2023 je suis preneuse, je ne les retrouve plus dans mes notes :'(
