### ISSUE TITLE
Bug stats utilisateurs

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1278]

**Comment by mxmeunier** [comment]
![Image](https://user-images.githubusercontent.com/7630775/236409549-2974ec90-b557-45ff-8957-890801e3ef5c.png)

**Comment by alice-telescoop** [comment]
Peut-être résolu par #1186 ?

**Comment by VSerain** [comment]
Je close car ça passe par metabase maintenant
