### ISSUE TITLE
Formaliser/documenter notre proposition du format SCDL enrichi

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1315]
Résultats ici : [GitHub SCDL DataSubvention](https://github.com/betagouv/SCDL-Subvention-DataSubvention)

**Comment by alice-telescoop** [comment]
@VSerain tu as des notes de ça je crois

**Comment by VSerain** [comment]
Je regarde ça @VSerain et on fait un point
