### ISSUE TITLE
Lister les contacts "administration responsable" par fournisseur

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1321]
cf [cette maquette figma](https://www.figma.com/file/t6nWdBwKr8fancez3VO5kr/Data.Subvention-V0.4?type=design&node-id=10006-114127&t=iUM4O8l0mEJkg08J-0)

- créer document pour le co-remplir avec les autres membres de l'équipe
- savoir comment le stocker

**Comment by alice-telescoop** [comment]
demander bizdev
pour l'instant juste osiris

**Comment by alice-telescoop** [comment]
https://mattermost.incubateur.net/betagouv/pl/pb9htoj41pd69m6h4bh345csqy

**Comment by mxmeunier** [comment]
On peut faire le dev et afficher "pas d'info" ou cacher le champs pour les providers manquant afin de faire avancer les choses

**Comment by VSerain** [comment]
C'est Alix la chef

**Comment by VSerain** [comment]
En attente de les prévenir avant de mettre en prod ! ps: Alix à déjà fait le document

**Comment by VSerain** [comment]
https://docs.google.com/spreadsheets/d/1KvtV5U9zNu79MN3W7PtlaBX1CKR961tAzyi7BElS0U4/edit#gid=0

**Comment by mxmeunier** [comment]
@VSerain fais un message à alix

**Comment by VSerain** [comment]
Message envoyer à alix et il faut qu'on face un message à Yasmine

**Comment by mxmeunier** [comment]
Vrai point en vrai avec alix
