### ISSUE TITLE
S'assurer du bon traitement des données FONJEP

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1344]
Faire un état du traitement des données FONJEP (côté front, `linkVersementsToSubvention`).

Vérifier avec Yasmine que l'on fait bien de ne garder que la dernière année sur les trois (subvention sur trois années).
On a vu qu'il y avait parfois 4 demandes pour les trois ans, donc potentiellement des départs/arrivés sur les trois ans. Vérifier qu'on traite bien ce sujet.

S'assurer que ne garder que la dernière année est une bonne idée et voir si on a cumulé les trois ans de versements sur une seule année

**Comment by mxmeunier** [comment]
Voir W751003066 exercice 2021

**Comment by alice-telescoop** [comment]
duplicates #1343
