### ISSUE TITLE
Réfléchir à un format pour stocker les données SCDL/Subvention

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1364]
L'idée est de sauvegarder ces données dans une même collection mais

1) garder la date d'import et/ou la date de création du jeu de donnée
2) garder le nom du "provider" (nom de mairie, etc)

**Comment by alice-telescoop** [comment]
colonnes :
- `source`
- `importDate`
- `dataGouvId` # pour pouvoir mettre à jour certains fichiers ?
- ...les champs du SCDL
