### ISSUE TITLE
Mettre à jour la fiche contact Brevo après la mise à jour d'un utilisateur

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1366]
STUCK BY: création de la partie modification dans la page profil utilisateur

**Comment by mxmeunier** [comment]
J'ai juste accéder à a la [doc](https://developers.brevo.com/reference/getting-started-1) et vu qu'il y avait une méthode pour ajouter ou mettre à jour un contact.

**Comment by alice-telescoop** [comment]
Il va falloir faire ça pour que les infos du formulaire d'inscription remontent sur brevo

**Comment by alice-telescoop** [comment]
Et pas sûre que ce soit stuck du coup

**Comment by alice-telescoop** [comment]
Définir le nom des champs pour brevo pour que ce soit bien clair pour les bizdevs. Notamment pour `jobType` qui est un tableau, càd un format de données que brevo ne gère pas (d'après Alix tout à l'heure)

**Comment by mxmeunier** [comment]
ca me paraît étonnant qu'ils ne gère pas les tableaux. Après si les props peuvent être nommées librement il suffit de faire du jobType1 jobType2 etc

**Comment by alice-telescoop** [comment]
Je confirme que les types attendus par l'API brevo sont bien des string[^1]. Après peut-être que brevo les re-parse derrière je serais curieuse de voir l'interface web

[^1]: https://developers.brevo.com/reference/updatecontact

**Comment by alice-telescoop** [comment]
En attente des traductions demandées potentiellement par les bizdevs des noms de champs

**Comment by alice-telescoop** [comment]
Et pour moi c'est plus stuck

**Comment by VSerain** [comment]
> Quelle séparateur pour simuler un tableau ?

je dirait ","

**Comment by alice-telescoop** [comment]
Je note la question pour voir avec les bizdevs si qqchose les arrange. A priori ce sera bien `,` mais je sais pas peut-être qu'ils vont faire des export csv et que ça ferait du bazar. Mais c'est pas à trancher entre nous et on a prévu de faire un point

**Comment by alice-telescoop** [comment]
Pour les valeurs des champs radio : soit on transmet un nombre à mapper (en attente de Louis qui attend la réponse de brevo) soit l'intitulé affiché sur le front
