### ISSUE TITLE
Ajouter la partie Information sur votre Profil de la page utilisateur

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1370]
stuck by #1309 

[Figma](https://www.figma.com/file/t6nWdBwKr8fancez3VO5kr/Data.Subvention-V0.4?type=design&node-id=9953-147684&t=vx356ZCHSdImhBO8-0#452885480)

**Comment by alice-telescoop** [comment]
duplicates #1667
