### ISSUE TITLE
Maquetter une page budget

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#1402]
On peut trier par la colonne "budget" pour s'inspirer des bons élèves

- https://annuaire-entreprises.data.gouv.fr/budget
- urssaf
- https://pad.incubateur.net/s/qeT5bzHUM#Minist%C3%A8re-de-la-culture-atelier-num%C3%A9rique
- https://doc.transport.data.gouv.fr/le-point-d-acces-national/generalites/budget
- https://beta-gouv-fr-budget.netlify.app/?budget=800000&date=2022-07-13&start=2021-03-15&startup=Aides+Jeunes&startupId=aides.jeunes

**Comment by Gttnmarion** [comment]
https://blog.datasubvention.beta.gouv.fr/?page_id=1423&preview_id=1423&preview_nonce=10c0929261&preview=true

**Comment by Gttnmarion** [comment]
https://docs.google.com/spreadsheets/d/e/2PACX-1vTSrwRiBYO3Rwf9ZPmqvj5caKznKFynTReHPseAePT01cITi_yVprtLRULNDZcatn_0pM5tYD-fnXvw/pubchart?oid=1770050582&format=interactive
 
https://docs.google.com/spreadsheets/d/e/2PACX-1vTSrwRiBYO3Rwf9ZPmqvj5caKznKFynTReHPseAePT01cITi_yVprtLRULNDZcatn_0pM5tYD-fnXvw/pubchart?oid=1843371449&format=interactive
 
@VSerain @mxmeunier @alice-telescoop je vais avoir besoin de l'un de vous quand vous aurez une dispo pour intégrer ces graph sur WordPress parce que. jesais pas faire hahaha

**Comment by mxmeunier** [comment]
J'ai rien vu j'entend rien et je sais pas faire :p

Je veux bien regarder mais j'y connais que tchi en WordPress
