### ISSUE TITLE
S'assurer d'envoyer un code 404 sur le front au lieu d'une 200

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1404]
On parle de l'accès à des pages inexistants (!= ressources)

stuck by #1442

**Comment by VSerain** [comment]
Stuck tant qu'on a pas mis sveltekit ou autre

**Comment by alice-telescoop** [comment]
https://thegray.company/blog/single-page-application-spas-404s-seo

même pour un SPA avoir un petit peu de server side est conseillé

**Comment by alice-telescoop** [comment]
done in #1545
