### ISSUE TITLE
Faire une déclaration d'accessibilité

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1410]
https://betagouv.github.io/a11y-generateur-declaration/#create

la mettre sur `/accessibilite`

Créer une page front qui affiche le PDF

**Comment by VSerain** [comment]
C'est à qui de sens occupé ?

**Comment by mxmeunier** [comment]
Le remplir avec un bizdev / Yasmine

**Comment by mxmeunier** [comment]
penser à rajouter le lien vers `/accessibilite` dans le footer

**Comment by alice-telescoop** [comment]
[message prise de rdv](https://mattermost.incubateur.net/betagouv/pl/rs4jw9788in79brzp6a3j6kqfr)
