### ISSUE TITLE
Reprendre stack front - sveltekit

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1442]
investigation et présentation de plusieurs propositions

**Comment by VSerain** [comment]
Quesaco ?

**Comment by alice-telescoop** [comment]
Faut faire un point pour avoir une archi front propre et pensée (sveltekit ou autre)

**Comment by alice-telescoop** [comment]
## sveltekit

- À chaque fois que je cherche les gens me redirigent là-dessus
- il permet du SSR pas obligatoire, facile si on veut le faire
- il prévoit [une structure de fichiers particulière](https://kit.svelte.dev/docs/project-structure) qui va nous faire
    - décaler pas mal de code dans `src/lib`
    - renommer `views` en `routes` mais aussi les composants "page" en `+page.svelte`
- il va proposer plein de choses qu'on ne sera pas obligés d'utiliser mais qui vont être tentantes donc on devra être vigilants pour rester homogènes
    - dans le traitement des formulaires et chargement des premières données
    - pour potentiellement faire du SSR
- la gestion des 404 et du routing va être très simplifiée donc ça demandera du clean 

## express
- on peut continuer mais il faudrait un refacto pour clean ce qu'on ne garde pas
- [une base pour express + svelte + typescript](https://github.com/vonazt/svelte-express-typescript)
- il existe [express-svelte](https://github.com/maxiruani/express-svelte) pour que svelte soit compris par express comme le langage de templating, mais il n'est plus maintenu
- permettrait d'avoir qques redirections mais conserve le pb de 404 à moins de (**re-**)basculer tout notre routing dessus

## simple SPA - vite
on peut utiliser vite et déployer directement (cf [tuto](https://eternaldev.com/blog/build-and-deploy-apps-with-svelte-and-vite))
- on se gardera indéfiniment des codes 200 pour la page 404, ce qui peut notamment 
    - amener à ce que la 404 soit indexée sur google 
    - faire des faux positifs sur dashlord

## `single-spa`
- il existe [`single-spa`](https://github.com/single-spa/single-spa) qui fait une sorte de service minimum de service
- comme express, permettrait d'avoir qques redirections mais conserve le pb de 404 à moins de basculer tout notre routing dessus
- voici [le tuto pour svelte](https://single-spa.js.org/docs/ecosystem-svelte/)

----------

Je plussoie svelteKit même si c'est du taff et une nouvelle aventure de possibilités à discuter de si on les utilise ou pas

**Comment by VSerain** [comment]
> Merci pour ces recherches @alice-telescoop !
> 
> Je penche pour **SvelteKit** pour trois raisons :
> 
>     1. Amélioration du routine
> 
>     2. Stabilité et communauté autour de la solution
> 
>     3. J'ai envie de monter en compétence sur ce super-framework

Si ça vous motive, ca me suffit pour vous dire go ;)

**Comment by alice-telescoop** [comment]
Penser à check que le svg marche encore
