### ISSUE TITLE
Bug de téléchargement des pièces administrative

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1449]

**Comment by mxmeunier** [comment]
@mxmeunier @alice-telescoop @VSerain coucou

**Comment by VSerain** [comment]
Sur la prod, je ne vois pas de requête partir quand on clique sur documents, peut etre un soucis cotée front

**Comment by alice-telescoop** [comment]
côté front : `Uncaught (in promise) TypeError: this.getterByType[this.resourceType] is not a function`

**Comment by mxmeunier** [comment]
duplicate #1438
