### ISSUE TITLE
Créer une collection pour lister les types d'agent

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1464]
Stocker les types d'agents possible (_id, name)

Est-ce qu'on rajoute un champs agentId qui serait plus simple que le _id ? Genre 1, 2, 3, 4 ?

**Comment by mxmeunier** [comment]
https://docs.google.com/spreadsheets/d/1zAjTLwur9jw0VMlMYi77rLgw4F1PbCtII3Z86fFYBGo/edit#gid=922071148

Colonne B

**Comment by mxmeunier** [comment]
Il n'y a qu'administration déconcentrée qui nécessite un traitement supplémentaire pour définir la structure.

On passe de la colonne A à C dans la plupart des cas sauf pour Administration déconcentré qui doit savoir au préalable si c'est départemental ou régional ou interégional pour définir les structures à afficher dans la liste déroulante

**Comment by alice-telescoop** [comment]
will be done in https://github.com/betagouv/api-subventions-asso/issues/1525
