### ISSUE TITLE
Accéder à une liste des départements / régions

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1467]
~~Voir si il faut mieux uttiliser le csv ou plutot une api~~

~~https://docs.google.com/spreadsheets/d/1uU4A181UcHBajyxx9G_kDs70zoE6ItlROGaLet9ibg0/edit#gid=1650247646~~

**Edit du 18/08**

le document n'est pas pratique. Utiliser plutôt l'api https://geo.api.gouv.fr/decoupage-administratif

On a seulement besoin des régions et départements dans un premier temps

**Comment by VSerain** [comment]
Voir si on peut pas uttiliser une API #1529

**Comment by AlixBouillon** [comment]
Les données venaient de cette page : https://www.data.gouv.fr/fr/datasets/communes-de-france-base-des-codes-postaux/ :)

**Comment by mxmeunier** [comment]
Que faire de ce ticket ? @VSerain @alice-telescoop ? On en fait une implémentation API avec deux routes `/data/departements` et `/data/regions` ?

**Comment by VSerain** [comment]
On peut pas call l'api direcement depuis le front ?

**Comment by mxmeunier** [comment]
Aussi mais est-ce que c'est ce qu'on veut ?

**Comment by alice-telescoop** [comment]
Je suis pour appeler directement depuis le front. L'API ne demande pas d'authentification, qui serait une raison de passer par notre api
