### ISSUE TITLE
Rajoute une commande pour instancier les comptes déjà créer dans brevo

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1485]
@VSerain suite de la [#1367](https://github.com/betagouv/api-subventions-asso/pull/1472) avec comme commentaire "**@VSerain** Rajoute une commande pour instancier les comptes déjà créer dans brevo"

Lister tous les users,  et envoyer une notif à brevo pour créer tous les comptes dans la liste

**Comment by mxmeunier** [comment]
@VSerain suite de la [#1367](https://github.com/betagouv/api-subventions-asso/pull/1472)avec comme commentaire "**@victor** Rajoute une commande pour instancier les comptes déjà créer dans brevo"

**Comment by victor** [comment]
Je suis désolé, mais je refuse

**Comment by mxmeunier** [comment]
> Je suis désolé, mais je refuse

oops :)
