### ISSUE TITLE
[Étape 3] Version admin déconcentrée

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1529]
stuck by
- [x] #1523
- [x] #1524 
- [x] #1525 
- [x] #1467 

Rajouter le choix dans le formulaire type d'agents (#1523)

Faire un enum pour les types de territoire

Récupérer via un call à l'api les administrations (#1525).
La valeur et le label serait la colonne B.
Faire un filtre pour n'afficher que les bonnes suivant le types de territoires sélectionnés

Une fois la valeur sélectionnée pour la localisation du territoire, filtrer les possibilités pour l'administration.
La valeur serait l'id et le label serait la colonne C.

À la fin on veut avoir juste l'id du service qui nous permet de retrouver la compétence territoriale et la structure

**Comment by alice-telescoop** [comment]
Alix a fait [ce tableur](https://docs.google.com/spreadsheets/d/1uU4A181UcHBajyxx9G_kDs70zoE6ItlROGaLet9ibg0/edit#gid=1650247646) pour les territoires, je pense que ça vaut le coup de voir avec elle si ya des pièges ou pas par rapport à si on utilise une api

**Comment by VSerain** [comment]
Voir le ticket #1467

**Comment by alice-telescoop** [comment]
Les valeurs possibles pour le premier champs sont bien 

![Image](https://github.com/betagouv/api-subventions-asso/assets/94919029/a735b99e-eaba-4f1e-9995-6ac6278c83f0)

Ensuite dans le cas départemental ou régional -> utiliser l'api https://geo.api.gouv.fr/decoupage-administratif 
dans les 3 autres champs : champs libre
