### ISSUE TITLE
Regarder mail PESV2 pour victor

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1531]
Voir mail partager par Alix sur la document Helios

**Comment by alice-telescoop** [comment]
> Piste PES V2 :
> - Le numero de siret ou siren s'emble etre transmit dans la plupart des documents de type tiers. Mais ça peut également etre des finess, NIR, TVAIntraCo, Hors UE,TAHITI, RIDET , FRWF, EnCoursImm, IREP ou NFP. Regarder le dossier https://www.collectivites-locales.gouv.fr/files/finances-locales/Schemas_PES_v5.21.7z
> - Y a une genre de doc mais pas vraiement qui ce trouve ici: https://www.collectivites-locales.gouv.fr/files/finances-locales/DosTech_v5.21.7z décompresser + un petit python3 -m http.server dans le dossier pour pouvoir naviguer trkilou
> - J'ai l'impression que c'est assez uni directionelle dans le sense ou on peut déposer des fichiers, mais on ne peut pas interroger la base (en tout cas sur la partie que j'ai fouillée)

**Comment by VSerain** [comment]
Après lecture:

Les collectivités doivent effectivement passer un IdTiers qui peut etre un Siret ou un Siren ou autres choses.

L'outil ne semble pas permettre de le questionner via un Siret association, si j'ai bien compris, on ne peut le questionner que par commune. Je ne suis pas sûr qu'on puisse questionne par commun tous les versements, de ce que je comprends, il faut qu'on ai l'identifiant du "versement"  pour demander de l'information

Pour ce qui est de la possibilité dès l'extraire pour l'adapter à data subvention : Les données paraient être présentes (si elles sont bien complétées par les collectivités).
En revanche, rien est prévu pour y accéder via le pesV2. 
Difficile de déterminer quelles sont les étapes pour y arriver et encore moins si l'on a les capacités techniques pour y arriver.
Si prochaine étape il doit y avoir, c'est mieux comprendre l'outil hélios sur la partie central (!=collectivité), voir si on peut avoir des access à certainne choses (mais je ne sais pas quoi :D)

**Comment by VSerain** [comment]
Je close car doublon avec le trello, j'ai remis tous les information
