### ISSUE TITLE
Comprendre pourquoi le bodac est charger au debut et pourquoi on peut ne pas avoir de jugement

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1533]
voir : http://localhost:1235/association/309835379

**Comment by alice-telescoop** [comment]
Pour la première partie : le bodacc est envoyé par l'api dans le cadre de l'appel à `associations/:id`

**Comment by alice-telescoop** [comment]
Pour la 2e partie : on renvoie presque tel quel le résultat de l'api source donc c'est que le format qu'ils nous envoie est cassé. On a donc intérêt à être les plus prudents possible  et on ne peut pas vraiment en faire +
