### ISSUE TITLE
Rediriger vers le blog après suppression de son compte

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1539]

**Comment by mxmeunier** [comment]
@natoine est-ce toujours ce qu'on veut ? aujourd'hui redirection vers la page de login

**Comment by natoine** [comment]
tu peux demander sur mattermost aux bizdev ? Je pense qu'on peut se contenter de la situation actuelle mais s'il y a un enjeu pour eux faut leur demander.

**Comment by mxmeunier** [comment]
Pas important
