### ISSUE TITLE
Sujet mongo in metabase

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1547]
Metabase demande une version plus récente de mongo

Piste possible : Faire un duplicate journalier du mongo dans une autre version (heberger de OVH) et y connecter metabase

**Comment by alice-telescoop** [comment]
@VSerain tu l'as fait non ? #1349 Je pense que tu as même fait ce ticket-ci plutôt que celui que tu as associé à la PR ^^

**Comment by VSerain** [comment]
Yes, j'ai du m'embrouiller dans les tickets

Le mar. 12 sept. 2023 à 10:35, alice-telescoop ***@***.***> a
écrit :
