### ISSUE TITLE
Mettre à jour la version du DSFR

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1565]
passer de 1.8 à 1.11
### release notes
[v1.9](https://github.com/GouvernementFR/dsfr/releases/tag/v1.9.0)
[v1.10](https://github.com/GouvernementFR/dsfr/releases/tag/v1.10.0)
[v1.11](https://github.com/GouvernementFR/dsfr/releases/tag/v1.11.0)

**Comment by alice-telescoop** [comment]
si #1568 n'est pas fait, penser à mettre à jour le fichier dsfr nomodule dans les `static`

**Comment by VSerain** [comment]
https://sentry.incubateur.net/organizations/betagouv/issues/75884/activity/?project=101&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d
