### ISSUE TITLE
Mettre la doc opendata dans le wiki github

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1571]
mettre un lien vers le wiki sur le swagger

EDIT: et mettre un lien sur le blog

**Comment by VSerain** [comment]
Voir avec @AlixBouillon pour mettre sur blog

**Comment by VSerain** [comment]
@mxmeunier pourquoi donc est-ce en review ? Je ne vois pas le doc dans le wiki

**Comment by mxmeunier** [comment]
Bah si, elle est dans le wiki GitHub dans la section "Données ouvertes".

J'ai copié collé le contenu du fichier créé sur le drive

**Comment by alice-telescoop** [comment]
https://github.com/betagouv/api-subventions-asso/wiki/Donn%C3%A9es-ouvertes
