### ISSUE TITLE
Changer les liens envoyés par l'api pour l'inscription terminer l'inscription

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1592]

**Comment by alice-telescoop** [comment]
Ben il faut pas changer les liens tant qu'on n'a pas fini le formulaire. C'est tout :)

**Comment by mxmeunier** [comment]
Mais la partie mot de passe est déjà utilisable en soit, non ? Donc on peut "utiliser" le nouveau formulaire

**Comment by alice-telescoop** [comment]
Ben je sais pas, il faut pas que ça les amène sur des étapes pas finies

**Comment by mxmeunier** [comment]
bah la redirection sera forcément faite sur l'étape "1" donc à partir du moment ou l'étape mot de passe est mergée le bouton submit fonctionne et c'est tout bon. Après on ajoutera étape 2 et 3 et ça changera rien au lien, ou alors quelque chose m'échappe !

**Comment by mxmeunier** [comment]
c'est un autre problème ça, au pire on commentera l'ajout de la dernière step dans le ActiveAccount et/ou on ne mergera sur main qu'une fois toute l'étape 3 terminée

**Comment by alice-telescoop** [comment]
done in #1536
