### ISSUE TITLE
Le lien d'accessibilité est introuvable

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1602]
La page est introuvable

-> corriger le lien
-> cache le lien si la page n'existe pas

**Comment by mxmeunier** [comment]
@natoine est-ce qu'on crée des tickets pour créer cette page qui n'était que la page de base du DSFR ?

**Comment by alice-telescoop** [comment]
cf #1410

**Comment by mxmeunier** [comment]
Doublon
