### ISSUE TITLE
réparer la deconnexion dans le header en version mobile

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1660]

**Comment by mxmeunier** [comment]
@alice-telescoop tu peux mettre un peu plus d'info sur ce bug ?

**Comment by alice-telescoop** [comment]
Quand je suis en version mobile et que je clique sur "déconnexion" dans le header, rien ne se passe

**Comment by alice-telescoop** [comment]
duplicates #1505
