### ISSUE TITLE
Scinder le `userService` en sous services spécifiques

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1703]

**Comment by alice-telescoop** [comment]
Proposition de répartition : 

##### auth
getHashPassword
authenticate
login
logout
updatePassword
findJwtByEmail
findJwtByUser
buildJWTToken

##### consumer
findConsumerToken
createConsumer

##### crud
findByEmail
find
update
delete
getUserById
listUsers
createUser
signup

##### check
validateSanitizeUser
passwordValidator
validateEmail

##### roles
addRolesToUser
validRoles
isRoleValid
getRoles

##### activation
refreshExpirationToken
isExpiredReset
validateResetToken
validateTokenAndGetType
resetPassword
forgetPassword
findUserResetByUserId
resetUser
activeUser

##### stats
countTotalUsersOnDate
findByPeriod
getUsersWithStats
notifyAllUsersInSubTools

##### subscription form
activate
sanitizeActivationUserInfo
validateUserActivationInfo

##### rgpd
getAllData
disable
