### ISSUE TITLE
Investiguer lien matomo metabase

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1750]

**Comment by VSerain** [comment]
J'avais regarder vite fait, j'ai cru voirs qu'il y avait des repo github sur ce sujet, mais pas approfondit

**Comment by alice-telescoop** [comment]
https://github.com/OpenSourcePolitics/matomo_pull je suppose mais
1. ça demande de connaître la clé api de matomo -> je crois pas qu'on ait l'accès (mais on peut le demander)
2. ça demande une db en +

Aussi j'ai trouvé[^1]
> We’ll assume you have at least a basic [installation of Metabase](https://serversoul.com/install-metabase-on-ubuntu/) running. Then open the admin panel and click on Databases > Add Database.
> 
> Here you need to fill out all the connection details to your Matomo database server. My demo setup is hosted on DigitalOcean so your details may vary according to your hosting provider. 

Ça demande d'avoir un accès à la base de données utilisée par matomo, mais ça me paraît + simple à l'usage

[^1]: https://serversoul.com/matomo-metabase-visualization/

**Comment by alice-telescoop** [comment]
Et j'ai demandé l'aide des gens du FAST [sur cette discussion mattermost](https://mattermost.incubateur.net/betagouv/pl/rm1huprxw7r6zmx6s8od69xbhw)

**Comment by alice-telescoop** [comment]
On peut appliquer ça https://github.com/SocialGouv/matomo-postgres/ mais il faut une db postgre
Et je cite "mais rien ne t'oblige a lier les deux"

**Comment by mxmeunier** [comment]
@natoine est-ce que ça vaut le coup vu le coût ?

**Comment by natoine** [comment]
ben ça dépend du besoin. A la base c'est pour avoir toutes les métriques en un seul endroit pour faire un tableau de bord. Et pour préparer l'automatisation d'envoi de mail pour relancer nos utilisateurs. Si c'est compliqué et qu'on peut faire autrement c'est pas la peine.

**Comment by VSerain** [comment]
On attend le retour de Gauthier ! (Renvoyer un message debut décembre)

**Comment by mxmeunier** [comment]
Message envoyé

**Comment by VSerain** [comment]
On va migrer matomo dans un hébergement "privée" donc on aura accès à la db #1954

**Comment by VSerain** [comment]
NON MAIS C'EST FAIT CA
