### ISSUE TITLE
Ajouter un tracker matomo quand un utilisateur est redirigé vers une page asso à la suite de son inscription

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1767]
stuck by #1925

**Comment by alice-telescoop** [comment]
Je comprends pas ce ticket j'ai l'impression que cette redirection n'arrive jamais @VSerain

**Comment by mxmeunier** [comment]
@natoine est-ce qu'on veut cette feature ?

**Comment by VSerain** [comment]
Ok on veut faire cette feature et la traquer

**Comment by alice-telescoop** [comment]
in #1925
