### ISSUE TITLE
Répertorier les datasets data.gouv aux bons formats et les erreurs

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1771]
https://docs.google.com/spreadsheets/d/12MuErIiavcmSXdR1oYJEeTYcaxaCFHuanzqylCV5arY/edit#gid=0

**Comment by alice-telescoop** [comment]
| nom                                                                                                                                                                                                                                                        	| vu 	|
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|----	|
| [Subventions (organisation Premier ministre)](https://www.data.gouv.fr/api/1/datasets/subventions-organisation-premier-ministre-1/)                                                                                                                        	| ✅  	|
| [Subventions de la saison 1 de l'Accélérateur d'Initiatives Citoyennes](https://www.data.gouv.fr/api/1/datasets/subventions-de-la-saison-1-de-laccelerateur-dinitiatives-citoyennes/)                                                                      	| ✅  	|
| [Subventions versées par la DILCRAH en 2019](https://www.data.gouv.fr/api/1/datasets/subventions-versees-par-la-dilcrah-en-2019/)                                                                                                                          	| ✅  	|
| [Subventions versées par la DILCRAH en 2018](https://www.data.gouv.fr/api/1/datasets/subventions-versees-par-la-dilcrah-en-2018/)                                                                                                                          	| ✅  	|
| [Subventions versées par la DILCRAH en 2021](https://www.data.gouv.fr/api/1/datasets/subventions-versees-par-la-dilcrah-en-2021/)                                                                                                                          	| ✅  	|
| [Subventions versées par la DILCRAH en 2020](https://www.data.gouv.fr/api/1/datasets/subventions-versees-par-la-dilcrah-en-2020/)                                                                                                                          	| ✅  	|
| [Subventions versées par le Conseil Départemental des Côtes d'Armor aux associations depuis 2016 (Décret)](https://www.data.gouv.fr/api/1/datasets/subventions-versees-par-le-conseil-departemental-des-cotes-darmor-aux-associations-depuis-2016-decret/) 	| ✅  	|
| [Données essentielles des conventions de subvention - Bayonne](https://www.data.gouv.fr/api/1/datasets/donnees-essentielles-des-conventions-de-subvention-bayonne/)                                                                                        	| ✅  	|
| [Conventions de subventions attribuées par la Région Centre-Val de Loire 2019](https://www.data.gouv.fr/api/1/datasets/conventions-de-subventions-attribuees-par-la-region-centre-val-de-loire-2019/)                                                      	| ✅  	|
| [Données essentielles de conventions de subvention attribuées par la Ville d'Antibes](https://www.data.gouv.fr/api/1/datasets/donnees-essentielles-de-conventions-de-subvention-attribuees-par-la-ville-dantibes/)                                         	| ✅  	|
| [Jeu de données Subventions](https://www.data.gouv.fr/api/1/datasets/jeu-de-donnees-subventions/)                                                                                                                                                          	| ✅  	|
| [Conventions de subventions attribuées par la Région Centre-Val de Loire 2018](https://www.data.gouv.fr/api/1/datasets/conventions-de-subventions-attribuees-par-la-region-centre-val-de-loire-2018/)                                                      	| ✅  	|
| [Subventions - Conventions signées avec des organismes privés](https://www.data.gouv.fr/api/1/datasets/subventions-conventions-signees-avec-des-organismes-prives/)                                                                                        	| ✅  	|
| [Subventions liées au confinement Covid-19 Pays de Mormal 2020](https://www.data.gouv.fr/api/1/datasets/subventions-liees-au-confinement-covid-19-pays-de-mormal-2020-1/)                                                                                  	|    	|
| [Subventions Associatives de la commune de Lys-Saint-Georges de 2017 à 2022.](https://www.data.gouv.fr/api/1/datasets/subventions-associatives-de-la-commune-de-lys-saint-georges-de-2017-a-2022/)                                                         	|    	|
| [Subventions aux associations de la Ville de Baugé-en-Anjou de 2018 à 2020](https://www.data.gouv.fr/api/1/datasets/subventions-aux-associations-de-la-ville-de-bauge-en-anjou-de-2018-a-2020/)                                                            	|    	|
| [Subventions attribuées par l'Agglomération Montargoise depuis 2017](https://www.data.gouv.fr/api/1/datasets/subventions-attribuees-par-lagglomeration-montargoise-depuis-2017/)                                                                           	|    	|
| [Conventions de subvention - 2017](https://www.data.gouv.fr/api/1/datasets/conventions-de-subvention-2017/)                                                                                                                                                	|    	|
| [Subventions attribuées](https://www.data.gouv.fr/api/1/datasets/subventions-attribuees/)                                                                                                                                                                  	|    	|
| [Subventions attribuées aux associations par la ville de La Possession](https://www.data.gouv.fr/api/1/datasets/subventions-attribuees-aux-associations-par-la-ville-de-la-possession/)                                                                    	|    	|
| [Subventions 2017 du Département de la Dordogne](https://www.data.gouv.fr/api/1/datasets/subventions-2017-du-departement-de-la-dordogne/)                                                                                                                  	|    	|
| [Subventions 2018 du Département de la Dordogne](https://www.data.gouv.fr/api/1/datasets/subventions-2018-du-departement-de-la-dordogne/)                                                                                                                  	|    	|
| [Subventions 2019 du Département de la Dordogne](https://www.data.gouv.fr/api/1/datasets/subventions-2019-du-departement-de-la-dordogne/)                                                                                                                  	|    	|
| [Subventions 2022](https://www.data.gouv.fr/api/1/datasets/subventions-2022/)                                                                                                                                                                              	|    	|
| [Contributions et subventions 2020](https://www.data.gouv.fr/api/1/datasets/contributions-et-subventions-2020-1/)                                                                                                                                          	|    	|
| [Données essentielles conventions subventions 2018 du Département de la Loire](https://www.data.gouv.fr/api/1/datasets/donnees-essentielles-conventions-subventions-2018-du-departement-de-la-loire/)                                                      	|    	|
