### ISSUE TITLE
Créer une fake collection metabase pour savoir combien de nouveaux users ont tapé une recherche

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1776]
Possibilité de calculer :
Sur une période donnée, combien de nouveaux utilisateurs on tapés plus de 3 caractères dans la barre de recherche

Via metabase on peut faire le liens entre la table Users et la table Logs en ce basant sur la date de Log

Voir avec @alix

**Comment by alice-telescoop** [comment]
https://metabase-datasubvention-prod.osc-secnum-fr1.scalingo.io/question/38-nombre-dutilisateurs-inscrits-sur-une-periode-qui-ont-fait-une-recherche
