### ISSUE TITLE
Créer une fake collection pour remonter des stats sur la recherche

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1777]
on a les logs de toutes les recherches au delà de 3 caractères. 
Ce qu’on voudrait en traitant ces logs :
% RNA, SIRET, Nom d’asso
~~recherche le plus fait~~ -> #1930

**Comment by alice-telescoop** [comment]
J'ai dû faire une requête custom 
part des recherches par type : https://metabase-datasubvention-prod.osc-secnum-fr1.scalingo.io/question/41-part-des-recherches-par-type
@natoine ça te servira pour du pilotage je suppose

**Comment by alice-telescoop** [comment]
cf daily : On sort cette partie du ticket pour en re-discuter
