### ISSUE TITLE
Exclure de DAUPHIN les demandes FONJEP

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1828]
Sera fait avec #2252

**Comment by VSerain** [comment]
@VSerain il faut que tu nous donne le bon path vers l'attribue et ça valeur pour fonjep

**Comment by mxmeunier** [comment]
@VSerain tu dors ?

**Comment by VSerain** [comment]
Non mais pas eu le temps

**Comment by mxmeunier** [comment]
Au boulot !
