### ISSUE TITLE
Mettre à jour la validation des versements chorus au moment de l'import

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1839]
Bien tester la robustesse du validateur d'entité `ChorusLine` (suite au bug décelé sur le siret valant `#`)

- [ ] Gérer les doublons.
    Deux possibilités :
     - récupérer la date d'opération de versement la plus récente en base et filtrer les nouvelles entités sur cette date
     - catch les erreurs mongo d'unicité sans compromettre l'import
 - [ ] validation du siret : autoriser le "#" ?

**Comment by alice-telescoop** [comment]
reste à faire
- créer le readme
- gérer les doublons au moment de l'import

**Comment by mxmeunier** [comment]
Reste à faire : remplacer le filtre par date d'opération par un `try...catch` sur les erreurs de doublons
