### ISSUE TITLE
Séparer les documents en deux parties

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1877]
Deux parties :
- RNA/SIREN
- Documents complémentaires (ApiAsso, Dauphin)

**Comment by mxmeunier** [comment]
https://www.figma.com/file/t6nWdBwKr8fancez3VO5kr/Data.Subvention---Développeurs?type=design&node-id=10710-154458&mode=design&t=BWCUoRvkqGqBBzea-0

**Comment by alice-telescoop** [comment]
Oui mais j'ai un doute. À confirmer avec Marion et/ou bizdevs que c'est bien le même résultat

**Comment by VSerain** [comment]
Remontée également des documment des l'association quand on est sur une page établisement
