### ISSUE TITLE
Désactiver les differents onglet quand on est pas une asso

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1886]
Stuck par le point @VSerain Yasmine sur le sujet code APE four tout

**Comment by mxmeunier** [comment]
peut-être fait dans #1798

**Comment by alice-telescoop** [comment]
Mais en fait la validation côté front c'est moins gênant parce que si on a un rna c'est déjà ok. 
Autrement dit toujours nécessaire de traiter #1406 et d'avoir de bonnes règles mais ça bloque peut-être pas tout à fait ce ticket-ci
