### ISSUE TITLE
Mettre à jour l'API pour retourner l'adresse de l'association sur la recherche par nom

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1917]
stuck by #1937 

créer un joiner entre `unite-legal-names` et `insee-etab` pour renvoyer une entité `InseeSearchResult` au format 
```ts
type SimplifiedAsso = {
    rna?: Rna
    siren?: Siren
    nbEtabs?: number
    address?: Adresse
    name?: string
}
````
au lieu de `AssociationNameDto`

**Comment by alice-telescoop** [comment]
- le parser 
    - avait-on déjà du code là-dessus ?
- stocker l'information
    - nouvelle table `associations` ?

réalisation stuck par #1911 pour le stockage de la donnée

**Comment by alice-telescoop** [comment]
L'adresse n'est **pas** présence dans UniteLegal

**Comment by alice-telescoop** [comment]
done in #971 ?
