### ISSUE TITLE
Retirer  `unzip` et `unzipper`

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1933]
`unzip` dépend d'un version vulnérable de `fstream` (vulnérabilité haute d'après npm) et n'est plus maintenu (cf https://github.com/EvanOxfeld/node-unzip/issues/125 )
https://github.com/ZJONSSON/node-unzipper semble faire le taff 

[^1]: https://github.com/EvanOxfeld/node-unzip/issues/125

**Comment by mxmeunier** [comment]
Retirer `unzip` `node-unzipper` non utilisé
