### ISSUE TITLE
Investiger pour voir si on peut créer plusieurs compte avec un seul email

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#1940]
https://mattermost.incubateur.net/betagouv/pl/wxt7dj4enifs7xei5mf94qoqjo

**Comment by mxmeunier** [comment]
-> rajouter l'unicité sur l'email dans le `user.repository`

**Comment by alice-telescoop** [comment]
Pour le cas trouvé : il a fait ses 5 requêtes en 74ms

**Comment by alice-telescoop** [comment]
La résolution de ça se combine très bien avec #1867 je vois si je l'inclue à ma PR
