### ISSUE TITLE
Utiliser l'api comme un proxy pour dl les fichiers

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1955]
Il faudrait se servir de l'api comme proxy pour DL les fichiers rna

**Comment by VSerain** [comment]
Uttilier pour l'api asso et pour avis de situation siren

**Comment by VSerain** [comment]
Voir si on peut pas envoyer une reuqette de type OPTION en amont pour check si un fichier de l'api asso est bien downloadable

**Comment by alice-telescoop** [comment]
En premier jet : comportement différent pour dauphin et les autres parce que pour dauphin on a toujours le même domaine. Est-ce sûr pour tous les providers ? Si oui ça permet de raccourcir les urls

**Comment by alice-telescoop** [comment]
Quel comportement si doc pas dispo : on affiche la carte en "désactivé" ? On n'affiche pas du tout la carte ? On redirige vers une jolie page d'erreur quand la personne clique ?
Dans les deux premiers cas ça se gère au moment de trouver les docs, dans le dernier ça se gère au moment du proxy

**Comment by alice-telescoop** [comment]
Ça rend quand même très visible les token des utilisateurs. Devrait-on imaginer un token à part juste pour les documents ?

**Comment by alice-telescoop** [comment]
Est-ce que l'API renvoie direct l'url encodée (comme pour dauphin) ou est-ce que l'api renvoie l'url complète (comme d'hab' pour api-asso et avis situation, mais un changement pour dauphin) et ensuite le front calcule l'url à appeler pour utiliser le proxy ?
