### ISSUE TITLE
Créer un template du format d'entrée idéal

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1956]
P-ê faire un format qui puisse être validé par [cet outil](https://validata.fr/)

**Comment by mxmeunier** [comment]
Pour le dépôt de données d'une demande de subvention depuis Data.Subvention ?

**Comment by VSerain** [comment]
Oui dans l'idée

**Comment by alice-telescoop** [comment]
P-ê faire un format qui puisse être validé par [cet outil](https://validata.fr/)

**Comment by mxmeunier** [comment]
On en fait quoi de ce ticket ?

**Comment by alice-telescoop** [comment]
Si on considère que le taff de Victor résout le truc on ferme, et sinon faut en discuter. Je trouve que le ticket parle de trop de trucs à la fois donc je suis pour clarifier. On en discute un minimum en daily demain ?

**Comment by mxmeunier** [comment]
> Si on considère que le taff de Victor résout le truc on ferme, et sinon faut en discuter. Je trouve que le ticket parle de trop de trucs à la fois donc je suis pour clarifier. On en discute un minimum en daily demain ?

ok si on oubli pas :)

**Comment by alice-telescoop** [comment]
Apparemment Soumaya en a besoin https://mattermost.incubateur.net/betagouv/pl/1jamjrfey78cfg4814i6ng3osa
