### ISSUE TITLE
DL et intégrer les donnée osiris

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1961]

**Comment by VSerain** [comment]
manque la mise en prod

**Comment by alice-telescoop** [comment]
@mxmeunier c'est fini du coup, ça ?

**Comment by mxmeunier** [comment]
> @mxmeunier c'est fini du coup, ça ?

Non j'ai eu un souci d'archive vide une fois décompressée sur scalingo. A priori un problème de compression macOS différent de Linux :/

**Comment by alice-telescoop** [comment]
Et tu veux t'y remettre ou on le remets en TODO ? La quantité de choses en "in progress" me perturbe

**Comment by mxmeunier** [comment]
> Et tu veux t'y remettre ou on le remets en TODO ? La quantité de choses en "in progress" me perturbe

c'est débloqué grâce à Victor donc je suis dessus en parallèle #1993
