### ISSUE TITLE
remplacer `standard-version` (déprécié) - alternative qui génère un changelog à partir de PR ?

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1971]
Utiliser pour les tags de version !

**Comment by alice-telescoop** [comment]
- https://github.com/absolute-version/commit-and-tag-version un fork de ce qu'on utilise en version "à jour" mais ça fait tjs un changelog par commit (et pas par PR/feature)

**Comment by VSerain** [comment]
A rediscuter savoir si on peut squash

**Comment by VSerain** [comment]
Au cas ou  : https://github.com/wanadev/changelogify

**Comment by mxmeunier** [comment]
On se remet à squash & merge les PR et on met à jour `commit-and-tag-version`
