### ISSUE TITLE
Supprimer les users qui n'ont pas utilisé datasub depuis 2 ans

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#1977]
Un mail sera envoyé 1 mois avant via brevo (gérer par les biz dev)
Nous, on doit juste faire le delete en base et envoyer une notif au biz dev pour leurs dire que le compte est supprimé automatiquement (Notif différente qu'un utilisateur a supprimé son propre compte)

**Comment by VSerain** [comment]
@alice-telescoop @MorelAlexandra voir avec louis si on agèrege les notifications

**Comment by alice-telescoop** [comment]
Boucle de mail (enfin) activée par Louis à date
