### ISSUE TITLE
Renvoyer un cookie utilisateur

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#1983]
> Pour l'instant, si un utilisateur partage le lien qu'il a d'un document dauphin, la personne qui reçoit ce lien peut se faire passer pour lui en réutilisant le token dans d'autres requêtes
> 
> -------
> 
> Proposition : à l'appel à `/structure/documents`, créer une sorte de token, personnalisé ou non, qui expire après un délai qu'on déciderait, et qui serait rajouté côté api ou envoyé au front. Ce token ne permettrait que l'accès aux documents et à rien d'autre. 
> Ainsi, le front n'aurait pas besoin de transmettre le token générique dans l'url et on évite le souci

Du coup on part sur l'utilisation de cookie utilisateur et il faut faire en sorte que la route auth de l'API renvoi un cookie contenant le token d'authentification (garder le renvoi du token dans le body)

**Comment by VSerain** [comment]
Ou des cookies ? 🍪

**Comment by alice-telescoop** [comment]
#548

**Comment by mxmeunier** [comment]
prequel de #1286

**Comment by VSerain** [comment]
Duplicate de #2010
