### ISSUE TITLE
Intégrer les données pipedrive dans notre base

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2000]
https://trello.com/c/aMkn9y4h/81-mise-%C3%A0-jour-pipedrive-pour-import-sur-metabase
https://trello.com/c/EEJWRdCK/136-etq-dev-je-veux-importer-les-donn%C3%A9es-issues-de-pipedrive-dans-notre-bdd-et-elles-seront-propag%C3%A9es-auto-dans-brevo-metabase-au-su

**Comment by alice-telescoop** [comment]
Faire faire le moins de traitement par les bizdevs et avec des astuces
Entre dans un seul excel ? si oui : 
- définir format intermédiaire
- écrire cli/script tools qui importe dans une nouvelle collection ovh
    - selon si on met à jour les utilisateurs de la db
    - voir si on garde les utilisateurs présents dans les deux
- adapter `dumpService.upsertUsers` pour récupérer les utilisateurs de la nouvelle collection dans la collection ovh

Côté bizdevs : 
- utiliser l'autocomplete pour structure. Est-ce que c'est ok si c'est fait automatiquement ??

**Comment by alice-telescoop** [comment]
[base pipedrive nettoyée par Louis](https://trello.com/1/cards/6581b69222dbdcf57f00a584/attachments/6596e811eef72518d24b74c6/download/5_-_V1_importpipedrive.xlsx)

**Comment by mxmeunier** [comment]
transformer en ticket dev
