### ISSUE TITLE
utiliser le cookie d'authentification

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2010]
stuck by #1983

Remplacer l'utilisation du token depuis le localStorage par le nouveau cookie #1983

principalement `authService` et `documentService`

**Comment by alice-telescoop** [comment]
J'ai envie qu'on prenne ces tickets très vite au vu de la tension sur les documents en ce moment

**Comment by VSerain** [comment]
C'est fait ;)

**Comment by VSerain** [comment]
Oupis :)
