### ISSUE TITLE
BUG On n'affiche pas de données alors qu'il y en a bien

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2030]
J'arrive sur la page asso 485147805 et on m'indique que pour l'année (Pas d'années) il n'y a pas de données, mais j'en ai bien pour les autres années

Je veux dans le cas où il y a au moins une sub/versement arrivé sur son année et non sur une page vide

Victor pense que le soucis viens de la partie Async / Flux

**Comment by VSerain** [comment]
Il faut avoir les données scdl en local ;)

**Comment by mxmeunier** [comment]
je ne reproduis pas : 
j'ai 1 versement en 2023 et 1 demande en 2019 mais ça s'affiche bien directement
