### ISSUE TITLE
Changer la couleur de l'icône de tri dans le header du tableau de bord

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2053]

**Comment by mxmeunier** [comment]
https://trello.com/c/4NuNF7Bb/167-améliorer-laffichage-du-tableau-de-bord-actuel-la-petite-flèche-de-tri-nest-pas-visible

**Comment by alice-telescoop** [comment]
Même couleur que `active` et `hover` ?

**Comment by alice-telescoop** [comment]
On va le mettre en préprod mais la différence entre l'état normal et l'état hover est pas vraiment visible @Gttnmarion
[Capture vidéo du 2024-02-02 14-52-35.webm](https://github.com/betagouv/api-subventions-asso/assets/94919029/2d7b5169-faa3-4892-a422-767347394b1e)

**Comment by Gttnmarion** [comment]
> l'état

mmmm en effet c'est embêtant ! Et si on utilise un bleu écume ?
<img width="297" alt="Capture d’écran 2024-02-07 à 12 53 39" src="https://github.com/betagouv/api-subventions-asso/assets/114912799/a8a2b04e-618e-4085-b5ab-b1c993992259">

**Comment by alice-telescoop** [comment]
Si tu as un peu de temps soit pendant la daily demain soit après les tests préprod on pourra tester en live
