### ISSUE TITLE
renommer onglet et titre du tableau de bord

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2055]

**Comment by mxmeunier** [comment]
![Image](https://github.com/betagouv/api-subventions-asso/assets/7630775/a2702cf1-4c58-4ed4-8628-2c28f5d002f6)

**Comment by alice-telescoop** [comment]
fait dans #2075 mais apparemment la maquette n'était pas validé donc défait le temps d'éclaircir la question

**Comment by alice-telescoop** [comment]
Plus précisément en attente qu'Alix et Marion se mettent d'accord
