### ISSUE TITLE
Afficher un label sur les lignes du tableau concernant des subventions co-financées

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2059]

**Comment by mxmeunier** [comment]
![Image](https://github.com/betagouv/api-subventions-asso/assets/7630775/d589c5ec-b9e6-41b8-84ad-dece5020b5d6)

**Comment by VSerain** [comment]
Même question que pour #2060

**Comment by alice-telescoop** [comment]
en attente que gispro et osiris se stabilisent ensemble

**Comment by VSerain** [comment]
Je crois que c'est en 2025
