### ISSUE TITLE
Sauvegarder en base les imports de données réussis

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2077]
Le but est d'avoir une possibilité de savoir rapidement quel est la dernière date de mise à jour, si une commande est bien allé jusqu'au bout (coucou moi qui ferme mon écran sans vérifier mon script)

Stocker un document nouvelles données fournisseur + année(s)

1. date mise à jour dans la solution (intégration)
2. de quelle date datent les données (édition)

**Comment by mxmeunier** [comment]
Peut-être un doublon quelque part ?

**Comment by alice-telescoop** [comment]
- créer un nouveau service et repository (**pb : ** différence provider technique vs éditeur de donnée pour le scdl en particulier)

| provider | fileName | integrationDate | editionDate | success |
| -- | -- | -- | -- | -- |

- créer un document dans cette table à chaque fois qu'on commence à importer un fichier 
- met à jour ce document lorsque l'import a fonctionné (**question : ** est-ce qu'il y a besoin de sauvegarder aussi quand ça ne marche pas..?)
