### ISSUE TITLE
Envoyer un mail à l'activation du compte

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2088]
Quand un utilisateur active son compte pour la 1er fois on lui envoie un mail pour lui dire bien jouée ! (ne peut pas être fait dans Brevo car latence trop longue)

https://my.brevo.com/camp/template/135/message-setup

**Comment by alice-telescoop** [comment]
Le mail existe dans brevo

**Comment by mxmeunier** [comment]
@alice-telescoop on supprime ce ticket, c'est fait, non ?

**Comment by alice-telescoop** [comment]
oui, duplicates #2071
