### ISSUE TITLE
Les emails ne sont pas anonymisés lors du CRON RGPD

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2095]
`removeInactiveUsers`, que ce soit en préprod ou dans la run de Victor, n'a pas complèment anonymisés les utilisateurs concernés. Tous les changements ont été faits (`disable: true`, `active: false`, enlever le prénom et le nom) SAUF anonymiser le mail (ce qui est important !)

Et réactiver le CRON (pour le moment désactivé par sécurité)

**Comment by alice-telescoop** [comment]
Je reproduis pas en local. Soit il faudra remettre la feature en préprod pour essayer de reproduire soit j'aurai besoin de vos jus de cerveau @mxmeunier @VSerain

**Comment by mxmeunier** [comment]
alternative : mettre un log quelque part lors de la vraie suppression d'un utilisateur et vérifier à ce moment là ? En soit c'est pas la mort si l'anonymisation échoue on fera à la main le temps de trouver la faille

**Comment by alice-telescoop** [comment]
C'est arrivé 2 fois quand même. Mais ok à le passer au prochain sprint et à voir en conditions réelles, quitte à créer des faux utilisateurs en préprod pour déclencher la situation plus tôt. Mais je crois que les mails sont pas bien configurés côté brevo par ailleurs donc je pense pas utile de le rajouter dès maintenant

**Comment by alice-telescoop** [comment]
Un utilisateur doit être supprimé en préprod le 5 février au soir
