### ISSUE TITLE
Investigation de l'API PISTE

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#211]
## UPDATE 2: 
Les APIs à intégrer sont RIB et TIERS ([Voir ici](https://github.com/betagouv/api-subventions-asso/issues/211#issuecomment-1451491103)).

En attents de : 
- Leurs validations
- La creation d'un VPN entre nos services

## UPDATE: voir PPT chorus

Regarder les informations que l'on peut récupérer via l'api PISTE (Chorus chore)

https://developer.aife.economie.gouv.fr/

Pas besoin de dev sur ce ticket, on peut seulement créer une collection postman pour lister les routes qui nous semblent intéressants.

A RECHERCHER : IBAN et RIB (au format PDF)

NOTE DE MAXIME: à priori il faut un compte Chorus Pro pour utiliser les APIs.

Il y a l'API "référentiel des organisations" qui permettrait de récupérer les pièces jointes d'une structure. Mais "structure" reste à définir... est-ce pour établissement / association ? Peut-être un RIB/IBAN à récupérer là-bas... En tout cas je n'ai rien réussi à testé de l'extérieur via Postman.

**Comment by VSerain** [comment]
Stuck tant qu'ils ne nous auront pas répondu

**Comment by VSerain** [comment]
@VSerain vérifier s'ils nous ont donné les accès sans nous répondre !

**Comment by VSerain** [comment]
Toujours pas d'accès

**Comment by VSerain** [comment]
Toujours bloquée j'ai renvoyer un mail

**Comment by mxmeunier** [comment]
@VSerain il faut remettre à jour l'état d'avancement

**Comment by VSerain** [comment]
Suite à des échanges avec l'AIFE (Ceux qui gère piste et chorus), nous savons qu'il faut être sur le RIE (Réseau interministériel état) pour accéder à leurs apis. 
Comme nos serveurs sont hors de ce reseau, il a été proposé et valider d'installer un vnp entre notre serveur et leur reseau pour que nous puissions consommée leurs APIs

Après discutions, nous devrons intégrer les APIs Tiers et RIBs.

Mais pour le moment nous somme dans l'attente de l'envoie et la signature d'un courrier qui fixerait le partenariat.

Revoir avec @Vserain ou bien Yasmine ou l'ont en ai

**Comment by VSerain** [comment]
@VSerain Refaire le point avec Yasmine la dessus

**Comment by VSerain** [comment]
Dans tous les cas les requette nésésite d'avoir le nom + prenom + service + num de tel de l'agent

**Comment by mxmeunier** [comment]
BREAKING NEWS : ON FAIT CONFIANCE A JFM

**Comment by VSerain** [comment]
Normalement c'est valide, y a plus qua avoir les acces

**Comment by VSerain** [comment]
@VSerain revoir avec Yasmine et JFM

**Comment by alice-telescoop** [comment]
pas assez d'info ça traîne
