### ISSUE TITLE
Remonter la statistique de partage de page data subvention

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2202]
1. S'assurer qu'on a accès à l'historique hors domaine data sub

2. Tracker les personnes qui s'inscrivent après avoir été sur une autre page de data.subvention (donc un partage de lien)

à l'inscription, regarder l'historique pour voir si il y a eu redirection ou si la personne est arrivée directement sur la page de création de compte

**Comment by mxmeunier** [comment]
Demande de RDV avec les bizdevs

**Comment by mxmeunier** [comment]
Faire un compteur général de nombre d'inscrits à la suite d'un partage (donc du nombre d'inscription avec un historique avant login contenant `app.datasubvention.beta.gouv.fr`)

**Comment by alice-telescoop** [comment]
voir `document.referrer`

**Comment by alice-telescoop** [comment]
Ça permettra de comparer au partage de page par le bouton quand on l'aura

**Comment by mxmeunier** [comment]
@natoine https://matomo-datasubvention.osc-secnum-fr1.scalingo.io/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=1#?idSite=1&period=day&date=yesterday&category=General_Actions&subcategory=Actions_SubmenuPagesEntry

**Comment by natoine** [comment]
oui ça me va dans ce cas
