### ISSUE TITLE
hotfix: mettre à jour l'adapteur api asso (MEP de leur côté la semaine du 26/02)

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#2204]
> "reseaux_affiliation" => on n’a conservé que "reseau_affiliation"
> 
> "composition_reseau" => "membre" a été retiré
> 
> "adherents_personnes_morales" => on n’a conservé que "adherent_personne_morale"
> 
> "representants_legaux" => on n’a conservé que "representant_legal"
> 
> "rhs" => on n’a conservé que "rh"
> 
> "agrements" => on n’a conservé que "agrement"
> 
> "comptes" => on n’a conservé que "compte"
> 
> "etablissements" => on n’a conservé que "etablissement"
> 
> "ribs" => on n’a conservé que "rib"
> 

fiche des attributs envoyé par mail

**Comment by mxmeunier** [comment]
[API Association-champs-v1.8-1.xls](https://github.com/betagouv/api-subventions-asso/files/14342393/API.Association-champs-v1.8-1.xls)
