### ISSUE TITLE
Appel à rna-siren avec un identifiant undefined pour la gestion des doublons siren/rna

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2209]
Sur chaque page asso on cherche à savoir si y'a un doublon rna ou siren et par moment l'identifiant est undefined

https://sentry.incubateur.net/organizations/betagouv/issues/82624/?query=is%3Aunresolved&referrer=issue-stream

**Comment by mxmeunier** [comment]
https://api.datasubvention.beta.gouv.fr/association/483500773

**Comment by VSerain** [comment]
Déjà corriger
