### ISSUE TITLE
Aligner correctement le titre de l'onglet Subvention

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2213]
le titre a trop d'espacement vers le haut

**Comment by alice-telescoop** [comment]
J'ai l'impression qu'on est iso aux maquettes : 2rem de padding général au sein de l'onglet, et 2rem de l'élément titre. @Gttnmarion tu estimes qu'il y a toujours un pb ?

**Comment by alice-telescoop** [comment]
@Gttnmarion relance

**Comment by VSerain** [comment]
Vu avec Marion, on close plus de soucis
