### ISSUE TITLE
Investigation connexion Agent Connect

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2220]
Description du process + réflexion sur l'implémentation ?

https://pad.numerique.gouv.fr/E7FSGf2gRUOIKtkEUT6mnw?edit

**Comment by mxmeunier** [comment]
> [support.partenaires@agentconnect.gouv.fr](mailto:support.partenaires@agentconnect.gouv.fr) 
https://pad.numerique.gouv.fr/p/4finbsfnw#/

**Comment by alice-telescoop** [comment]
[documentation](https://github.com/france-connect/Documentation-AgentConnect/blob/main/doc_fs.md)

cf page 10 des [CGUs](https://raw.githubusercontent.com/france-connect/Documentation-AgentConnect/main/doc_fs/cgu_fca/20210528-DINUM-AC-CGU_FS-v1.2.pdf) on peut faire une demande avant pour avoir un token de test et développer mais on pourra pas mettre en prod tant qu'on n'a pas fait l'homologation de sécurité puis fait la demande de datapass (cf doc)([demande en brouillon](https://www.demarches-simplifiees.fr/dossiers/16955360/brouillon))

À faire pour implémenter en test : 

- [ ] comprendre comment brancher [les infos qu'on récupèrerait](https://github.com/france-connect/Documentation-AgentConnect/blob/main/doc_fs/technique_fca/technique_fca_scope.md) à notre formulaire (voir avec bizdevs ; Alix ou Louis je dirais)

Reste à faire en investigation : 

- [ ] comprendre quelles données enregistrer où et pour combien de temps quoi enregistrer ?
- [ ] définir les routes à implémenter 
- [ ] choix : changer algo de signature de token ? 
    par défaut de la librairie utilise HS256 qui est symétrique et synchrone, déconseillé au profit de RS256 et ES256 qui sont asymétrique. Il faut avoir choisi pour avoir un token même de test. Si on dit HS256 on est moins secure mais on peut avancer + vite. Ça n'a pas l'air difficile de changer ça fait juste se reconnecter tout le monde
- [ ] compléter la demande de token de test

**Comment by alice-telescoop** [comment]
### première connexion france connect

- création d'un compte avec les données :
    - `given_name` -> `firstName`
    - `usual_name` -> `lastName`
    - `email` **à valider d'office** (ajouter dans domaines validés ou exception..?)
    - `uid` à stocker dans un nouveau champ
- pas de mot de passe à priori

### connexions suivantes france connect

- chercher l'utilisateur par `uid`

**Comment by alice-telescoop** [comment]
## À créer côté api

- `auth/ac/login` une url de connexion qui redirige vers agent connect avec les bons secrets, `nonce` `state` (qui doit être stocké pour vérification uttérieure) etc (redirection 307)
    - `authService.generateAgentConnectUrl()`
- `auth/ac/callback` 
    - vérifie que `state` correspond
    - demande un token grâce au code d'autorisation passé en query par agent-connect.
    - demande les infos utilisateurs à partir du token récupéré 
    - vérifie si on a déjà un utilisateur avec cet `uid` en base
    - si non on le crée (et on l'active dans la foulée ? quel mail lui est envoyé ? mapping des champs utilisateurs ?
