### ISSUE TITLE
Ajouter la possibilité d'adapteur dans le mapper démarche.gouv

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2256]
Je sais pas si ce serait une bonne idée mais ce serait pour régler un souci remonté par Alix :

> Le montant accordé est marqué `undefined` dans la modale pour une demande de 2023 de l'asso au SIREN 775649676
> Et après enquête c'est parce qu'ils ont mis du texte dans la case : 
> 
> > 300 000€ (issus du projet Respir, subvention non consommée)
> 
> et donc on n'a pas pu le convertir en nombre. 
> 
> Notre process fait que ce n'est pas évident de forcer un typage même si là on a l'impression que l'information est facilement récupérable mais avoir cette souplesse de configuration champ par champ ajoute pas mal de complexité mine  de rien. 
> Côté DS c'était bien censé être un nombre donc je suis étonnée que la personne ait pu renseigner un texte

**Comment by mxmeunier** [comment]
ou alors fait juste un traitement côté front ?

**Comment by alice-telescoop** [comment]
Pour le sujet d'Alix elle m'a dit qu'elle remontait le pb à l'équipe avec qui elle est en lien pour montrer qu'on met à jour régulièrement les données et les encourager à remplir correctement tout ça. Donc pas de nécessité pour elle de combler techniquement le pb pour l'instant en tous cas
