### ISSUE TITLE
Intégrer les données subventia (CIPDR)

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2264]

**Comment by mxmeunier** [comment]
https://trello.com/c/7XeJNc3Q/220-intégrer-les-données-de-subventia

**Comment by gcarra** [comment]
> Arrivés à l'étape de créer le mapper entre les données reçu et le dto, nous nous sommes penchés sur la compréhension des fichers des données reçus.

> synthèse des hypothèses et questionnements https://docs.google.com/spreadsheets/d/14QlctaBexdPPvuHUXWXNJAAZj1T-FMj6/edit#gid=127912700

> Next step envisagé avec Alix : 1) prendre le retour d'Antoine 2) prévoir un échange visio avec Richard pour éclaircir et/ou valider tout ça

**Comment by gcarra** [comment]
Un point a été fait avec Richard, pas tous les points ont été éclairci, ils devraient revenir vers nous avec des info supplémentaires (voir CR). Avec les éléments que on a on peut commencer le parser mais la question de la qualité des données se posent : est-ce qu'on souhaite commencer à regarder la cohérence et la qualité de données "un peu plus poussée" (i.e. au de là des problèmes de typo) avant de le faire "sortir" ou pas forcement ? 
Exemple d'erreurs rencontrés : 
> Année de décision < année de demande
> Status de la subvention "INSTRUCTION" plus d'une année la date de la demande. Dans certaines cas, c'est surement une manque de mis à jour car on a le versement associé côté chorus.

**Comment by gcarra** [comment]
Il manque : 
> le test d'intégration
> l'export du csv données invalids
