### ISSUE TITLE
Permettre la sélection des documents à télécharger

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2308]
stuck by #2307 and #2309 

![Image](https://github.com/betagouv/api-subventions-asso/assets/7630775/2e90c7b3-a97e-4391-9a67-ab8d3a36b090)

**Comment by alice-telescoop** [comment]
Je fais 2309 d'abord parce que celui-ci est stuck mais j'ai du dev d'avance dessus
