### ISSUE TITLE
Intégrer les données 2023 GISPRO - DAUPHIN 

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2322]
deux collection : `dauphin-gispro` et `gispro-action-ghost`

affaire à suivre sur ce qui avait été démarré par victor à ce sujet

**Comment by mxmeunier** [comment]
https://trello.com/c/EqssCpVy

**Comment by VSerain** [comment]
Voir avec @yasmine si on peut leurs demander les donnée 2018 a 2022 au format de celle de 2023 (Quand on sera sur de bien pouvoir intéger les données)

**Comment by alice-telescoop** [comment]
Non : on n'aura pas + d'extract
