### ISSUE TITLE
Gérer les recherches par RNA valide mais liée à aucune association

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2343]
cas : https://app.datasubvention.beta.gouv.fr/search/W011000016

**Comment by mxmeunier** [comment]
https://sentry.incubateur.net/share/issue/299ea708aeac424394f90fc7e2067783/

**Comment by VSerain** [comment]
Duplicate de https://github.com/betagouv/api-subventions-asso/issues/2131
