### ISSUE TITLE
Afficher les libellés des BOP

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#2353]
renommer bop par programme ??

affiche code programme + label

**Comment by natoine** [comment]
oui renommer BOP par programme ;)

**Comment by alice-telescoop** [comment]
@VSerain maintenant on a le libellé du BOP/programme à renseigner dans la case à droite

**Comment by alice-telescoop** [comment]
Le côté api a été fait

**Comment by VSerain** [comment]
Ahah  oui effectivement ! Vous avez specifier un truc ou je fait comme je veux ?

**Comment by alice-telescoop** [comment]
> affiche code programme + label

On a spécifié ça. Quelle (autre ?) spécification voudrais-tu ?
