### ISSUE TITLE
[scdl] Gérer attribuants variés - données France Travail

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2384]
Nécessite du dev

stuck by #2387 
https://trello.com/c/Ya5QO39U

**Comment by VSerain** [comment]
It's possible to have many details ?

**Comment by alice-telescoop** [comment]
Le coup des headers c'est pas grave, par contre on affiche le nom du producteur comme nom d'attribuant dans notre code alors que là les attribuants sont pas tous les mêmes :/

**Comment by alice-telescoop** [comment]
NB : prendre le excel, le csv passe pas

**Comment by alice-telescoop** [comment]
Les attribuants ne sont pas tous les mêmes, alors que notre parseur suppose que si et qu'ils sont égaux au producteur. Vu avec Giulia et Victor on voudrait défaire ce comportement mais à réfléchir et + de dev que de l'intégration de données.
On a exclus l'idée de mettre un SIRET générique et "Pôle Emploi" ou "France Travail" générique partout
