### ISSUE TITLE
Exporter tous nos services instructeur et centre financier

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2386]
Faire un script / requêtes mongo qui ressort la liste des services instructeur et centre financier

Pour transmettre à annuaire service public

Centre financier => que chorus 
Faire une requête par fournisseur pour le services instructeur

**Comment by mxmeunier** [comment]
https://trello.com/c/he5KXMYz

**Comment by mxmeunier** [comment]
> C'est un one shot ?

oui

**Comment by gcarra** [comment]
Extractions faites : 

- [ ] centre financiers - chorus
- [ ] osiris - service instructeurs en utilisant providerInformations.service_instructeur dès la collection sur osiris-requests
- [ ] fonjep - service instructeurs en utilisant indexedInformations.service_instructeurs
