### ISSUE TITLE
Créer l'export CSV du tableau des subventions depuis l'API

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2413]

**Comment by mxmeunier** [comment]
En PJ ici le tableau de Gabrielle de Nadaillac avec les évolutions demandées

[DATASUB-CSV-EXTRACT-OPTIMUM.xlsx](https://github.com/betagouv/api-subventions-asso/files/11865315/DATASUB-CSV-EXTRACT-OPTIMUM.xlsx)

**Comment by alice-telescoop** [comment]
stuck by #2313
