### ISSUE TITLE
Définir une première version du schéma de données "tout versement"

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2414]
A mon avis, cela fait partir d'une EPIC qui sera toujours en évolution. 
- faire au plus simple
- considerer en premier temps que les donées chorus

**Comment by gcarra** [comment]
Une première version à revoir peut être trouvée ici : https://docs.google.com/spreadsheets/d/1VcSJiCE_O-DXFSJlqCAz1AS2RSvX2Rkz/edit?gid=1392962387#gid=1392962387 sous l'onglet "versement chorus".

La table de correspondance de nomenclature ici : https://docs.google.com/spreadsheets/d/1c4rllFMKVWMyVK_XV6eOU_ujdaseQOBF2ZejEjd7oms/edit?gid=0#gid=0

et la doc sur le budget d'Etat ici : 
https://docs.google.com/document/d/19BCpHkUC1JgJ8r73AKQSw9esth6hU-JJ/edit

peuvent aider à éclaircir certaines définition de libellé ou la méthodologie à utiliser pour extraire l'information dont nous avons besoin.
