### ISSUE TITLE
Impossible d'accéder à une association par la recherche directe mais possible part accès à la page association

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2424]
exemple 1: 305877706

https://app.datasubvention.beta.gouv.fr/search/305877706
qui retourne l'alerte "pas une association"

versus

https://app.datasubvention.beta.gouv.fr/association/305877706
qui affiche une page association

exemple 2 : 478761992
On la trouve par nom mais pas pas SIREN. 
Voici le résultat de la recherche par SIREN : 
```json
{
    "nbPages":1,
    "page":1,
    "results":[{
        "name":"MISTRAL EST",
        "siren":"478761992",
        "address":{"numero":"1","type_voie":"PLACE","voie":"DES ORPHELINS","code_postal":"67000","commune":"STRASBOURG"},
        "nbEtabs":3
    }],
    "total":1
}
```
Or le test est 
```ts
const isAssociation = association => !!association?.rna || isAssoCategory(association?.categorie_juridique)
```

Ici le rna n'existe pas (Alsace-Lorraine) et la catégorie juridique n'est pas remontée

**Comment by alice-telescoop** [comment]
duplicate of #2618
