### ISSUE TITLE
Ajouter une checkbox "utilisateur conscient que son utilisation doit se limiter à son rôle d'agent"

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2432]
pas besoin d'enregistrer dans l'utilisateur, mais bloquer la création tant que c'est pas coché

**Comment by VSerain** [comment]
> pas besoin d'enregistrer dans l'utilisateur, mais bloquer la création tant que c'est pas coché

Ducoup on a pas de risque qu'un mec qui a créer son compte sans l'accepter nous embette ? On devrais pas forcée tous les uttilisateurs a validée cette nouvelle regle avant de pouvoir continuée a uttiliser l'outil ?

**Comment by alice-telescoop** [comment]
Mais il sera bloqué, à moins qu'il ne fasse des requêtes api directes mais ça n'arrive jamais. Ce n'est qu'un blocage front mais pour ce que c'est ça suffit. Et puis c'est dans les CGU aussi
