### ISSUE TITLE
Intégrer des données du CD de l'Oise

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2464]
stuck by #2456

**Comment by alice-telescoop** [comment]
en vrai comme décrit dans le ticket trello c'est pas tout à fait du scdl. Je sais pas trop quoi faire de ce fichier :/ Ça paraît overkill de lui faire un service, adapteur etc dédié et en même temps si on le traite comme du scdl on perd des trucs

**Comment by VSerain** [comment]
Stuck by #[2534](https://github.com/betagouv/api-subventions-asso/issues/2534)

**Comment by alice-telescoop** [comment]
cf #2534 il suffit de les ajouter à la fin du sprint
