### ISSUE TITLE
Données 2022-2023 de la métropole de Lyon

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2490]
https://data.grandlyon.com/portail/fr/jeux-de-donnees/subventions-metropole-lyon/telechargements

il semble que ce soit un seul lien pour toutes leurs subventions donc attentions aux doublons. Il sera à priori normal d'en avoir plein sur l'exercice 2021 déjà en base.

**Comment by alice-telescoop** [comment]
Les guillemets de leurs csv sont pas échappés correctement. On pourrait leur taper sur les doigts ou dev un parseur json qui doit être rapide à faire pour le coup, mais c'est un dev

**Comment by alice-telescoop** [comment]
Je m'en suis débrouillée autrement
