### ISSUE TITLE
Créer un service payments-flat

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2523]
À créer dans modules/data-viz/payments-flat

- créer un paymentsFlatEntity
- intérroger le port ou le repository chorus-line pour acceder à indexed-data et le service dataBretagne
- processeser les données pour avoir l'entité paymentsFlatEntity
- valider ces données

**Comment by VSerain** [comment]
Stuck by #2525 #2526 #2524

**Comment by gcarra** [comment]
Même considerations que dans un autre ticket. Comme Maxime aussi me disait, je ne sais pas si c'est pertinent de séparer tout ça avec un label "Giulia" peut-être que certaines choses vous seraient utiles de l'avoir pendant la suite. Non ?

**Comment by VSerain** [comment]
Eu je vois pas trop pourquoi on voudrais séparer avec un label giulia ?

**Comment by gcarra** [comment]
À créer dans modules/data-viz/payments-flat

- [ ]  créer un paymentsFlatEntity

- [ ] créer dans dataBretagneServices des methodes équivalents à findProgramsRecord pour ministries, ref_programmation et domain_fonct pour retrouver facilement l'info dont on a besoin pour créer payementFlatEntity

- [ ]  intérroger le service dataBretagne et le service chorus-line pour acceder à indexed-data et le service dataBretagne

- processeser les données pour avoir l'entité paymentsFlatEntity
- valider ces données
