### ISSUE TITLE
Dans le service chorus rajouter une methode passe plat pour récupérer toutes les donées de la base en brut

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2526]
Ajouter dans service chorus un findAll ou getAll pour recuperer les données

**Comment by gcarra** [comment]
- [ ] define findAll method in chorus-line repository
- [ ] define getAll method in chorus-line service

**Comment by VSerain** [comment]
Payement entity à des données limité et déjà transformer, ce qui ne convient pas dans le cas actuelle car on veux récupérer les données brut ! Je ne vois pas l'uttilte d'ajouter un label giulia
