### ISSUE TITLE
faire un cli controlleur versements-flat

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2527]
Faire le controller payement flat 
ajouter une méthode qui appelle le service payment-flat pour construire l'incroyable collection !

**Comment by VSerain** [comment]
Stuck by #2523

**Comment by gcarra** [comment]
- [ ] Création du cli et de son test unitaire. 
- [ ] Clarifier : si je fais tourner le cli j'ai des erreurs liés à la connection à l"API dataBretagne qui n'est pas bonne. Comment on gère ça ?
- [ ] Enregistré le newObjectId quelques parts de façon que le cron puisse le récuperer et le donner comme paramètre à la méthode
- [ ] Faire le test d'integration
