### ISSUE TITLE
Refacto la jointure fonjep versement/sub car elle est tres lente sur get grant

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2548]
![Image](https://github.com/user-attachments/assets/eeada0df-5587-4d0c-9352-18e097b76d21)

**Comment by alice-telescoop** [comment]
Idées : 
- [x] rajouter des index
- [ ] créer colonne exercice avec l'exercice sur la table des paiements et l'indexer
- [ ] inverser ordre jointure
