### ISSUE TITLE
Réflechir à comment fournir un max de données deveco

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2550]
Ajouter un rate limite

**Comment by alice-telescoop** [comment]
#2588

**Comment by VSerain** [comment]
Pour l'instant, on mets en place le rate limte (pour l'instant on met 80 requettes par minutes)

**Comment by VSerain** [comment]
Rendez-vous le 10/09 pour la suite

**Comment by VSerain** [comment]
A quelle moment le re rendre service est plus prio que nos prio @VSerain

**Comment by VSerain** [comment]
Discution en cours .... https://mattermost.incubateur.net/betagouv/pl/c7nm96q8cibq7qeh9wsqtbrdih

**Comment by VSerain** [comment]
Done car pas de news, ils reviendron vers nous si jamais
