### ISSUE TITLE
Le lien de certains documents api asso ont un hôte interne au lieu de l'url générale

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2551]
Il semble que le lien de document donné par l'api asso commence parfois par un url interne (`localhost:8181) au lieu de l'url générale accessible depuis l'extérieur.

Ce lien vient d'un appel à une url censée être interne du compte asso

**Comment by VSerain** [comment]
https://sentry.incubateur.net/organizations/betagouv/issues/107898/?query=is%3Aunresolved&referrer=issue-stream&stream_index=0

**Comment by VSerain** [comment]
Faire un premier fix au moment ou l'erreur survient dans l'api -> remplacer le début de l'url localhost:8181 par la vrai url. 
On veux continuer a logger l'erreur actuelle pour suivre ça progression et logger si une erreur survient apres le fix.
Cela nous permetera de faire une diff entre les deux.

Une fois passer en prod et valder, faire le fix en amont, CAD remplacer par default l'url envoyer par l'api

**Comment by alice-telescoop** [comment]
C'est pas arrivé depuis le 22/11/2024. J'ai fait le dev parce que c'est rapide mais j'ai pas pu tester
