### ISSUE TITLE
Créer un type Reponse<T,S>

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#257]
Le but serait d'unifier les reponses de l'api,

Ce type contiendrait soit une interface `SuccessReponse<T>` soit une interface `FailureResponse<S>`.

Ou T est S serait le type qui serait dans data

Implémenter ce type dans toutes les routes

**Comment by mxmeunier** [comment]
@VSerain est-ce qu'on fait vraiment ce ticket ? Sachant que j'ai déjà travailler dessus et qu'on a deux interfaces SuccessResponse et ErrorResponse. La seule diff réside dans la présence ou non d'un object data personnalisé.

Par exemple aujourd'hui on a pour CetAssociationResponseDto cette interface :
```
{
  success: true
  association: Association
}
```

Tu souhaites vraiment que l'on ait :
```
{
  success: true
  data: {
    association: Association
  }
}
```

?
