### ISSUE TITLE
Créer un tableau type et son explication dans le schema Dauphin

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2584]
Il manque : 

- [ ] Mise en prod de la V5 chorus
- [ ] Mise en prod du nouveau csv
- [ ] Envoi du mail à l'ANCT après avoir validé les précédentes deux points

---------------------------------------

Pour la rentrée Anct (cotée dauphin) souhaite que nous leurs fournision un exemple d'extract que nous faison.

Pour ce faire, nous allons créer un tableau dans Dauphin qui listerait les colonnes utilisé par datasubvention.
Une fois ceci fait, il faut clean la table de correspondance pour que ça soit claire.

| Colonne dans Dauphin | Colonne dans DataSub | Path vers la valeur | Description du champ dans Datasub |

Démontrer l'utilisation avec les exemples qu'ils nous demandent, voir CR dans journal de bord

**Comment by VSerain** [comment]
A faire en peer avec un dev et un data

**Comment by gcarra** [comment]
on à bien bosser (2h30) sur le sujet anct avec, voici notre document sur culture du coeurs (https://docs.google.com/spreadsheets/d/1lf8pBgG7rI_kRLu65Trals0h990UmlJfWX9SDhZ7Cf0/edit?gid=766547928#gid=766547928)
Pour l'asso  JOB IN REAL LIFE, on c'est rendu compte que la question du non affichage les lignes pouvais également etre répondu avec l'asso culture du coeurs donc on a pas fait de document appart

**Comment by alice-telescoop** [comment]
La forme ne correspond pas, et il manque les noms techniques dans l'api dauphin (pas uniquement les noms dans les front)

**Comment by gcarra** [comment]
Les modifications suite au dernier commentaire ont été faite. Il restaient d'éclaircir comment la pluri-annualité est traitée et s'assurer que on duplique pas l'information. 

Suite à investigation, je comprends que : 
- on ne duplique pas l'information
- on perds l'information sur le lien entre des financement que sont données sur plusieurs années est qui sont associés à la même demande de subventions. On traite actuellement ces financements comme s'il s'agit de demande de subventions different. C'est ce que j'en comprends en jouant avec les données. Ces financements peuvent être lié ensemble en utilisant l'attribut dauphin.referenceAdministrative.

**Comment by gcarra** [comment]
Il manque : 

- [ ] Mise en prod de la V5 chorus
- [ ] Mise en prod du nouveau csv
- [ ] Envoi du mail à l'ANCT après avoir validé les précédentes deux points
