### ISSUE TITLE
Passer en revue les scdl pour vérifier que les attribuants sont bien homogènes

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#2586]
Contexte : 
Les données France travail ont des attribuant différent pour un même fournisseur hors notre code supposent que les attribuant sont homogènes sur fournisseur donné.
Le ticket #2384 change ce comportement, ce ticket (le #2586) consiste à identifier les fichiers à éventuellement réimporter.

**Comment by alice-telescoop** [comment]
vérifier notamment la métropole de Lyon

**Comment by alice-telescoop** [comment]
@gcarra à voir avec l'évolution du format

**Comment by gcarra** [comment]
@alice-telescoop, merci pour l'info. Dans le nouveau format https://docs.google.com/spreadsheets/d/1y734YhO7JJqYMf1fhKrOrl0MfSFEsyecdlQ2LE0dTT0/edit?gid=1852322444#gid=1852322444

il y a bien un attribut "attribuant", est-ce que c'est bien ça que tu suggérer de vérifier ? Ou tu vois autre chose ?

**Comment by alice-telescoop** [comment]
| provider               | homogène | inhomogène |
|------------------------|----------|------------|
| centre-val-de-loire    | X        |            |
| lys-saint-georges      | X        |            |
| grand-est              | X        |            |
| lyon                   | X        |            |
| ademe                  |          |            |
| nievre                 |          |            |
| paris                  |          |            |
| bretagne               |          |            |
| normandie              |          |            |
| aix-marseille-provence |          |            |
| aura                   | X        |            |
| antibes                | X        |            |
| cd-oise                |          | X          |

TODO trouver/ranger les autres
