### ISSUE TITLE
montant accordé osiris non affiché

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#2622]
stuck by #2662

**Comment by alice-telescoop** [comment]
https://mattermost.incubateur.net/betagouv/pl/yxd1grojdbfcffhwdpodwiye1r

77566314900273

**Comment by mxmeunier** [comment]
à voir quand @gcarra aura fait l'investigation

**Comment by VSerain** [comment]
@alice-telescoop n'oublie pas :D

**Comment by alice-telescoop** [comment]
C'est une conséquence de #2688, fixé donc dans #2689 (+ le réimport des données à faire à la MEP(P))
