### ISSUE TITLE
Sortir date + ancienne dans api historique des imports

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#2641]
suite de [#2589](https://github.com/betagouv/api-subventions-asso/issues/2589)

format attendu : 
```
{
     identifiant_fournisseur: string,
     derniere_date_integration: Date; // Date à la quelle les données ont ajoutées à data-subvention
     derniere_date_edition: Date; // Date à la quelle les données ont été extraite par le fournisseur
     premiere_date_integration: Date; // Date du premier ajout de données ce ce fournisseur
}
```

- [x] ajouter propriété premiere_date_integration
- [x] renommer derniere_date_integration et derniere_date_edition
- [ ] modifier requête d'aggrégation pour calculer premiere_date_integration
- [ ] renseigner en db de quoi répondre pour le passé

**Comment by mxmeunier** [comment]
Ca doit être rétroactif ?

**Comment by alice-telescoop** [comment]
Oui, le ticket contient le fait d'enquêter auprès des bizdevs pour pouvoir renseigner dans la db de quoi donner la première et la dernière date

**Comment by mxmeunier** [comment]
Je ne comprend pas ce point

> modifier requête d'aggrégation pour calculer premiere_date_integration
