### ISSUE TITLE
Retirer le message d'info indisponible côté payement pour les subv non acceptées

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#2642]
https://www.figma.com/design/t6nWdBwKr8fancez3VO5kr/Data.Subvention---D%C3%A9veloppeurs?node-id=12423-42390&node-type=INSTANCE&m=dev

(à valider)
- subv acceptées : Information actuellement indisponible
- autres : aucun message

**Comment by alice-telescoop** [comment]
@Gttnmarion on laisse vide uniquement pour les refusées, ou au contraire on ne garde le message que pour les acceptées ?

**Comment by Gttnmarion** [comment]
On ne garde le message que pour les acceptées.
