### ISSUE TITLE
verifier sur scalingo que les données sont chiffrées

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#2660]

**Comment by mxmeunier** [comment]
Un peu de contexte ? 

De quelles données parle-t'on ? Celles qui transitent par HTTP ?

**Comment by alice-telescoop** [comment]
Le contexte, c'est pour pouvoir remplir Mon Service Sécurité en vue de l'homologation de sécurité. Mais du coup c'est pas plus précise, mais je pense essentiellement au disque dur du serveur et à la db

**Comment by mxmeunier** [comment]
voir avec Scalingo si elles le sont et sinon comment faire

**Comment by alice-telescoop** [comment]
sur OVH : ✅ (cf https://help.ovhcloud.com/csm/fr-public-cloud-databases-concepts-security-overview?id=kb_article_view&sysparm_article=KB0048879#82-data-encryption)

**Comment by alice-telescoop** [comment]
Oui c'est chiffré : https://doc.scalingo.com/security/overview/physical-security

**Comment by alice-telescoop** [comment]
@VSerain @mxmeunier ça vous convainc ?
