### ISSUE TITLE
Faire une table de correspondance ApplicationFlat sur Osiris

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2662]
Le mapping se trouve [ici](https://docs.google.com/spreadsheets/d/1VcSJiCE_O-DXFSJlqCAz1AS2RSvX2Rkz/edit?gid=1257401545#gid=1257401545). 

- [x] Validation et éclaircissement avec JFM

**Comment by gcarra** [comment]
Un premier échange clarificateur avec JFM a été effectué. On travaille pour finaliser cela.

**Comment by gcarra** [comment]
Il manque l'éclaircissement sur la question du SIRET. 

Est-ce qu'on stock des Ridet et Thaiti dans le SIRET et si oui est-ce qu'on modifie l'identifiant pour le discerner du SIRET ?
