### ISSUE TITLE
Investiguer sur la disparition des données Chorus (AURA)

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2665]
~~regarder dans le collection chorus-line-old si c'était déjà présent~~

présent dans chorus-line-save donc c'est bien une régression V0004

**Comment by mxmeunier** [comment]
https://mattermost.incubateur.net/betagouv/pl/bswaua7psjybz8ermfmsphfb4e

**Comment by alice-telescoop** [comment]
Le gars de chorus doit faire un retour

**Comment by mxmeunier** [comment]
Import 2023 en local 


Log de la commande :
207751 lignes parsées
207751 entitées valides
207751 entitées sauvegardées

Mais seulement 114501 documents dans MongoDB soit presque 50% de doublon.

**Comment by alice-telescoop** [comment]
Donc ça vaut le coup de restaurer `chorus-old` non ?
