### ISSUE TITLE
Travailler sur les correspondances FONJEP

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2697]
lié à #2818 

- [ ] table compréhension des donnée FONJEP. [Ici](https://docs.google.com/spreadsheets/d/1iLcwsP6pKWQxu3L6IVdzaUCN-_aPYORINB6OGd7fHzA/edit?gid=23086927#gid=23086927) le travail en cours
- [ ] table de correspondance. [Ici](https://docs.google.com/spreadsheets/d/1VcSJiCE_O-DXFSJlqCAz1AS2RSvX2Rkz/edit?gid=1257401545#gid=1257401545) le travail en cours

**Comment by gcarra** [comment]
- [ ] Un premier travail a été fait avec Yasmine
- [ ] Un mail a été envoyé pour planifier un échange avec le fournisseur. 
- [ ] Validation avec fournisseur

Questionnement : moi je m'interroge que sur les données concernant mes schémas. Est-ce que à chaque fois ça vaudrait la peine que Marion fasse un passe dessus éventuellement avec Yasmine pour voir si elle a besoin d'autres infos spécifiques pour le front ? à mettre dans une collection "données spécifiques" ?
