### ISSUE TITLE
ajouter deux attributs à l'entité Osiris

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2700]
Sera fait dans #2785 

Ici https://docs.google.com/spreadsheets/d/1VcSJiCE_O-DXFSJlqCAz1AS2RSvX2Rkz/edit?gid=1257401545#gid=1257401545 le mapping Osiris ApplicationFlat, j'ai besoin de deux attributs qui existent mais qui ne sont pas enregistrés : 

- exerciceBudgetaire = année pour lequel on demande l'extraction
- dateDepotDemande = Date Reception dans Osiris

**Comment by alice-telescoop** [comment]
@gcarra j'ai une question par rapport à ton mapping osiris : as-tu fait la différence entre osiris actions et osiris requests ? Comment as-tu procédé ?

**Comment by alice-telescoop** [comment]
Notamment j'ai l'impression de trouver la date de dépôt de demande à l'échelle de l'action, et nos demandes de subventions c'est l'échelle des dossiers (et il peut y avoir plusieurs actions pour un même dossier). À quelle échelle t'es-tu placée pour ton mapping ?

**Comment by alice-telescoop** [comment]
Et c'est pas super clair pour moi où tu voudrais que ce soit enregistré. Dans `data` de chacune des tables ?

**Comment by alice-telescoop** [comment]
C'est bien dans le excel des dossiers je sais juste pas chercher. Par contre stuck by #2662

**Comment by mxmeunier** [comment]
Sera fait dans #2785
