### ISSUE TITLE
revoir paymentFlat suite à changements Chorus

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2701]
agreger le nouveau Chorus avant de les ajouter à paymentFlat de façon à avoir le bon niveau de granularité

**Comment by gcarra** [comment]
Choix à faire. 

Pour créer paymentFlat à partir de chorus : 

1) je récupère sur chorus les dernières documents qui ont été ajoutés ou modifiés par rapport à mon dernier import sur paymentFlat
2) je mèrge avec les données data.breagne pour avoir activité, action, ministere, mission etc. 
3) je crée l'uniqueId pour ma future paymentFlat = siret, ej, action, activite, programme
4) j'agrège les données afin de faire la somme des montants des versements ayant le même uniqueId
5) et là une problèmatique se pose : 

a) si l'uniqueId n'est pas déjà sur paymentFlat, tout va bien!! 
b) si l'uniqueId est déjà sur paymentFlat et le nouveau versement chorus est un vrai nouveau versement et pas une modification d'un ancien (cas réel mais qui arrive) alors je peux ajouter le montant lors de l'upsert j'imagine.
c) si l'uniqueId est déjà sur paymentFlat et le nouveau versement chorus est une modification d'un ancien (cas réel mais qui peut arriver) alors je peux ajouter le montant lors de l'upsert mais je n'ai pas moyen de soustraire celui a été mal ajouté. 

Et il me semble que je n'ai pas une façon facile de discerner le cas a) du cas b). 

Est-ce qu'il vaut mieux tout effacer et tout mettre à jour à chaque fois de paymentFlat ? Voyez-vous une autre solution ? 
@mxmeunier @alice-telescoop je ne sais pas si j'ai été claire :/ mais vous avez des opinions sur le sujet ? Un de vous deux est dispo pour faire un petit point là-dessus demain aprèm ?

**Comment by alice-telescoop** [comment]
Si ya des modifs et qu'on ne peut pas les distinguer je ne vois pas d'autre option que de vider refaire. P-ê que ça vaut le coup de s'assurer qu'on ne peut effectivement pas les distinguer mais si tu as bien vérifié je te crois et j'ai pas d'autre idée
