### ISSUE TITLE
Status DS manquant alors qu'accepté

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2738]
Test: 42237472800026

**Comment by mxmeunier** [comment]
https://mattermost.incubateur.net/betagouv/pl/xqk8i5fpnpdn8dc7kxhfiqnfoa

**Comment by alice-telescoop** [comment]
Ya pas de ticket technique c'est quand c'est pas bien renseigné à la source par les humains. Je close, râlez si c'est pas bon
