### ISSUE TITLE
[BUG] Page asso -> onglet document : Le btn Reinitialiser devrais etre grisser et changer le terme

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2744]
Situation : 
Sur l'onglet document, le bouton "réinitialiser" est toujours cliquable même quand il n'a rien à reset. De plus le texte n'est pas très clair

Taches : 

- [x] Trouver une nouvelle formule pour le bouton @gttnMarion
- [x] #2847
- [x] Changer le texte par celui proposé par Marion

**Comment by VSerain** [comment]
Nouveau texte : "Tout desélectionnée"

**Comment by Gttnmarion** [comment]
![Image](https://github.com/user-attachments/assets/8481ab19-bb06-4f79-84dd-45743943b7f7)
![Image](https://github.com/user-attachments/assets/12da58bd-c8b0-4ab9-bc98-5241d33299bf)

**Comment by VSerain** [comment]
Tous fini je close l'épique
