### ISSUE TITLE
OSIRIS - revue du processus d'import, de correspondance et de stockage des données sur MongoDB

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#2749]
Pourquoi cette EPIC ? 
-> des données concernant les subventions pluriannuels sont écrasés. 
-> un attribut dont j'ai besoin pour applicationFlat manque. 
-> vérification que le mapping actuellement utilisé est correcte 
-> on s'était accordé.es qu'il valait le coup de revoir au fur et mesure le format de données sur MongoDB et le modifier si pertinent.

- [ ] #2785 
- [x] #2876 
- [ ] Mettre à jour AppliationFlat
- [ ] Définir la fréquence et les années récupérés à chaque import

**Comment by mxmeunier** [comment]
@VSerain à transformer en epic de ton côté ?

**Comment by mxmeunier** [comment]
@VSerain en particulier #2785 qui doit être pris dans le prochain sprint

**Comment by VSerain** [comment]
Je close le ticket car les sujets sont dans d'autres tickets
