### ISSUE TITLE
Investiguer sur la meilleure solution pour améliorer la BDD FONJEP 

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2783]
Mettre à jour le CLI/parser pour sauvegarde chaque onglet dans une nouvelle collection

On souhaite faire une collection par onglet du fichier fonjep pour pouvoir dans la suite traiter les données brut directement

**Comment by alice-telescoop** [comment]
## Rangement de la donnée

- pour la base : enregistrer les données brutes (+  indexedData données spécifiques cf 3e point) avec autant de tables que nécessaies (ie 3 pour fonjep : tiers, demande, versement)
- pour le front : récupérer les infos d'une table jointe demande-versement (utiliser les materialized views[^1] si possible, sinon la faire ± à la main) générée à partir de `ApplicationFlat` et `PaymentFlat`
- pour la future page subvention : récupérer les infos génériques de la table jointe et aller chercher dans la table dédiée aux fournisseur les infos dédiées dans une espèce de `indexedData` dédiée aux infos spécifiques. On fusionne donc tout ça pour le retour de la route

## NB
- attention à bien se mettre d'accord sur le providerId enregistré sur ApplicationFlat pour arriver à récupérer les infos spécifiques

## Étapes d'implémentation
### pour le tableau de bord
- validation table correspondance (/!\ temps incertain)
- re-parser fonjep en 3 collections exhaustives brutes
- dev alimentation PaymentFlat & ApplicationFlat par fonjep
- créer table jointure [^a
- brancher l'appel api du front à table jointure (et désactiver vieilles tables fonjep)
## pour les pages par subv
- isoler dans les tables données brutes un `indexed` d'infos spécifiques au fournisseur intéressantes
- par appel récupérer cette info et l'ajouter au résultat de la table jointure

-------
## Ouverture

### à implémenter pour les autres fournisseurs
- tableau de bord
	- validation table correspondance
	- avoir les données brutes
	- dev alimenter tables Flat avec 
	- [commun] alimenter table jointe 
		- automatiser màj le soir ; déclenchée par booléen à l'ajout de données
		- au plus fin par versement et plat ou par demande et nested ? => plus réutilisable par Giulia si flat
	- [commun] brancher api du front à table jointure (et désactiver vieille table)
- page par subv
	- isoler dans les tables données brutes un `indexed` d'infos spécifiques au fournisseur intéressantes
	- par appel récupérer cette info et l'ajouter au résultat de la table jointure

------

## Questions
- c'est l'occasion de faire du SQL ? plus facile à transmettre pour l'internalisation et ce serait le moment
- le moment de mettre en place airflow ? 
- L'extract dans tout ça : 
    - bloqué par la réparation 
    - **ou** il faut concevoir un quick fix
    - **ou** en investigation on a une autre solution (perf mongo ?)

**Comment by alice-telescoop** [comment]
Ça prend bcp d'ampleur, point sur airflow le 25/10

**Comment by mxmeunier** [comment]
@VSerain je devais bien le passer dans le BL PO ce ticket ?
