### ISSUE TITLE
Valider le mapping de Giulia avec l'existant

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2784]
Histoire de bien voir si on avait pas des problème technique qui auraient défini certains workaround

**Comment by alice-telescoop** [comment]
avec @VSerain @alice-telescoop  et @gcarra on se dit qu'on peut fermer ça, ne pas le traiter comme ticket à part et on verra si ya des soucis au moment d'implémenter. Notamment @alice-telescoop et @gcarra ont déjà eu des discussions.

À confirmer avec @mxmeunier au prochain point ticket
