### ISSUE TITLE
Changer le texte et le lien du bandeau

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2788]
Pour les besoins biz dev, on souhaite changer le contenu du bandeau (MainInfoBanner)

**Comment by VSerain** [comment]
Repso coté biz dev : Louis & | Soumaya

**Comment by Gttnmarion** [comment]
Texte : Exclusivement pour les agents publics : formez-vous en moins d'une heure à Data.subvention et gagnez un temps précieux au quotidien : [plus d'information](https://datasubvention.beta.gouv.fr/webinaireformation-datasubvention/?mtm_campaign=webinaireformation&mtm_source=appli-bandeau)
