### ISSUE TITLE
Reverifier la table de correspondance Dauphin vis à vis des actions

### ISSUE THREAD

**Issue by gcarra** [betagouv/api-subventions-asso#2790]
Marion me signale que aujourd'hui pour Dauphin une même demande de subvention est dupliquée autant de fois que les actions qu'elle contient. 

- [x] Vérifier que avec la table de correspondance actuelle ce n'est plus le cas.
- [x] Si c'est encore le cas investiguer comment corriger cela.

Informations partagées par Marion : 

https://app.datasubvention.beta.gouv.fr/association/W611000253 pour l'année 2021

- Dans dauphin 2021 il y a deux documents associés au dispositif Mobilité emploi - Politique de la ville. Un ayant comme titre projet "Mobijump plateforme mobilité." et l'autre ayant "Location solidaire de véhicule « n@vette »." Dans dauphin  ces deux lignes ont une referenceAdministrative différente 00054802 et 00054562-01 respectivement. En étant une subvention pluriannuel on obtient le lien entre les différents années de la façon suivante : refAdm-01, refAdm-02, refAdm-03.

Dans GISPRO ces deux documents correspondent bien à deux lignes mais ils ont le même projet - Code dossier et le même engagement juridique. Nous en déduisons ainsi que elles correspondent à la même demande de subventions mais à deux actions différentes.

![Image](https://github.com/user-attachments/assets/8c0f7455-6dd2-44d6-a20e-7190f084e24c)

Il reste à revoir la table de correspondance que on avait fait avec Victor. et à faire correspondance avec applicationFlat et PaymentFlat.

Avant de pouvoir faire ça, valide avec @alice-telescoop : 

- [x] (avec Alice) la question de la referenceAdministrative des fois absente
On ne sais pas trop pourquoi certaines documents n'ont pas la referenceAdministrative
Next steps avant de décider quoi faire. 
- [x] regarde nombre de documents concernés sur totale
1265 sur 175949 = 0,7%
- [x] regarde si chaque fois que referenceAdministrative est absente, l'attribut dauphin.multiFinancement.financeurs.source.reference est absent aussi. 
Oui si referenceAdministrative est absente dauphin.multiFinancement.financeurs.source.reference est absent aussi
- [x] Est-il possible qu'il s'agit des doublons dont G. parlait ? 
Aucune information me permets de deduire ça. Par contre dans leurs tableau de bord on ne retrouve pas les données des documents n'ayant pas de reference Administratif => moi je propose de pas afficher ces données.

- [x] (avec Alice) quels fichiers GISPRO on utilise et comment la jointure est faite.
On utilise les données GISPRO qui sont dans les drives (pas la dernière version envoyée). la referenceAdministrative est utilisée pour faire la jointure entre GISPRO et dauphin mais actuellement le -01 est éliminé ce qui n'est pas pertinent car on perds l'info sur la pluriannualité et on fait une jointure pas précise.

**PROCHAINES ETAPES (autre ticket) : ** @VSerain 
- faire mapping avec applicationFlat et paymentFlat en sachant que l'ANCT doit nous envoyé des choses

**Comment by alice-telescoop** [comment]
voir notes #2001

**Comment by gcarra** [comment]
@Gttnmarion est-ce que tu serais me re-indiquer le ticket de l'investigation que toi et Victor vous aviez fait à ce sujet.
@VSerain j'avais un peu l'impression que on avait mis en standby ce sujet mais il est dans le sprint, je le prends quand même du coup ?

**Comment by Gttnmarion** [comment]
Le ticket EPIC : https://github.com/betagouv/api-subventions-asso/issues/2001
Le figma avec toutes les infos : https://www.figma.com/design/t6nWdBwKr8fancez3VO5kr/Data.Subvention---D%C3%A9veloppeurs?node-id=11664-29338&t=oK6iC4pyQSRh6Kom-4

**Comment by gcarra** [comment]
@VSerain @alice-telescoop est-ce que vous savez pourquoi dans mongoDB dauphin pas tous les documents ont l'attribut "referenceAdministrative" ? Est-ce que cela est du à comment vous avez importé et enregistré les données ?

**Comment by VSerain** [comment]
Je dirais que c'est que ça n'était pas dans toutes les données, apres un coup d'oeil dans le code devrais repondre à ta question ;)
