### ISSUE TITLE
Créer une ressource pour modifier la configuration du bandeau d'information

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2853]
Story:

### Description

Ajouter un document dans la collection `configurations` et créer la route associée. Elle prendra comme body

```js

{ title: "", desc: "", link: "", labelLink: ""} 

```

Vérifier côté front pour que ce soit ISO

Créer la route postman qui va bien

**Comment by alice-telescoop** [comment]
https://github.com/betagouv/api-subventions-asso/issues/2753#issuecomment-2460237429
> Louis m'a dit qu'ils était ok pour ecrire du HTML et l'objectif est de faire au plus simple pour nous comme pour eux.
> 
> Faudra juste leurs faire un exemple claire dans postman

Let's do avec juste `title` et `desc` du coup..?
