### ISSUE TITLE
Vérifier le format et la qualité du jeu de donnée Santé Public

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2854]
Story: #2812

J'ai fait [ce fichier](https://docs.google.com/spreadsheets/d/182ht1zRPWo2hYpVe6vzOAyHaar5jIjzS/edit?gid=1801672851#gid=1801672851) qui permets de voir que le format n'est pas un format SCDL qu'il y a des choses en plus par rapport au scdl standard et des choses en moins. 

J'ai préparé un mail que j'ai envoyé à @VSerain sur le sujet mais je m'apperçois que je n'ai pas mis la question sur quel outil de versement utilisent ? Est-ce qu'ils ont aussi des données paymentFlat. Il n'y a pas d'ailleurs en bizdev en charge de tout ça ?

**Comment by VSerain** [comment]
Je vous ai transféré le mail sur la boite dev.

Objectif n1 comprendre les données et voir si on veux leurs en demandé plus / moin / different. Ils etait très volontaire dans les echanges

**Comment by gcarra** [comment]
https://docs.google.com/spreadsheets/d/182ht1zRPWo2hYpVe6vzOAyHaar5jIjzS/edit?gid=1801672851#gid=1801672851
