### ISSUE TITLE
Mettre à jour les indexedInformations OSIRIS avec le nouveau mapping

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2876]
Epic: #2749 

### Description

Mettre à jour les données indexées en se basant sur le nouveau mapping fait pas Giulia : 

https://docs.google.com/spreadsheets/d/1VcSJiCE_O-DXFSJlqCAz1AS2RSvX2Rkz/edit?gid=1257401545#gid=1257401545

Rajouter exercice budgétaire ??
Mettre ApplicationFlat à la place de IndexedInformations ??

### Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by VSerain** [comment]
Finalement on ne le fait plus car les regles seront faite via applicationFlat
