### ISSUE TITLE
Faire et valider avec JFM la table de correspondance associationFlat

### ISSUE THREAD

**Issue by gcarra** [betagouv/api-subventions-asso#2889]
[ici](https://docs.google.com/spreadsheets/d/1VcSJiCE_O-DXFSJlqCAz1AS2RSvX2Rkz/edit?gid=1703264057#gid=1703264057) la table associationFlat;
J'ai avancé sur associationFlat, j'ai joué un peu avec les données SIRENE : 
- on n'a pas de doublons dans les siren 
- plusieurs siren peuvent être associés à un même RNA 

@victor.serain tu me disais que le même SIREN peut être associé à plusieurs RNA. ça on ne le voit pas à partir de base de données siren et la base de données RNA moi je pensais l'utiliser que pour faire la jointure => il ne va pas apparaitre après la jointure.
Je pourrais jeter un oeil à la base RNA une fois que sera dans mongo car le telechargement complet est plus complexe par rapport à celui de SIRENE

Pour les libelles et le format précis du DBO je préfère attendre que les données brutes soient en base et je pense que c'est un travail à faire éventuellement avec Marion.

@VSerain @alice-telescoop @Gttnmarion n'hésitez pas à me faire vos retours et/ou commentaires

**Comment by gcarra** [comment]
Salut, 
J'ai avancé sur associationFlat, j'ai joué un peu avec les données SIRENE : 
- on n'a pas de doublons dans les siren 
- plusieurs siren peuvent être associés à un même RNA 

@victor.serain tu me disais que le même SIREN peut être associé à plusieurs RNA. ça on ne le voit pas à partir de base de données siren et la base de données RNA moi je pensais l'utiliser que pour faire la jointure => il ne va pas apparaitre après la jointure.
Je pourrais jeter un oeil à la base RNA une fois que sera dans mongo car le telechargement complet est plus complexe par rapport à celui de SIRENE

**Comment by VSerain** [comment]
> Salut, J'ai avancé sur associationFlat, j'ai joué un peu avec les données SIRENE :
> 
>     * on n'a pas de doublons dans les siren
> 
>     * plusieurs siren peuvent être associés à un même RNA
> 
> 
> @victor.serain tu me disais que le même SIREN peut être associé à plusieurs RNA. ça on ne le voit pas à partir de base de données siren et la base de données RNA moi je pensais l'utiliser que pour faire la jointure => il ne va pas apparaitre après la jointure. Je pourrais jeter un oeil à la base RNA une fois que sera dans mongo car le telechargement complet est plus complexe par rapport à celui de SIRENE

Je dirait plutot que plusieurs siren peuvent avoir le meme rna dans la db siren ! 
Je rajoute un warning sur le faite que meme si la base siren est la plus complet il existe d'autre base (rid, tahiti) qui represente des entreprises de france et qu'on doit faire attention à ne pas les exclures

**Comment by VSerain** [comment]
> > Salut, J'ai avancé sur associationFlat, j'ai joué un peu avec les données SIRENE :
> > ```
> > * on n'a pas de doublons dans les siren
> > 
> > * plusieurs siren peuvent être associés à un même RNA
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @victor.serain tu me disais que le même SIREN peut être associé à plusieurs RNA. ça on ne le voit pas à partir de base de données siren et la base de données RNA moi je pensais l'utiliser que pour faire la jointure => il ne va pas apparaitre après la jointure. Je pourrais jeter un oeil à la base RNA une fois que sera dans mongo car le telechargement complet est plus complexe par rapport à celui de SIRENE
> 
> Je dirait plutot que plusieurs siren peuvent avoir le meme rna dans la db siren (a valider) ! Je rajoute un warning sur le faite que meme si la base siren est la plus complet il existe d'autre base (rid, tahiti) qui represente des entreprises de france et qu'on doit faire attention à ne pas les exclures

Et probablement que plusieurs linge des fichiers rna peuvent point vers le même siren ! 

Si il ce trouve qu'il n'y a effectivement pas de doublon, faudrait qu'on regarde pourquoi nous on en a !
