### ISSUE TITLE
ETQ datasub, je veux valider que le format Application Flat

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#2901]
- [x] #2961
- [x] #2913
- [x] #2914

**Comment by mxmeunier** [comment]
@VSerain @gcarra faire les tickets de tâches associés

**Comment by VSerain** [comment]
@gcarra on est ok que c'est duplicate de https://github.com/betagouv/api-subventions-asso/issues/2800 ?

**Comment by gcarra** [comment]
@VSerain pour moi ce n'est pas exactement la même chose mais fortement liée

**Comment by VSerain** [comment]
Tous les sujet liée a cette epic sont fini ! Je close
