### ISSUE TITLE
Rendre téléchargeable les fichiers provenant du RNA qui ne le sont pas

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#2911]
Lié à #2551, voir si encore besoin après #2551 

### Description

Certaines pièces provenant du RNA ne sont pas téléchargeable : 

### Comment reproduire

Essayer de télécharger les documents RNA de l'association 924173024

**Comment by alice-telescoop** [comment]
duplicata #2551 ? @VSerain est-ce qu'on priorise ?

**Comment by VSerain** [comment]
> duplicata #2551 ? @VSerain est-ce qu'on priorise ?

Je dirai que c'est le ticket dev non ?

**Comment by VSerain** [comment]
Ah non, ça semble un duplicate
je dirait on fait l'autre en prems et on vois si on a plus d'erreur apres

**Comment by alice-telescoop** [comment]
@1383 ?

**Comment by VSerain** [comment]
On close jusqu'à ce que les gens hurle a nouveau
