### ISSUE TITLE
Mettre à jour Lerna

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#308]
Lerna est montée en version (5.x).

On devrait se mettre à jour pour profiter des différentes améliorations.

EDIT: cette montée en version peut peut-être régler le problème #363

**Comment by VSerain** [comment]
Je déplace le ticket en Ready car il ai faisable

**Comment by VSerain** [comment]
Pensée à déplace/supprimer le ticket #363 à la fin de cette issue
