### ISSUE TITLE
Ajouter TypeScript dans le front

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#330]
STUCK: nécessite un front 100% svelte

Ajouter typescript à svelte

**Comment by VSerain** [comment]
On stuck, car on est bloqué et qu'on préfère avancer plutôt que de mettre TypeScript.

Attendre le moment où tout le front est passé en svelte pour voir la nécessité de passer à TypeScript

**Comment by alice-telescoop** [comment]
Penser à reprendre les imports `dto` qui ont dû être faits sur svelte à partir des fichiers de `build`

**Comment by alice-telescoop** [comment]
avec #1545
