### ISSUE TITLE
Créer un parser pour UniteLegalHistory

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#357]
Documentation : 
[description-fichier-stockunitelegalehistorique-2.pdf](https://github.com/betagouv/api-subventions-asso/files/9919586/description-fichier-stockunitelegalehistorique-2.pdf)

Créer une parser pour UniteLegaleHistory qui récupère la dernière entrée dans la table import-unite-legale et filtre les lignes afin de ne garder que celles dont la dateDebut est inférieure à la dernière date d'import.

Pour le moment ce limiter à l'ajout de siret et au changement de nom

TODO:
- (télécharger le fichier en local)
- Récupérer la dernière entrée dans la table datagouv-history-import
- Filtrer les lignes du fichier en ne gardant que celles dont la dateDebut est inférieur à la dernière date d'import.
- Filtrer les lignes en fonction de si elles concernent une entreprise ou une association (grace à la categorieJuridique, voir fichier LegalCategoriesAccepted.ts):

Si c'est une entreprise :
- Mettre à jour la collection datagouv-entreprise-siren si le siren n'est pas déjà présent (voir si on peut déterminer la ligne de creation de l'entreprise pour éviter ces vérifications).
Si c'est une association : 
- Vérifier si la variable changementNomUniteLegale est à true. Si tel est le cas, ajout du nouveau nom dans la table association-name (voir si on peut déterminer la date de création de l'entreprise).

- Regarder les variables changementCategorieJuridiqueUniteLegale (vérifier que lors de la création d'une entreprise ce booléen soit à true) et categorieJuridique pour déterminer si c'est une entreprise ou une association
- En fonction des lignes,  si c'est une entreprise, ou la collection association-name si c'est une association
- Mettre à jour la table datagouv-history-import avec la date du jour lorsque le parsing est terminée.

**Comment by VSerain** [comment]
@mxmeunier on est d'accord que la partie entreprise ne doit pas être faite dans ce ticket ?

**Comment by mxmeunier** [comment]
oui elle est décrite dans l'autre ticket
