### ISSUE TITLE
Séparation RNA SIREN - SUITE

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#407]
STUCK: en attente de consensus sur le design à adopter.

Le nom affiché de l'association doit être la dénomination RNA (Le RNA étant la source de vérité en ce qui concerne les associations)

Rajouter dans la partie unité legal de la page association les 4 dates CAD:
- Date de création au RNA
- Date de création au SIREN
- Date de modification au RNA
- Date de modfication au SIREN

Revoir avec @valerie-daoduy pour l'intitulée des différentes dates (Date de modification au greffe ou quelque chose du genre)

Rajouter un tableau à deux colonnes : 
- RNA
- SIREN

Dans chaque colonne, il doit y avoir deux lignes :
- La denomination
- L'adresse

**Comment by mxmeunier** [comment]
@VSerain que veut dire "afficher les 4 dates" ? Et en cas de VS nom/adresse que fait on si il y a des différences ?

**Comment by VSerain** [comment]
Je re-détail ça ;)

**Comment by VSerain** [comment]
@mxmeunier c'est mieux ?

**Comment by mxmeunier** [comment]
Oui c'est bien mieux et je vois maintenant que cela implique une modification du design

**Comment by valerie-daoduy** [comment]
Pour les intitulés des dates, on peut laisser comme tu as mis car j'ai peur qu'introduire la notion de "greffe" trouble nos utilisateurs non experts des démarches. En revanche, je me demande si au lieu de "Date de création au SIREN", il faut mettre "Date de première immatriculation au SIREN" ou laisser "création"?

**Comment by VSerain** [comment]
Est-ce qu'on peut se faire immatriculer plusieurs fois ? Si c'est pas le cas est-ce que date d'immatriculation siren serait suffisant ? @valerie-daoduy je vois que github est devenu ton ami :D

**Comment by mxmeunier** [comment]
Je pense comme Victor et simplement mettre "Date d'immatriculation au SIREN" sauf si c'est courant de changer de SIREN...

**Comment by valerie-daoduy** [comment]
Oui, je crois qu'à chaque changement de SIRET, on parle d'immatriculation donc c'est pour ça que je me posais la question mais vous avez peut-être raison, on met "immatriculation" pour la première et ensuite on met "modification"? @VSerain oui, je fais des efforts pour que github et moi, on ne se quitte pas fâchés !

**Comment by mxmeunier** [comment]
<img width="1222" alt="Capture d’écran 2022-09-19 à 12 31 33" src="https://user-images.githubusercontent.com/7630775/191067525-49648464-eb79-429a-9e0c-c7bc820ee4d1.png">

@valerie-daoduy voici ce que rend un tableau deux dimension pour comparer les informations RNA/SIREN.

Est-ce que ça te vas ou tu voyais quelque chose d'autre ? @VSerain tu as un avis ? J'ai gardé le style du DSFR (légèrement modifié pour un tableau à deux dimensions).

Et vue avec le reste de la page : 

<img width="1267" alt="Capture d’écran 2022-09-19 à 12 33 50" src="https://user-images.githubusercontent.com/7630775/191067733-44ff8ba1-9300-4013-aa81-07c7559aabbd.png">

C'est pas super top niveau couleur design mais j'attend des retour (peut-être une petite présentation en fin de daily pour avoir un avis général sur les couleurs à utiliser si on veut dévier du design system ?)

**Comment by VSerain** [comment]
Hello, je trouve ça bien ! 
Les dates sur siren semblent bizarres non ?

J'aurais peut-être mis une bordure sur le tableau, mais il faudrait voir en vrai. Et un tout peut moins d'espace entre le tableau et le reste ;)

**Comment by valerie-daoduy** [comment]
Hello, hello,
Oui, c'est bien ce type d'affichage comparatif qui serait utile, cependant, comme Victor, je m'interroge sur les dates côté SIREN qui sont étranges (je ne pense qu'il y avait l'INSEE au 19ème siècle) et je trouve que le design du tableau détonne un peu par rapport au reste...
