### ISSUE TITLE
Renomer le provider DataEntreprise en ApiRna

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#450]
Choisir un nom entre "API RNA" ou "API RNA donnée ouverte".

- Supprimer la partie qui récupère les données sur la base "API SIREN donnée ouverte" qui est coupée.
- Vérifier dans le code si l'on utilise directement ce provider pour des infos sur le siren. Clean si besoin.
- Demande à l'équipe bizdev de mettre à jour le fichier cartographie des fournisseurs en supprimant "API SIREN donnée ouverte" ou en l'indiquant fermé.

**Comment by mxmeunier** [comment]
Supprimer tout le provider qui est déprécié. Utiliser API ASSO dans RnaSiren en remplacement
