### ISSUE TITLE
Permettre d'inclure les versements dans la remontée de subventions

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#479]
Effectuer la jointure subvention - versement depuis l'API (actuellement fait coté front).

Pour se faire, créer une route /association/id/subventions-versements

Rajouter un tableau versements pour chaque subvention

Double sujet HTTP et SSE

**Comment by mxmeunier** [comment]
@VSerain on pensait finalement créer une autre route /association/:id/subventions-versements (route modifiable) parce que sans ça on ne sait pas comment gérer les versements non liés à des subventions.

**Comment by VSerain** [comment]
Hum pas bête, j'avoue qu'à froid, je ne me souviens plus trop du pourquoi !

**Comment by VSerain** [comment]
Mais ça me va

**Comment by mxmeunier** [comment]
Discuter du format open-data et si il convient à ce besoin

**Comment by mxmeunier** [comment]
@VSerain est-ce qu'on est bon là dessus ?

**Comment by VSerain** [comment]
Je crois que oui

**Comment by alice-telescoop** [comment]
cf #1103 ?

**Comment by mxmeunier** [comment]
> cf #1103 ?

c'est assez lié mais quand même indépendant !

**Comment by mxmeunier** [comment]
@alice-telescoop @VSerain on a déjà un truc avec les `grants`, non ? Je vois pas forcément la diff avec ce ticket

**Comment by VSerain** [comment]
Oula vaste sujet ! Je crois que Alice, voyais les grants comme sur futur format de toute l'application, ducoup j'imagine que oui @alice-telescoop ?

**Comment by alice-telescoop** [comment]
Oui j'ai conçu les grants comme ça quand j'ai fait l'open-data. Si on reste sur ma lancée il "n'y a qu'à" faire en sorte d'appliquer les adapters à ce workflow-là. En sachant que ça défait le principe du SSE vu que tous les calculs doivent être faits pour pouvoir faire les liens en amont (mais ça, ce n'est pas seulement à cause de mon implémentation)

**Comment by mxmeunier** [comment]
Plus à jour. Gros sujet à discuter en séminaire.
