### ISSUE TITLE
Se renseigner sur le fonctionnement des Refresh Token Rotation

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#548]
Se renseigner sur comment bien implémenter le refresh automatique des tokens lorsque l'utilisateur utilise l'application (afin d'éviter de le déconnecter pour rien, via le token.now).

c.f https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation

- [ ] #1289
- [ ] #1283
- [ ] #1290
- [ ] #1284 
- [ ] #1282
- [ ] #1285 
- [ ] #1286 
- [ ] #1287 
- [ ] #1288

**Comment by alice-telescoop** [comment]
# Notes sur le principe

Le principe de "Refresh Token Rotation" s'applique à l'OAuth, ou plus généralement aux systèmes dans lesquels le serveur d'authentification est différent du serveur qui contient les ressources.

# Côté API

## Flow théorique

Le flow que j'ai trouvé le + convaincant est [celui décrit par supertokens](https://supertokens.com/blog/the-best-way-to-securely-manage-user-sessions). En résumé : 
- un token d'authentification à durée de vie courte (max 2h, souvent suggéré 15 min) non stocké en base et dont la validité se calcule à partir du token (JWT)
- un token de rafraîchissement à durée de vie longue (~ une semaine) stocké en base ou pour lequel on maintient une blacklist [^1]
- à la connexion, les deux token sont générés et émis
- au rafraîchissement, le token de rafraîchissement utilisé est invalidé, et les deux tokens sont générés.

[^1]: il doit être stocké en base pour pouvoir l'invalider en cas de déconnexion manuelle ou de pb

## Un peu plus pratique

[Cet article](https://jasonwatmore.com/net-6-jwt-authentication-with-refresh-tokens-tutorial-with-example-api) précise les routes à créer. En cas de désaccord entre les deux articles, je fais + confiance au premier.

### Sur le stockage

Il était conseillé un peu partout de stocker le token de rafraîchissement en cookie `HttpOnly` et `Secure` en renseignant bien `SameSite=strict` et `Domain="mondomain.com"`[^2]. D'après [cet article] ce n'est pas parfait, mais c'est déjà bien mieux qu'en local storage.

[^2]: [doc MDN](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Set-Cookie)

### La déconnexion

Il faut penser à invalider le token de rafraîchissement au moment de la déconnexion de l'utilisateur

# Risque de race condition

Ce fonctionnement crée un risque de `race condition`, qui peut créer des alertes ou des déconnexions intempestives lorsque deux onglets différents procèdent à un rafraîchissement en même temps. Selon [ces pistes](https://stackoverflow.com/questions/56082559/stop-race-condition-of-refresh-token) il faudrait
- ou bien **en front** interrompre le rafraîchissement sur les onglets qui ne sont pas actuellement visibles ([solution technique sur axios](https://axios-http.com/docs/cancellation))
- ou bien **en back** laisser un peu de délai avant d'invalider un refresh token mais je ne suis pas convaincue du fonctionnement

# Côté front

[Cette implémentation] côté axios me paraît convaincante, en ajoutant la gestion des race condition. Dans l'idée, il faut rattraper les 401, essayer de rafraîchir le token, redemander la ressource en cas de succès et déconnecter l'utilisateur comme d'hab en cas d'échec (typiquement expiration du token de rafraîchissement).

**Comment by alice-telescoop** [comment]
@mxmeunier @VSerain 
Posez vos questions tant que ce n'est pas clair et dites-moi quand ça l'est, je ferai les tickets quand on sera au clair.

**Comment by VSerain** [comment]
Hello @alice-telescoop le fonctionement proposer me va bien ! Je pense qu'on peut faire les tickets ;)

**Comment by mxmeunier** [comment]
J'ai enfin pris le temps de lire et ça me va aussi. 

Deux questions sur leur implémentation et explications :

On peut avoir deux token d'accès valide en même temps (sur le schéma de race condition, le vert et le rouge) ?

Le token d'accès est recréé à chaque requête ? Sinon je comprend pas comment le tab1 de l'exemple récupère un token d'accès vert alors qu'il avait le rouge

**Comment by alice-telescoop** [comment]
> On peut avoir deux token d'accès valides en même temps (sur le schéma de race condition, le vert et le rouge) ?

Non, et c'est justement pour ça qu'il y a un pb de race condition. Quand il y en a deux, un des deux n'est plus valide

> Le token d'accès est recréé à chaque requête ? Sinon je comprend pas comment le tab1 de l'exemple récupère un token d'accès vert alors qu'il avait le rouge.

Le token d'accès est recréé à chaque requête **à la route de rafraîchissement** ou d'authentification mais pas pour des appels "normaux". Par contre il est ensuite partagé entre les onglets via les cookies. Donc quand tab2 récupère le token vert, ça écrase le token rouge de tab1

**Comment by mxmeunier** [comment]
Ok merci pour les clarifications.

Y'a plus qu'à !
