### ISSUE TITLE
Créer une migration pour vider la table datagouv-entreprise-siren

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#552]
La mise en place du nouveau parser nécessite que la table datagouv-entreprise-siren sois vide pour la première exécution.

Un simple `collection.drop` devrait suffire

**Comment by mxmeunier** [comment]
@VSerain peux-tu me rappeler pourquoi on doit drop cette base ?

**Comment by VSerain** [comment]
Oui, vu qu'on repart du début de l'historique, on part de zéro comme ça on est sûr qu'il n'y a pas de doublon !

**Comment by mxmeunier** [comment]
Toutes les entrées de la collection viennent des anciens import de StuckUniteLegale ?

**Comment by VSerain** [comment]
Oui
