### ISSUE TITLE
Utiliser des badges pour les statuts de demande

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#569]

**Comment by VSerain** [comment]
Hello @Gttnmarion @natoine j'ai un doute sur le fait qu'on à bien fait le travail de réunification des status, ça vous dit un truc

**Comment by VSerain** [comment]
Alors c'est sûr que ça n'a pas été implémenté ! Il me semblait que ça n'avait pas été actée

**Comment by Gttnmarion** [comment]
Le filtrage n'avait pas été validé ? On avait fait la réunion ensemble et j'ai le souvenir qu'on s'était dit OK pour les 4 filtres et qu'on allait les faire tester aux users, c'est pas le cas ?

**Comment by VSerain** [comment]
Oui, mais je ne me souviens pas que ça a été validé par les utilisateurs ! Mais peut-être que j'ai loupé un wagon

**Comment by Gttnmarion** [comment]
On attend les retours utilisateurs sur cette partie

**Comment by Gttnmarion** [comment]
https://docs.google.com/spreadsheets/d/1BKVvn3tSVomTyYXTWyN9PiL3Pyt-WSw8V2plrQYiRgQ/edit#gid=1786670237
