### ISSUE TITLE
[interface admin] données users : graphique de l'évolution des utilisateurs inscrits, faisant apparaître le nombre de nouveaux utilisateurs

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#578]

**Comment by Gttnmarion** [comment]
![Image](https://user-images.githubusercontent.com/114912799/201656872-0a1cfe68-3a7d-40df-9d05-0390ba1faff3.png)

**Comment by mxmeunier** [comment]
@Gttnmarion @natoine pour l'instant nous sommes en incapacité de déterminer de quel département viennent les utilisateurs.

**Comment by natoine** [comment]
Je crois que là département = service.
On ne sait pas exactement, y a un travail de modélisation à faire probablement, mais on peut approximer en prenant les extensions de noms de domaine pour l'instant.

**Comment by Gttnmarion** [comment]
On ne sait effectivement pas exactement mais depuis les adresses mails de certains poles on peut le savoir.
On a un sujet d'ailleurs avec les bizdev à savoir si on demanderait pas la zone géographique de nos utilisateurs

**Comment by mxmeunier** [comment]
On a besoin d'avoir la règle métier ici. Ok pour les ac-* qu'on peut à la limite lier à un département; mais il y'en a plein d'autres.

On peut se faire un point si vous voulez en discuter.

Ici la liste des domaines permis : https://github.com/betagouv/api-subventions-asso/blob/develop/packages/api/src/configurations/auth.conf.ts

**Comment by VSerain** [comment]
Pour le moment ou supprime le terme département et on le remplace par service (aka @blaba.fr)

**Comment by VSerain** [comment]
Pour ce ticket, ne rien afficher du tout à la place de département

**Comment by Gttnmarion** [comment]
Nouveau design : @mxmeunier est-ce que ça te va ?
<img width="655" alt="Capture d’écran 2022-11-29 à 15 41 33" src="https://user-images.githubusercontent.com/114912799/204559204-085ff3bf-e784-401d-878e-9b061a929fa0.png">
