### ISSUE TITLE
[interface admin] camembert de répartition des utilisateurs par la fréquence de leurs requêtes

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#582]

**Comment by mxmeunier** [comment]
@Gttnmarion @natoine on a besoin de faire un point pour s'assurer du but / algorithme derrière

**Comment by VSerain** [comment]
Le nombre d'utilisateurs ayens fait plus de X requettes en moyene sur une années

**Comment by VSerain** [comment]
Donc un utilisateur qui aurait fait 120 requêtes sur l'année, aurait en moyen par mois 10 requêtes et apparaîtra donc dans la partie <=10 par user

Si un utilisateur qui aurait fait 544 requêtes sur l'année, aurait en moyen par mois 45,33 requêtes et apparaîtra donc dans la partie > 31 par user

**Comment by VSerain** [comment]
@mxmeunier est-ce que c'est plus clair ?

**Comment by Gttnmarion** [comment]
<img width="579" alt="Capture d’écran 2022-11-29 à 16 28 23" src="https://user-images.githubusercontent.com/114912799/204571355-43837ef8-9746-4d7b-a4de-6d6262befde7.png">

**Comment by VSerain** [comment]
Exemple https://docs.google.com/spreadsheets/d/1DNtVg_uisI5_hReMyi3LUPHVFLZmSwadbqG_u3QJy4Y/edit?usp=sharing

**Comment by mxmeunier** [comment]
yes c'est précisé !

**Comment by Gttnmarion** [comment]
Je fais le lien avec un ticket design en cours ^^" suite aux retours pour la lecture du camembert 
[#690](https://github.com/betagouv/api-subventions-asso/issues/690)
