### ISSUE TITLE
[interface admin] section listant les associations les plus consultées

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#583]

**Comment by Gttnmarion** [comment]
A mettre dans la page statistiques d'usage

![Image](https://user-images.githubusercontent.com/114912799/202161970-77fb1944-1c85-4d69-96aa-32fd124efee6.png)

**Comment by mxmeunier** [comment]
@Gttnmarion pour l'affichage de la période (depuis Nov 2021) on se base bien sur les stats sur un an ?

**Comment by mxmeunier** [comment]
@Gttnmarion @natoine  On parle bien de médiane ? Quel est le calcul a opéré ici, je ne suis pas sûr de comprendre.

**Comment by Gttnmarion** [comment]
Oui, le calcul prévu ici c'est :

Sur l'année, on affiche les associations les plus consultées (on fait le total - si c'est possible - des vues sur la page asso et ses pages établissements). Peu importe qui a fait la recherche, on prend en compte le total des requêtes.

Exemple : entre nov 2021 et nov 2022, il y a eu 100 recherches pour mouvement ATD, 50 pour l'établissement siège, 50 pour l'établissement du 18e à Paris. Soit un total de 200 recherches sur l'année pour l'asso mouvement ATD

Redis moi si c'est faisable :)

**Comment by mxmeunier** [comment]
@Gttnmarion  Ce n'est donc pas une médiane mais un total de vue. Problème dans le libellé ? On devrait avoir "pages les plus consultées - depuis nov. 2021"

**Comment by VSerain** [comment]
@mxmeunier C'est bien le nombre total de vues sur une association sur la période données, donc par exemple combien de fois a été vue ATD puis un ans

**Comment by Gttnmarion** [comment]
<img width="411" alt="Capture d’écran 2022-11-29 à 16 06 02" src="https://user-images.githubusercontent.com/114912799/204565424-2b93588f-75d8-4909-9669-ec7d257780df.png">

**Comment by VSerain** [comment]
Règle :
On contablise une vue quand un utilisateur requeter une fois ou plus sur 24h soit la d'une page asso X ou/et une des pages établissements liée à l'asso X

```
var log = getLogsByYear()

const logByAssos = agregate log par RNA/SIREN(SIRET)

logByAssos.foreach(logbyAsso => {
   var logByUsers = filtre des logs par utilisateurs
 // pour chaque user je cherche à savoir le nombre ou l'uttiisateur a vu la page dans la meme journée
  const nbViewAssoInYear = logByUsers.reduce(total, logByUser => {
   logsByDay = logByUser.reduce((acc, log) => {
         if (!acc[log.date.day]) acc[log.date.day] = [];
         acc[log.date.day].push(log);
         return acc;
     }, {})
    retrun total + Object.values(logsByDay).length // Ici on n'a le nombre des jours ou l'utilisateur à vu l'asso X
  })
  
   
})
```

**Comment by VSerain** [comment]
@mxmeunier je veux bien que tu me disent si le bout de code te semble claire

**Comment by VSerain** [comment]
@alice-telescoop vu que tu à l'air d'etre plus douée que nous en math si tu veux jeter un oeil aussi ;)

**Comment by alice-telescoop** [comment]
Je suis convaincue que c'est juste. Ça fait effectivement un total et pas une médiane. Je ne me sens pas très sûre de moi pour avoir un avis de ce qui serait plus pertinent entre médiane et totale.
Par contre j'ai clairement eu besoin de qques minutes avec mon papier et mon crayon pour être convaincue que c'était juste, donc je ne suis pas sûre que ce soit clair.
Je pense que j'aurais transformé tous les logs en qqchose de la forme `{user, dateNoTime, assoName}`, j'aurais mis tout ça dans un Set qui aurait retiré les doublons et pris la taille du Set.
Petit doute quand même, les logs qu'on a au début du calcul c'est bien les logs pour une association *et* ses établissements ? Si non, ça ne correspond pas à le demande plus haut :
> on fait le total - si c'est possible - des vues sur la page asso et ses pages établissements

**Comment by VSerain** [comment]
Hello !
Oui, c'est du faux pseudo code ! Il ne marchera pas tel quelle ! C'est plus pour données une idée du fonctionnement voulu ! 
Sur le dernier point oui, je suis partie du principe qu'on avait le nom de l'asso dans le log (que ça soit une recherche par établissement ou bien par asso), ce qui n'est pas le cas dans la realitée !

Très bonne idée pour le Set, de mémoire, il vérifie la stricte égalité, donc en JS la réf, ce qui ne marchera pas, car on créera sûrement un obj pour chaque log et donc même si les deux obj on la même "valeur" ils n'auront pas la même ref !

**Comment by VSerain** [comment]
Ou, ou alors, on transforme la clé en string, genre 'user-dateNoTime-assoName' et dans ce cas la le set doit fonctionner !

**Comment by VSerain** [comment]
L'algo d'Alice est mieux ! Message au dev qui prendra ce ticket : Faire avec le Set :)

**Comment by mxmeunier** [comment]
@VSerain ça me va même si à 8h ça pique les yeux. Par contre je ne vois pas de Set dans le pseudo code en haut, alors que tu fais référence à l'algo de @alice-telescoop ? C'est juste une référence au fait qu'elle ait proposé l'utilisation d'un Set on est d'accord ? Ou alors il me manque un lien vers son pseudo. :)

**Comment by VSerain** [comment]
Oui pardons, juste la ref au set pas de pseudo code, mais je peut le faire si besoin ;)
