### ISSUE TITLE
[Page Statistiques] Carte de France avec toutes les demandes de subvention par région

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#591]

**Comment by Gttnmarion** [comment]
![Image](https://user-images.githubusercontent.com/114912799/201886771-b1bb7706-e94e-4408-86e1-38eb63effa74.png)

**Comment by Gttnmarion** [comment]
Voir avec outil Matomo si on peut récupérer donner géoloc.
Via noms de domaines (qu'est-ce qu'on peut relier)

**Comment by mxmeunier** [comment]
STUCK DEV: en attente de la carte via le DSFR

**Comment by mxmeunier** [comment]
@Gttnmarion on est d'accord c'est à mettre en "Need Information" ?

**Comment by Gttnmarion** [comment]
> @Gttnmarion on est d'accord c'est à mettre en "Need Information" ?

Yes ! Car je dois voir quelle carte utiliser pour qu'on ait bien tous les départements + DOM TOM
