### ISSUE TITLE
[Page Statistiques] graphique de la répartition mensuelle des demandes de subvention

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#592]

**Comment by Gttnmarion** [comment]
![Image](https://user-images.githubusercontent.com/114912799/201887178-1e915b3a-8dcc-4f83-8183-48b855607b99.png)

**Comment by mxmeunier** [comment]
@Gttnmarion on ne liste que les subventions accordées ?

**Comment by Gttnmarion** [comment]
> @Gttnmarion on ne liste que les subventions accordées ?

Hello ! j'avais listé toutes les demandes de subventions, peu importe le statut.
