### ISSUE TITLE
[interface admin] camembert de répartition des utilisateurs en inscrits et non actifs, et admin

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#593]

**Comment by Gttnmarion** [comment]
![Image](https://user-images.githubusercontent.com/114912799/201887480-eef62d4a-6699-430b-a487-b22b4aa13ac9.png)

**Comment by mxmeunier** [comment]
@Gttnmarion @natoine 
Récapitulatif des 3 champs :

1. Utilisateurs inscrits et actif
2. Utilisateurs inscrits mais sans activité depuis 7j ?
   Est-ce que c'est compte actif (fait des recherches) ou simplement qui a finalisé son inscription ?
4. Admins

**Comment by natoine** [comment]
Actif = qui a fait au moins une recherche dans les 7 derniers jours

**Comment by Gttnmarion** [comment]
1. ce sont bien les utilisateurs inscrits et actifs 
2. ce sont les users inscrits mais qui n'ont pas utilisé la solution pendant plus de 7 j
3. admins

(il n'y a plus dans le camembert ceux qui n'ont pas finalisé leur inscription

**Comment by mxmeunier** [comment]
super merci pour vos retours
