### ISSUE TITLE
Création de la homepage

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#614]

**Comment by Gttnmarion** [comment]
@VSerain @mxmeunier 

Pour les métriques on a besoin de ces différentes infos :
- nombre d'utilisateurs
- services ministériels soit les différentes extensions mails à récupérer
- Nombre de dispositifs de subventions
- Et le montant des versements 

Est-ce qu'on a bien une route pour chacune de ces infos ?

**Comment by Gttnmarion** [comment]
![Image](https://user-images.githubusercontent.com/114912799/204837553-08fe91bf-8296-4523-973b-4f9a473db8c2.png)

**Comment by mxmeunier** [comment]
Alors :
- Nombre d'utilisateur : on remonte déjà la liste côté admin donc on peut récupérer le nombre facilement
- Service ministériels : on a pleins d'extensions qui ne sont pas liées à un "service ministériel" donc à définir @natoine.
Par exemple tous les domaines en ac-* ou region-academique-* ?
- Nombre de dispositifs de subventions : késako @Gttnmarion @natoine ? Je ne suis pas sûr de comprendre où trouver la donnée
- Nombre (et non pas montant comme mentionné ?) de versements : @VSerain vu qu'on a pas tout en base locale, impossible de calculer le nombre de versements qu'on "traite/affiche" ?

**Comment by VSerain** [comment]
Hello, c'est fou je pensais avoir repondu !
On a tous les versements chorus ! Donc si on change le libellé ça peut le faire ! Par contre, la partie Jaune, on a n'a pas, ça veut dire créer un parser et stocker tout ça en base, ça me semble un peu over-kill juste pour afficher un chiffre !

**Comment by mxmeunier** [comment]
Ok @VSerain donc au final on a tous les versements en base (en comptant également FONJEP). Est-ce qu'il y a d'autres sources de versements non connectés à Data.Subvention que Chorus et FONJEP @natoine  ?

**Comment by VSerain** [comment]
Il y à d'autres outils tels que SIREPA que l'ont à pas !

**Comment by natoine** [comment]
Service ministériels : on a pleins d'extensions qui ne sont pas liées à un "service ministériel" donc à définir @natoine.
Par exemple tous les domaines en ac-* ou region-academique-* ?
Pour l'instant on approxime en mettant le nombre d'extensions que l'on a différentes.
Après il va y avoir un chantier avec les bizdev de modéliser la hierarchie ministères / services / agences / collectivités et lier nos utilisateurs aux bonnes administrations ... ça va nous servir en déploiement de mieux comprendre qui est dans quel service. 
L'enregistrement en base de cette information se fera bientôt via du déclaratif dans un formulaire d'inscription plus fourni.

**Comment by natoine** [comment]
Nombre de dispositifs de subventions : késako @Gttnmarion @natoine ? Je ne suis pas sûr de comprendre où trouver la donnée

C'est censé être les dispositifs d'aide proposés par les différentes administrations : genre le FONJEP c'est un dispositif.

**Comment by mxmeunier** [comment]
Dispositif = type d'aide ? Il faut créer une liste des dispositifs recencé dans l'outil mais je vois pas. Surtout avec le chiffre  de 11308 donné en exemple. @VSerain tu vois toi ?

**Comment by Gttnmarion** [comment]
@mxmeunier @VSerain @natoine pour exemple de dispositifs on a la colonne dans le tableau de bord à ce sujet, le chiffre est fictif pour le moment (j'avais laissé 11 000 car je pensais mettre au début le nombre de dossiers de sub qu'on a).

**Comment by VSerain** [comment]
@mxmeunier c'est bien ce qu'affiche Marion, on a un attribut dispositif dans chaque demande de sub

**Comment by VSerain** [comment]
En résumer pour moi, on peut le faire, mais il y a encore de coin sombre à éclairer (aka: les services ministériel)
