### ISSUE TITLE
[Tableau de données - dashboard] utiliser des badges pour les statuts de demande

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#615]
stuck by ticket api #1045
cf #569

**Comment by VSerain** [comment]
#569

**Comment by VSerain** [comment]
Stuck tans que l'on aura pas unifié les status des demandes de subvention

**Comment by VSerain** [comment]
Voir figma V0.4
![image](https://user-images.githubusercontent.com/22598814/209972422-0004eddd-ca14-47d3-9f6e-b288b555016e.png)

**Comment by alice-telescoop** [comment]
https://docs.google.com/spreadsheets/d/1BKVvn3tSVomTyYXTWyN9PiL3Pyt-WSw8V2plrQYiRgQ/edit#gid=1786670237

**Comment by alice-telescoop** [comment]
faire attention à remplacer tous les `versement.status` par `statut_label` ou `statut_provider`

**Comment by alice-telescoop** [comment]
Oui et non : c'est normal parce que le changement de backlog-status n'est pas automatisé. Non parce que le truc est de facto terminé. Dans notre process on peut toujours passer une carte qui a un statut de sprint terminé à un backlog-status Done
