### ISSUE TITLE
Widget évolution des utilisateurs inscrits

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#661]
c.f #578

**Comment by mxmeunier** [comment]
stuck by #667 et #669

**Comment by alice-telescoop** [comment]
@mxmeunier @VSerain zut, pour le ticket API on n'a pas pensé au "+105" qui demande d'envoyer aussi la valeur au début de l'année. Si on fait juste "décembre - janvier" ça ne compte pas les nouveaux utilisateurs de janvier. 
Je fais 
- quand même le graphique avec cette "fausse" valeur  

ou 
- je laisse de côté et je fais un ticket rectificatif côté API ?

**Comment by VSerain** [comment]
Tu fait le premier point ! Et tu créer un ticket correctif qu'on prendra plus tard ! En règle générale, on préfère sortie un truc pas parfait, mais qu'on améliore, plutôt que d'attendre que ça sois parfait ! ;)
