### ISSUE TITLE
Créer une page 404 dans svelte

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#664]
Créer une page 404.

Créer un composant ContactButton si pas déjà fait avec en action un `mailto:contact@datasubvention.beta.gouv.fr`

LINK TO: #691

**Comment by Gttnmarion** [comment]
> @natoine à envisager un design avec @Gttnmarion ?

Ce serait pas mal en effet ! J'ajoute un ticket design @natoine
