### ISSUE TITLE
Trouver une librairie de graphique

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#667]
Travail de veille sur ce qui existe pour intégrer des graphique 2D dans une application web.

Pistes: D3.js, chart.js

**Comment by Gttnmarion** [comment]
D3.JS :
https://observablehq.com/@d3/gallery

**Comment by mxmeunier** [comment]
D3.js est très complexe et nécessite trop de temps pour de simples camemberts et graphiques en bar. Après investigation mon choix se penche vers Chart.js qui a une bonne communauté, facile à prendre en main, design simple et élégant. Il est également bien plus utilisé récemment d'après [npm trend](https://npmtrends.com/c3-vs-chart.js-vs-chartist)

**Comment by mxmeunier** [comment]
@alice-telescoop @VSerain faites moi savoir si ça vous va.

J'ai comparé [C3.js](https://c3js.org), [Chart.js](https://www.chartjs.org) et [Chartist](https://gionkunz.github.io/chartist-js/).

Ce que j'en retient : 
- C3 prise en main facile mais pas beaucoup de personnalisation des graphiques
- Chartiste très léger et permet de belles animations sur les graphiques (mais on en a pas besoin)
- Chart.js assez léger, utilise des Canvas HTML et à priori permet de personnalisé les graphiques (notamment de coloré en dessous des lignes des graphiques par exemple).

De ce que j'ai vu les dernières versions de ces 3 librairies ne supportent plus Internet Explorer. @Gttnmarion un problème ?

**Comment by alice-telescoop** [comment]
Effectivement je trouve que C3.js c'est visuellement un peu trop austère. Je suis personnellement intriguée par le fait que chartiste marche avec des svg ça doit être plus léger, mais c'est clair que Chart.js est plus utilisé et semble faire référence donc 👍

**Comment by mxmeunier** [comment]
Chart.js mis à jour sur develop. Je viens de me rendre compte qu'on l'utilise déjà dans la partie admin.
