### ISSUE TITLE
Remonter les associations les plus consultées

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#668]
1. Agrégation les id (SIREN, RNA) de toutes les association liées aux requêtes vers /association/:id et l'ancienne route /search/association/:id
2. Récupérer le nom associé à l'id via le service associationName.
3. Sauvegarder en cache le lien nom - siren - rna (pour limiter le nombre de recherche en bas)
4. Créer une tableau Map par nom d'association qui contiendra un nombre de consultation
5. Incrémenter ce nombre pour chaque élément dans le tableau d'agrégation.
6. Créer la ressource /stats/associations prenant une query limit par défaut à 5 afin de définir le nombre de retour.

**Comment by mxmeunier** [comment]
@natoine on exclu bien les requêtes admin dans toutes les stats ?

**Comment by alice-telescoop** [comment]
- 1.2.3 -> seulement une migration ?
- Possibilité de doublon de nom d'asso ?
- 3. cache -> une collection ou DataCache ? Comment marche DataCache ?
- 4. C'est bien une collection plutôt qu'un tableau ?

**Comment by mxmeunier** [comment]
@alice-telescoop le but ici est de récupérer à partir des logs la liste des associations les plus visitées.

1 - on a modifié les ressources passant de /search/association/:id à /association/:id donc il faut regrouper les deux en 1
2 - utiliser la collection associationName pour retrouver les noms
3 - la phrase est pas top mais c'est juste utiliser un cache temporaire le temps de récupérer toutes les infos qui retient le nom associé à un siren/rna pour ne pas appeler inutilement la collection associationName pour chaque ligne de log
4 - créer un object Map avec comme clé le nom d'une asso et comme valeur le nombre de recherche 
5 - peupler cette collection en parcourant les logs remontés
6 -créer la ressource http pour récupérer le résultat

**Comment by mxmeunier** [comment]
Finalement c'est sur les 12 derniers mois donc modifier la requête pour prendre une période. Trouver une astuce pour garder le résultat en base pour pas refaire le calcul à chaque fois

**Comment by alice-telescoop** [comment]
Question : comment ça se passe quand une asso change de nom ? Pour l'instant je stockais le nom mais je pense que c'est une mauvaise idée en cas de changement de nom justement. Une objection à ce que dans la collection `association-visits` on se repère plutôt avec les identifiants rna et siren ? @VSerain @mxmeunier ?

**Comment by alice-telescoop** [comment]
> Finalement c'est sur les 12 derniers mois donc modifier la requête pour prendre une période. Trouver une astuce pour garder le résultat en base pour pas refaire le calcul à chaque fois

Fait

**Comment by VSerain** [comment]
> Question : comment ça se passe quand une asso change de nom ? Pour l'instant je stockais le nom mais je pense que c'est une mauvaise idée en cas de changement de nom justement. Une objection à ce que dans la collection `association-visits` on se repère plutôt avec les identifiants rna et siren ? @VSerain @mxmeunier ?

Si un asso change de nom alors, on rajoute une entrée dans la table association name ! Donc oui, il faut mieux se baser sur un identifiant unique ! 
Avec une préférence pour le siren (car tu peux aussi gérer les établissements comme ça, vu que siret = siren + code nic) ! 
Attention cependant toutes les assos n'ont pas de siren, comme tous les assos non pas forcément bien déclarer leur rna à l'Insee

**Comment by VSerain** [comment]
C'est pour ça que dans le code d'association name, on passe par des ref pour les tableaux !

**Comment by VSerain** [comment]
@alice-telescoop est-ce que tu en profite pour faire #771 ? Savoir si on peut supprimer le ticket ?

**Comment by alice-telescoop** [comment]
> est-ce que tu en profite pour faire #771 ? Savoir si on peut supprimer le ticket ?

Euh c'est bizarre comme question. C'est censé être un épique avec plein de sous-tickets

**Comment by VSerain** [comment]
> > est-ce que tu en profite pour faire #771 ? Savoir si on peut supprimer le ticket ?
> 
> Euh c'est bizarre comme question. C'est censé être un épique avec plein de sous-tickets

J'aurai dit que non c'est un seul ticket, ou le but est de créer une route HTTP qui retrounes une liste des assos les plus consultées !   
Et que pour comptabiliser les assos le plus vu on prend également en compte les vues sur les pages établissement, le 771 a été créé pour rajouter les établissements dans le calcul, car ta dernière PR (celle avec mongo 5) ne les prenait pas en compte !   
Ma question, c'était juste, est-ce que dans ton nouveau dev, tu prends en compte les établissements ? Si oui plus besoin de 771 si non, on laisse le ticket.

**Comment by alice-telescoop** [comment]
J'ai confondu avec #761, trop d'onglets ouverts. Oui je peux prendre 771
