### ISSUE TITLE
Subvention absente lorsqu'on filtre sur l'établissement

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#672]
Page concernée : Association - Tableau de Bord

Association concernée : Amical du Nid ADN (W751187667)

Subvention concernée : 7 500€ en 2021 (par Chorus)

Problème : la subvention apparaît lorsque l'on filtre sur siège + établissements mais pas sur l'établissement concerné (filtre sur l'établissement siège, à Paris)

**Comment by VSerain** [comment]
C'est parce qu'il n'est pas lier au siège, mais à cette établissement : 77572367900418
Qui semble être fermer donc c'est peut-être l'ancien siège

**Comment by mxmeunier** [comment]
@AlixBouillon

**Comment by VSerain** [comment]
Pour moi on peut close
