### ISSUE TITLE
Retourner la répartition des utilisateurs par nombre de requêtes

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#676]
Créer une ressource /stats/users-by-request

Retourner le nombre d'utilisateurs par borne :
- = 0 requêtes par mois en moyenne sur l'année 
- de 1 à 10 requêtes par mois en moyenne sur l'année
- de 11 à 20 requêtes par mois en moyenne sur l'année
- de 21 à 30 requêtes par mois en moyenne sur l'année
- \>= 31 requêtes par mois en moyenne sur l'année

Toujours faire les moyennes par mois sur un an. Donner en paramètre les bornes (donc ici [0, 10, 20, 30]).

L'objet retourné comprendra également une date de début et de fin de période (comme novembre 2021 sur l'image)

```
{
    startPeriod: ...,
    endPeriod: ...,
    ":0": ...,
    "1:10": ...,
    "11:20": ...,
    "21:30": ...,
    "31:": ...
}
```

Se renseigner sur les bonnes pratiques de retour de tableaux "bornés"

**Comment by mxmeunier** [comment]
c.f #660

**Comment by alice-telescoop** [comment]
J'allais prendre ça mais je ne suis pas au clair sur ce qu'on compte comme des requêtes différentes. Si on veut ne compter qu'une fois deux appels à une même asso le même jour par un même utilisateur, comment se gère le cas où les deux appels ont été faits avec des identifiants différents ?
Dans le doute je ne le prends pas pour essayer d'avancer vite avant le début de la semaine pro, mais à préciser

**Comment by VSerain** [comment]
Alors, je dirait qu'on ce base toujours sur nos point d'entrée habituelles !
C'est à dire /association/ID /etablissement/ID /search/association /search/etablissement

Ensuite une vue sur un établissement != une vue sur sont associations
Pour ce qui est du RNA vs SIREN en premiers lieux je dirais on ne gérer pas !
Et on fait un point avec les BizDev sur ce sujet !

**Comment by alice-telescoop** [comment]
Le point avec les bizdev est déjà prévu ? Si non, pas clair qu'on puisse faire le ticket ce sprint. Ou on avance quitte à modifier, mais j'ai peur que ce soit un peu lourd

**Comment by VSerain** [comment]
;) https://mattermost.incubateur.net/betagouv/pl/znpnm5pzgfrm5g698kan3orfhw

**Comment by alice-telescoop** [comment]
Ah oui, je lis pas du tout le canal bizdev sur mattermost si je n'y suis pas taggée ><
