### ISSUE TITLE
Uniformiser le téléchargement des documents

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#677]
Trouver une solution pour uniformiser le téléchargement des documents.

SOIT forcer le téléchargement directe
OU l'ouverture dans un nouvel onglet 

Investiguer sur les deux possibilités

**Comment by mxmeunier** [comment]
Compte rendu d'une première investigation :

J'ai essayé de détourner le problème en téléchargeant les fichiers dans l'app avant de rediriger vers un téléchargement. C'est impossible à cause des problèmes de CORS liés aux serveurs détenant les fichiers.

J'ai également essayé `window.open()` plutôt que l'attribut `target` mais ça rend la même chose à la différence que pour les fichiers LCA vide, au lieu de DL un fichier vide corrompu avec un message d'erreur à l'ouverture (genre "fichier vide") et bien ça ouvre une page avec un message XML indiquant qu'il n'y a pas de ressource à l'url indiquée...

Affaire à suivre. @alice-telescoop @VSerain je vous laisse me relire et faire plus d'investigation si vous le voulez mais moi je fais une pause !

**Comment by mxmeunier** [comment]
STUCK: lire plus haut, je n'ai pas trouvé de solution

**Comment by alice-telescoop** [comment]
Pour y réfléchir efficacement il faudrait que j'ai un exemple de chacune des situations pour expérimenter un peu
