### ISSUE TITLE
Première mise en place d'un cron sur la plateforme

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#684]
Se renseigner sur la mise en place de CRON sur Scalingo (voir la documentation).

Faire l'état de l'art en commentaire ou programmer une réunion pour faire un choix.

---
### Edit
Après réflexion, on a décidé d'utiliser les cron node (Voir quels packages on choisit), car cela permet moins de dépendance à Scalingo.

Le but du ticket est de choisir le bon package et de mettre en place une première tâche bidon (style `console.log("hello world")`, pour montrer l'exemple.

Coté Archi, on propose de faire des `CronController` dans les dossiers interfaces de chaque module ayant besoin d'un cron.
Tous les controllers cron seront chargés dans un fichier `cron.ts` (qui se trouve à la racine avec `cli.ts`), qui aura pour job de les "charger".

Ce fichier doit soit être appelé et initialiser via `server.ts`, soit via un worker séparé (voir scalingo worker). Ce choix est à votre discrétion ainsi que le choix du package.

Bien documenter tous les fonctionnements (worker ou `server.ts`, récupération des contrôleurs cron , exécution, ...)

**Comment by VSerain** [comment]
https://scalingo.com/fr/blog/scalingo-scheduler
https://doc.scalingo.com/platform/app/task-scheduling/custom-clock-processes

**Comment by alice-telescoop** [comment]
ou directement dans node : 
https://www.npmjs.com/package/node-schedule
https://github.com/kibertoad/toad-scheduler

**Comment by VSerain** [comment]
> ou directement dans node : https://www.npmjs.com/package/node-schedule https://github.com/kibertoad/toad-scheduler

Oui bonne idée, voir ce qui est le mieux

**Comment by mxmeunier** [comment]
ça dépend de la fréquence non ? utiliser un cron node pour du traitement 1x par jour c'est pas overkill ?
si scalingo propose de programmer l'exécution de script c'est peut-être plus "opti" ?
