### ISSUE TITLE
Créer une page 404 dans svelte #664

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#691]

**Comment by alice-telescoop** [comment]
Il existe des pages dans le DSFR : https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles-et-blocs-fonctionnels/modeles-de-page-d-erreur

**Comment by Gttnmarion** [comment]
Page d'erreur dispo dans le Figma :)
https://www.figma.com/file/t6nWdBwKr8fancez3VO5kr/Data.Subvention-V0.4?node-id=9474%3A118899&t=Xi29PCpu7OnYN8vW-1

![Image](https://user-images.githubusercontent.com/114912799/210410231-13be1c37-3cbe-4d64-968b-58501e2d540e.png)
