### ISSUE TITLE
Modale : Provenance et date de dernière mise à jour

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#697]

**Comment by Gttnmarion** [comment]
Pour chaque ligne dans le tableau des financement : dans partie gauche, je veux savoir d'où ça vient
partie droite : je veux savoir d'ou ça vient

**Comment by Gttnmarion** [comment]
![Image](https://user-images.githubusercontent.com/114912799/207873002-85762af8-43e1-4843-b929-6fa4a4eb5c97.png)

**Comment by mxmeunier** [comment]
@Gttnmarion est-ce qu'on peut mutualiser la partie "Établissement concerné" avec le contenu des cartes Établissement ?

![Capture d’écran 2023-01-10 à 11 26 48](https://user-images.githubusercontent.com/7630775/211526522-1acc0548-c31b-4068-9ccf-4dc258c08afe.png)

**Comment by Gttnmarion** [comment]
Mutualiser quelles infos ?
Sur les infos qu'on a ci-dessous + ce qu'on trouve dans la carte ? 

<img width="672" alt="Capture d’écran 2023-01-10 à 11 34 52" src="https://user-images.githubusercontent.com/114912799/211528865-ac0692e9-b45d-4f67-a8ac-2609778d7e30.png">

**Comment by mxmeunier** [comment]
Non, les informations (et donc le design / alignement) de la carte établissement mis en photo au dessus et la partie "établissement concerné" de la modale
