### ISSUE TITLE
Améliorer la gestion du token utilisateur

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#716]
La propriété user.jwt contient un token et un date d'expiration.

Cette dernière est inutile et redondante avec le token.now et doit être supprimer. La propriété jwt ne contiendra plus que le token, il faut donc remonter directement le token dans l'objet user.

Bien prendre en compte cette modification dans le front et déconnecter tous les utilisateurs (supprimer tout ce qui est dans collection sessions_front).

Bien utiliser le code HTTP 401 en cas de déconnexion.

Supprimer également la méthode refrechExpirationToken() et son utilisation dans expressAuthentication()

EDIT:

- Modifier le DBO en supprimant expirationDate et déplacer la propriété jwt.token directement dans jwt.
- Mettre à jour dans le UserService `jwt.token = token` en `jwt = token`.
- Modifier toutes les occurrences de jwt.token en jwt.

**Comment by mxmeunier** [comment]
Voir aussi #548 et

**Comment by mxmeunier** [comment]
@VSerain j'ai remarqué qu'on utilisait pas la constante now créée dans le processus de création du token et qui était supposer remplacer user.jwt.expirateDate

**Comment by mxmeunier** [comment]
un peu flou à redéfinir avec toi @VSerain

**Comment by VSerain** [comment]
On vois ça en point tickets ?

**Comment by alice-telescoop** [comment]
duplicate de la série de tickets découlant de #548 ?

**Comment by VSerain** [comment]
Oui, ça dégage
