### ISSUE TITLE
Action de téléchargement données d'un graphique

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#736]

**Comment by Gttnmarion** [comment]
Action d'un bouton de téléchargement de fichier dans le graphique qu'on importera

![Image](https://user-images.githubusercontent.com/114912799/207638568-02ad6abf-ff70-4f20-984a-fe1e31e4a67c.png)

**Comment by Gttnmarion** [comment]
Par quel outil on développe les graphiques ? Pour savoir si un bouton de téléchargement est déjà prévu dans l'outil ou non

**Comment by mxmeunier** [comment]
@Gttnmarion en stand-by tant que la plupart des graphiques ne seront pas sortis ?
