### ISSUE TITLE
Outil de test d'API

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#742]
Avec l'arrivée d'Alice on dépasse les 3 membres gratuit de Postman.

Est-ce qu'on souhaite continuer à utiliser Postman ? Est-ce qu'il existe des alternatives gratuites pour 4-5 membres ?

**Comment by mxmeunier** [comment]
@VSerain @alice-telescoop qu'en pensez-vous ?

**Comment by VSerain** [comment]
Soit, on passe à insomnia, mais je crois que c'est aussi payent ! Si non ça fait partie des outils que la startup doit nous fournire donc on peut passer sur une version payent
