### ISSUE TITLE
Supprimer la configuration locale des noms de domaine d'e-mail

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#744]
On copie la liste dans la migration et on met à jour cette dernière.

**Comment by alice-telescoop** [comment]
Si on supprime ça, ça casse la migration qui les ajoute en base. Donc si on veut re-déployer de zéro et donc faire toutes les migrations, ça casserait. Je sais pas comment gérer ça :shrug:

**Comment by VSerain** [comment]
> Si on supprime ça, ça casse la migration qui les ajoute en base. Donc si on veut re-déployer de zéro et donc faire toutes les migrations, ça casserait. Je sais pas comment gérer ça shrug

Je pense qu'on doit supprimer la configuration en local et déplacer la valeur dans la migration pour garder son fonctionnement intact

**Comment by VSerain** [comment]
A rediscuter
