### ISSUE TITLE
Gérer les erreurs HTTP avec ErrorMiddleware dans EtablissementController

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#765]
link to #761

**Comment by alice-telescoop** [comment]
@mxmeunier attends peut-être que la PR linter passe vraiment parce que pour une refacto les conflits risquent de faire mal

**Comment by mxmeunier** [comment]
@alice-telescoop elle est pas "vraiment passée" ? :o

**Comment by alice-telescoop** [comment]
Maintenant oui mais j'ai écrit le message quand je me battais avec les tests. C'est bon maintenant
