### ISSUE TITLE
Revoir admin : permettre de voir les extensions autorisées (+ ajoutées)

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#790]

**Comment by Gttnmarion** [comment]
Ce ticket est déjà fait / intégré sur la preprod : https://front-datasubvention-preprod.osc-secnum-fr1.scalingo.io/admin/users/list

@VSerain 

![Image](https://user-images.githubusercontent.com/114912799/214619675-d378d56c-2d5e-4378-a158-e2a4df57f201.png)

**Comment by VSerain** [comment]
@Gttnmarion oui mais pas fini, on a pas dev les modal
