### ISSUE TITLE
Incorporer la page ResetPwd en tant que première étape de l'activation du compte

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#793]
Créer un composant PasswordForm.svelte qui sera partagé avec le formulaire de mot de passe oublié.

stuck by #937 pour l'interface à respecter

Figma 0.4

**Comment by VSerain** [comment]
![Image](https://user-images.githubusercontent.com/22598814/209969781-13f339c4-e98d-4e25-9205-85e3a59ab3a7.png)

**Comment by VSerain** [comment]
@Gttnmarion
Hello, est-ce que tu as pris en compte dans ton design que c'était le même formulaire que pour mots de passe oublié ?
Comment fait on pour la partie mdp oublier

**Comment by Gttnmarion** [comment]
Hello ! Pour mdp oublié je dois vous faire la page en maquette mais ce sera un form charté comme par exemple là : https://aides-territoires.beta.gouv.fr/comptes/demande-nouveau-mot-de-passe/

**Comment by mxmeunier** [comment]
Update : c'est en fait la première étape de **l'activation du compte**

**Comment by mxmeunier** [comment]
> Je pense que vous pouvez reprendre le code. La structure sera la même que aides territoires. Tu as besoin que je fasse une maquette pour que tu aies le parcours ?

non c'est bon surtout si c'est bien un email qui redirige vers la même pas de création de mdp
