### ISSUE TITLE
Widget de répartition des utilisateurs

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#798]
Supprimer l'ancien graphique de répartition des utilisateurs (page gestion des comptes utilisateurs).

Créer le nouveau widget et l'ajouter dans l'onglet "Données utilisateurs".

STUCK BY: [745](https://github.com/betagouv/api-subventions-asso/issues/745) + #661 (pour éviter de devoir réinventer la roue) 
LINK TO: #593

**Comment by VSerain** [comment]
Figma v0.4 

![Image](https://user-images.githubusercontent.com/22598814/209971435-9f92c0d7-9eeb-47c2-91d7-ea6c1c9a9327.png)

**Comment by VSerain** [comment]
> L'ancien widget se basait sur la liste des utilisateurs qui était chargée par ailleurs sur la page. Je pense qu'il faudrait une route api pour ne pas avoir à charger tous les utilisateurs et les compter sur le front alors que le reste de la page n'a pas grand chose à voir @VSerain @mxmeunier qu'en pensez-vous ?

Oui ! Fait un ticket + PR séparement !

**Comment by alice-telescoop** [comment]
Euh... du coup le nouveau ticket stuckerait ce ticket-ci donc j'ai pas compris ce que tu suggères

**Comment by VSerain** [comment]
> Euh... du coup le nouveau ticket stuckerait ce ticket-ci donc j'ai pas compris ce que tu suggères

Oui c'est ça ! Tu passe celui-ci en stuck ! Et tu créer un nouveau ticket pour l'api, que tu mets dans le sprint en cours

**Comment by VSerain** [comment]
Je prefaire qu'on face des petites PR

**Comment by alice-telescoop** [comment]
stuck by #850
