### ISSUE TITLE
Afficher la repartition geographique des utilisateurs

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#799]
stuck by #794

**Comment by VSerain** [comment]
figma V0.4

![Image](https://user-images.githubusercontent.com/22598814/209971530-be44379d-4ed8-44b9-8de1-573d12784903.png)

Afficher le widget en gris sans données

**Comment by VSerain** [comment]
@mxmeunier faut qu'on reparle

**Comment by mxmeunier** [comment]
> @mxmeunier faut qu'on reparle

On sait quand le DSFR fournira une carte de France ?
