### ISSUE TITLE
Typo dans le spinner de la page asso

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#821]
![Image](https://user-images.githubusercontent.com/22598814/210742766-0fca0fa6-b52c-4397-8c24-2ec029a02920.png)

**Comment by VSerain** [comment]
![Image](https://user-images.githubusercontent.com/22598814/212030628-16fcfcd7-3cb2-4477-9b60-0af9818ba8f1.png)

**Comment by VSerain** [comment]
Nous sommes désolés, nous n'avons trouvé aucune donnée pour cette établissement pour la page établissement

**Comment by alice-telescoop** [comment]
Le commentaire ne reprend pas la description donc c'est pas clair à quoi sert le ticket
