### ISSUE TITLE
Sendinblue : création de template

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#843]

**Comment by Gttnmarion** [comment]
https://my.sendinblue.com/camp/template/55/message-setup/app-smtp

https://my.sendinblue.com/camp/template/74/message-setup/app-smtp

**Comment by Gttnmarion** [comment]
OK 

![Image](https://user-images.githubusercontent.com/114912799/223096623-04ea5faf-5449-4759-ad2d-1f3406f781be.png)

**Comment by Gttnmarion** [comment]
![Image](https://user-images.githubusercontent.com/114912799/223101311-5b52325e-21f1-493a-9772-bcfda2c5d107.png)

**Comment by Gttnmarion** [comment]
@VSerain @alice-telescoop @mxmeunier @natoine j'ai modifié le template sendinblue, j'ai deux questions :) :
- pour les liens est-ce qu'ils s'activent automatiquement quand on fait une demande de mot de passe / activation compte ?
- pour les textes entre parenthèses dans le bouton, "Lien avec Token" et "LIENDUMOTDEPASSE" est-ce que je peux les retirer visuellement ?

**Comment by alice-telescoop** [comment]
> @VSerain @alice-telescoop @mxmeunier @natoine j'ai modifié le template sendinblue, j'ai deux questions :) :
> 
>     * pour les liens est-ce qu'ils s'activent automatiquement quand on fait une demande de mot de passe / activation compte ?
> 
>     * pour les textes entre parenthèses dans le bouton, "Lien avec Token" et "LIENDUMOTDEPASSE" est-ce que je peux les retirer visuellement ?

Je ne comprends pas bien la première question. Pour la 2e je dirais oui, pas de contrainte technique à ce que ça n'apparaisse pas visuellement

**Comment by Gttnmarion** [comment]
> > @VSerain @alice-telescoop @mxmeunier @natoine j'ai modifié le template sendinblue, j'ai deux questions :) :
> > ```
> > * pour les liens est-ce qu'ils s'activent automatiquement quand on fait une demande de mot de passe / activation compte ?
> > 
> > * pour les textes entre parenthèses dans le bouton, "Lien avec Token" et "LIENDUMOTDEPASSE" est-ce que je peux les retirer visuellement ?
> > ```
> 
> Je ne comprends pas bien la première question. Pour la 2e je dirais oui, pas de contrainte technique à ce que ça n'apparaisse pas visuellement

Pour mon point n°1, je me demande si : "quand je clique sur modifier votre mot de passe, quel est le lien relié à cette action ?" car actuellement dans le template ce bouton ne contient aucun lien
