### ISSUE TITLE
Créer une route api pour les stats de répartition des utilisateurs

### ISSUE THREAD

**Issue by alice-telescoop** [betagouv/api-subventions-asso#850]
Pour widget #593 
Renvoyer un résultat du type `{ admins: 12, activeUsers: 56, inactiveUsers: 64 } `

**Comment by alice-telescoop** [comment]
@mxmeunier @VSerain J'ai proposé ce format pour me fixer les idées mais c'est sans doute bien d'avoir votre avis

**Comment by VSerain** [comment]
@alice-telescoop @mxmeunier on avait pas close ce ticket ?

**Comment by mxmeunier** [comment]
ah j'ai modifié l'autre et je l'ai rajouté ton le sprint mais j'ai pas supprimé celui-ci !
