### ISSUE TITLE
Mise à jour de la modale subvention

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#853]
Ajouter les parties "Établissement concerné" et "Informations collectées".

STUCK BY: #854
LINK TO: #697 
[FIGMA](https://www.figma.com/file/t6nWdBwKr8fancez3VO5kr/Data.Subvention-V0.4?node-id=8795%3A153527&t=dTlkllYlsIjYmKGK-0)

**Comment by mxmeunier** [comment]
![Image](https://user-images.githubusercontent.com/7630775/211522337-be7ac483-e8b9-4753-8340-5c429a4c5bb7.png)

**Comment by mxmeunier** [comment]
En draft en attente de réponse de Marion

**Comment by alice-telescoop** [comment]
remettre le label "Accordé" dans la colonne et renommer la colonne correspondante #1045

**Comment by alice-telescoop** [comment]
le reste dans #1114 #1115 #1116

**Comment by alice-telescoop** [comment]
#1108
