### ISSUE TITLE
Si pas d'info versement mais versement accordé : changer affichage

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#858]

**Comment by Gttnmarion** [comment]
Ne pas laisser de vide dans les cases où y'a pas d'info et préciser pouruqoi on a pas la donnée

**Comment by Gttnmarion** [comment]
@natoine est-ce qu'il ne faudrait pas revoir le wording pour raccourcir la phrase "Nous ne disposons pas encore de cette information" ?

Exemple : "information non récoltée" ou "Information actuellement indisponible" : ça permet d'alléger un peu plus sans perdre le sens de la phrase



![Image](https://user-images.githubusercontent.com/114912799/214066948-72415e7c-9317-48e5-b6b4-fdc226bca2c8.png)

**Comment by mxmeunier** [comment]
ticket dev #1111
