### ISSUE TITLE
Ajouter un message à la création d'un compte

### ISSUE THREAD

**Issue by mxmeunier** [betagouv/api-subventions-asso#875]
STUCK: en attente de la définition du message

**Comment by mxmeunier** [comment]
@natoine tu te souviens ?

**Comment by natoine** [comment]
Prévenir les utilisateurs que l'on conserve des données de leur parcours dans l'application dans le but d'améliorer l'application.
Je ne sais pas comment le phraser... Je propose ça mais ça suppose que l'on ait fini la page utilisateur aussi.

Peut-être : 

data.subvention est en cours de développement. Pour améliorer votre parcours utilisateur nous conservons des informations de votre navigation dans l'outil afin d'orienter nos prochains développements. Vous pouvez demander la suppression de ces informations via votre page personnelle.

**Comment by mxmeunier** [comment]
géré par #1408
