### ISSUE TITLE
Affichage UX du pourcentage de demandes accordées : biaisé

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#915]

**Comment by alice-telescoop** [comment]
+1 même souci avec la caisse des dépôts

**Comment by mxmeunier** [comment]
@Gttnmarion y a t'il un autre ticket lié à ce problème ? Avoir une solution ?

**Comment by Gttnmarion** [comment]
Je ne crois pas qu'il y ait d'autres ticket ! Le soucis était que le pourcentage est pas toujours bon. 
Du coup il a été suggéré d'ajouter sous la phrase 'XX% des demandes ont été accordées en 2022. D'après les données récupérées via X.'
Cette phrase :  
' *Certaines informations et données peuvent être manquantes car elles n’ont pas encore été rattachées au service.'

**Comment by alice-telescoop** [comment]
> Je ne crois pas qu'il y ait d'autres ticket ! Le soucis était que le pourcentage est pas toujours bon. Du coup il a été suggéré d'ajouter sous la phrase 'XX% des demandes ont été accordées en 2022. D'après les données récupérées via X.' Cette phrase : ' *Certaines informations et données peuvent être manquantes car elles n’ont pas encore été rattachées au service.'

ok et pour ça on a bien un ticket dev #1113. Est-ce que ça clôt la question de ce ticket-ci ?
