### ISSUE TITLE
[OSIRIS] investigation sur les dates

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#942]
Il faut réussir à trouver les correspondances dans les données OSIRIS / LCA

Le but est de trouver les dates dans osiris qui correspondent à :
- date de dépôt dans LCA (stuck by #1036)
- date de décision ==  date commission si présente sinon pas dispo (sauf via le dump)
- date d'instruction (Pas accessible uniquement via le dump)

**Comment by VSerain** [comment]
Voir avec @VSerain si besoin

**Comment by mxmeunier** [comment]
@VSerain collector comme ticket :)

**Comment by VSerain** [comment]
:D on en repalera en point ticket !

**Comment by mxmeunier** [comment]
@VSerain au boulot

**Comment by VSerain** [comment]
@alice-telescoop @mxmeunier ducoup je me demande si c'est toujours une investigation ou bien si on à assez d'information pour faire le ticket

**Comment by mxmeunier** [comment]
> @alice-telescoop @mxmeunier ducoup je me demande si c'est toujours une investigation ou bien si on à assez d'information pour faire le ticket

Comment tu sais que certaines dates ne sont disponibles qu'avec le dump sachant qu'on a pas encore joué avec LCA ?

**Comment by VSerain** [comment]
> > @alice-telescoop @mxmeunier ducoup je me demande si c'est toujours une investigation ou bien si on à assez d'information pour faire le ticket
> 
> Comment tu sais que certaines dates ne sont disponibles qu'avec le dump sachant qu'on a pas encore joué avec LCA ?

On a déjà joué avec des données LCA (On a un parser/service LCA et des data dans le drive), par contre, on ne sait pas comment les récupérer de manière automatiser !

**Comment by mxmeunier** [comment]
Vu avec JFM il va rajouter les dates qui vont bien dans l'extrait
