### ISSUE TITLE
Créer un DTO OpenDataSubventionDto (dans le dossier subvention)

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#947]
voir https://schema.data.gouv.fr/scdl/subventions/2.0.2/documentation.html#nom-de-l'attribuant-propriete-nomattribuant
```[tasklist]
- [ ] https://github.com/betagouv/api-subventions-asso/issues/1417
```

**Comment by VSerain** [comment]
nomAttribuant = service Instructeur
idAttribuant = siret service Instructeur (Pour l'instant "00000000000000")
dateConvention = ?
date** = Comme chez nous
referenceDecision ?= EJ
nomBeneficiaire = nom d'asso
idBeneficiaire = siret de l'etablissement
object = Intitulée de l'action
montant = montant attribuée
nature = toujours "aide en numéraire"
conditionsVersement = unique si un versement trouver echelonné sur plusieurs versements
datePeridodeVersement = FONJEP (DATE debut et fin ternalie), Osiris anuelle = entre 01/01/yyyy et 31/12/yyyy si plurie anuel 01/01/yyy1 et 31/12/yyyn dauphin voirs si on peut par trouver plus d'info

notificationUE= pour l'instant non mais surment ne sait pas
pourcentageSubvention= 1

**Comment by mxmeunier** [comment]
@natoine est-ce qu'on fait le vrai "open-data dto" ou est-ce qu'on fait notre propre format pour remonter les données de subventions

**Comment by alice-telescoop** [comment]
Discussion du 12 mai avec Antoine : on ouvre d'abord avec une version "censurée" de notre format socle commun, et on adaptera au format d'etalab dans un second temps

**Comment by alice-telescoop** [comment]
pour les dates : #1417

**Comment by mxmeunier** [comment]
En attente de la réponse de Périca ? @natoine
