### ISSUE TITLE
[OsirisAction] Créer une méthode initIndexes

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#963]
Dans le fichier repository, créer une méthode initIndexes qui permet de créer les indexés dans la collection :
- indexedInformations.osirisActionId (unique true)
- indexedInformations.compteAssoId
- indexedInformations.siret

**Comment by mxmeunier** [comment]
mise à jour sur l'unicité de osirisActionId car le reste était déjà fait
