### ISSUE TITLE
[Stats] NB de requêtes par mois : utiliser la table stats-associations-view

### ISSUE THREAD

**Issue by VSerain** [betagouv/api-subventions-asso#984]
Les stats remontes toutes les requêtes (y compris documents, login, etc). Désormais on souhaite ne remonter que les requêtes sur la page asso et la page établissement !

Utiliser la table stats-associations-view

PS:  route `/stats/requests/monthly/{year}`

**Comment by mxmeunier** [comment]
à clôturer car doublon avec #1109
