### ISSUE TITLE
Afficher les BOP

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#990]

**Comment by Gttnmarion** [comment]
Proposition d'affichage de BOP @natoine : quand on clique sur la ligne on retrouve la modale de détail des versements avec : 
- le montant versé
- le domaine fonctionnel
- l'activité
- le centre financier
- la date du versement effectué
- le numéro de BOP

![Image](https://user-images.githubusercontent.com/114912799/224748077-89a6e32a-aab6-46a4-a155-47f6f161b2fb.png)

**Comment by mxmeunier** [comment]
ticket dev #1018
