### ISSUE TITLE
Établissement concerné par un financement d'une asso

### ISSUE THREAD

**Issue by Gttnmarion** [betagouv/api-subventions-asso#993]

**Comment by Gttnmarion** [comment]
En tant qu'utilisateur, je veux savoir sur une ligne de financement d'une sub à une asso quel établissement est financé et combien

**Comment by Gttnmarion** [comment]
![Image](https://user-images.githubusercontent.com/114912799/220927673-5322065b-b701-447e-98c4-712bec0fb4dd.png)

**Comment by mxmeunier** [comment]
@Gttnmarion toujours d'actualité ou alors c'est présent dans la modale ?

**Comment by Gttnmarion** [comment]
C'est présent dans le tableau directement, sur la colonne de droite : l'objectif est de pouvoir savoir quel établissement est concerné par une subvention. Du coup on a une colonne 'établissement'

**Comment by mxmeunier** [comment]
Ok je crée le ticket correspondant

**Comment by mxmeunier** [comment]
dev #1143
